Exiv2: Exiv2::Internal::TiffFinder Class Reference
Exiv2::Internal::TiffFinder Class Reference
Search the composite for a component with tag and group. Return a pointer to the component or 0, if not found. The class is ready for a first search after construction and can be re-initialized with init().
#include <tiffvisitor_int.hpp>
Public Member Functions
Creators
TiffFinder (uint16_t tag, IfdId group)
Constructor, taking tag and group of the component to find.
virtual ~TiffFinder ()
Virtual destructor.
Manipulators
virtual void visitEntry (TiffEntry *object)
Find tag and group in a TIFF entry.
virtual void visitDataEntry (TiffDataEntry *object)
Find tag and group in a TIFF data entry.
virtual void visitImageEntry (TiffImageEntry *object)
Find tag and group in a TIFF image entry.
virtual void visitSizeEntry (TiffSizeEntry *object)
Find tag and group in a TIFF size entry.
virtual void visitDirectory (TiffDirectory *object)
Find tag and group in a TIFF directory.
virtual void visitSubIfd (TiffSubIfd *object)
Find tag and group in a TIFF sub-IFD.
virtual void visitMnEntry (TiffMnEntry *object)
Find tag and group in a TIFF makernote.
virtual void visitIfdMakernote (TiffIfdMakernote *object)
Find tag and group in an IFD makernote.
virtual void visitBinaryArray (TiffBinaryArray *object)
Find tag and group in a binary array.
virtual void visitBinaryElement (TiffBinaryElement *object)
Find tag and group in an element of a binary array.
void findObject (TiffComponent *object)
Check if object matches tag and group.
void init (uint16_t tag, IfdId group)
Initialize the Finder for a new search.
Public Member Functions inherited from Exiv2::Internal::TiffVisitor
TiffVisitor ()
Default constructor. Initialises all stop/go flags to true.
virtual ~TiffVisitor ()
Virtual destructor.
void setGo (GoEvent event, bool go)
Set the stop/go flag: true for go, false for stop.
virtual void visitDirectoryNext (TiffDirectory *object)
Operation to perform for a TIFF directory, after all components and before the next entry is processed.
virtual void visitDirectoryEnd (TiffDirectory *object)
Operation to perform for a TIFF directory, at the end of the processing.
virtual void visitIfdMakernoteEnd (TiffIfdMakernote *object)
Operation to perform after processing an IFD makernote.
virtual void visitBinaryArrayEnd (TiffBinaryArray *object)
Operation to perform for a TIFF binary array, at the end of the processing.
bool go (GoEvent event) const
Check if stop flag for event is clear, return true if it's clear.
Accessors
TiffComponent * result () const
Return the search result. 0 if no TIFF component was found for the tag and group combination.
Additional Inherited Members
Public Types inherited from Exiv2::Internal::TiffVisitor
enum GoEvent { geTraverse = 0 , geKnownMakernote = 1 }
Events for the stop/go flag. See setGo().
Detailed Description
Search the composite for a component with tag and group. Return a pointer to the component or 0, if not found. The class is ready for a first search after construction and can be re-initialized with init().
Member Function Documentation
visitBinaryArray()
void Exiv2::Internal::TiffFinder::visitBinaryArray (TiffBinaryArray * object) virtual
Find tag and group in a binary array.
Implements Exiv2::Internal::TiffVisitor.
References findObject().
visitBinaryElement()
void Exiv2::Internal::TiffFinder::visitBinaryElement (TiffBinaryElement * object) virtual
Find tag and group in an element of a binary array.
Implements Exiv2::Internal::TiffVisitor.
References findObject().
visitDataEntry()
void Exiv2::Internal::TiffFinder::visitDataEntry (TiffDataEntry * object) virtual
Find tag and group in a TIFF data entry.
Implements Exiv2::Internal::TiffVisitor.
References findObject().
visitDirectory()
void Exiv2::Internal::TiffFinder::visitDirectory (TiffDirectory * object) virtual
Find tag and group in a TIFF directory.
Implements Exiv2::Internal::TiffVisitor.
References findObject().
visitEntry()
void Exiv2::Internal::TiffFinder::visitEntry (TiffEntry * object) virtual
Find tag and group in a TIFF entry.
Implements Exiv2::Internal::TiffVisitor.
References findObject().
visitIfdMakernote()
void Exiv2::Internal::TiffFinder::visitIfdMakernote (TiffIfdMakernote * object) virtual
Find tag and group in an IFD makernote.
Implements Exiv2::Internal::TiffVisitor.
References findObject().
visitImageEntry()
void Exiv2::Internal::TiffFinder::visitImageEntry (TiffImageEntry * object) virtual
Find tag and group in a TIFF image entry.
Implements Exiv2::Internal::TiffVisitor.
References findObject().
visitMnEntry()
void Exiv2::Internal::TiffFinder::visitMnEntry (TiffMnEntry * object) virtual
Find tag and group in a TIFF makernote.
Implements Exiv2::Internal::TiffVisitor.
References findObject().
visitSizeEntry()
void Exiv2::Internal::TiffFinder::visitSizeEntry (TiffSizeEntry * object) virtual
Find tag and group in a TIFF size entry.
Implements Exiv2::Internal::TiffVisitor.
References findObject().
visitSubIfd()
void Exiv2::Internal::TiffFinder::visitSubIfd (TiffSubIfd * object) virtual
Find tag and group in a TIFF sub-IFD.
Implements Exiv2::Internal::TiffVisitor.
References findObject().
The documentation for this class was generated from the following files:
tiffvisitor_int.hpp
tiffvisitor_int.cpp