Exiv2: Exiv2::Image Class Reference
Exiv2::Image Class Reference abstract
Abstract base class defining the interface for an image. This is the top-level interface to the Exiv2 library.
#include <image.hpp>
Public Types
typedef std::auto_ptr< Image > AutoPtr
Image auto_ptr type.
Public Member Functions
Creators
Image (int imageType, uint16_t supportedMetadata, BasicIo::AutoPtr io)
Constructor taking the image type, a bitmap of the supported metadata types and an auto-pointer that owns an IO instance. See subclass constructor doc.
virtual ~Image ()
Virtual Destructor.
Manipulators
virtual void printStructure (std::ostream &out, PrintStructureOption option=kpsNone, int depth=0)
Print out the structure of image file.
virtual void readMetadata ()=0
Read all metadata supported by a specific image format from the image. Before this method is called, the image metadata will be cleared.
virtual void writeMetadata ()=0
Write metadata back to the image.
virtual void setExifData (const ExifData &exifData)
Assign new Exif data. The new Exif data is not written to the image until the writeMetadata() method is called.
virtual void clearExifData ()
Erase any buffered Exif data. Exif data is not removed from the actual image until the writeMetadata() method is called.
virtual void setIptcData (const IptcData &iptcData)
Assign new IPTC data. The new IPTC data is not written to the image until the writeMetadata() method is called.
virtual void clearIptcData ()
Erase any buffered IPTC data. IPTC data is not removed from the actual image until the writeMetadata() method is called.
virtual void setXmpPacket (const std::string &xmpPacket)
Assign a raw XMP packet. The new XMP packet is not written to the image until the writeMetadata() method is called.
virtual void clearXmpPacket ()
Erase the buffered XMP packet. XMP data is not removed from the actual image until the writeMetadata() method is called.
virtual void setXmpData (const XmpData &xmpData)
Assign new XMP data. The new XMP data is not written to the image until the writeMetadata() method is called.
virtual void clearXmpData ()
Erase any buffered XMP data. XMP data is not removed from the actual image until the writeMetadata() method is called.
virtual void setComment (const std::string &comment)
Set the image comment. The new comment is not written to the image until the writeMetadata() method is called.
virtual void clearComment ()
Erase any buffered comment. Comment is not removed from the actual image until the writeMetadata() method is called.
virtual void setIccProfile (DataBuf &iccProfile, bool bTestValid=true)
Set the image iccProfile. The new profile is not written to the image until the writeMetadata() method is called.
virtual void clearIccProfile ()
Erase iccProfile. the profile is not removed from the actual image until the writeMetadata() method is called.
virtual bool iccProfileDefined ()
Erase iccProfile. the profile is not removed from the actual image until the writeMetadata() method is called.
virtual DataBuf * iccProfile ()
return iccProfile
virtual void setMetadata (const Image &image)
Copy all existing metadata from source Image. The data is copied into internal buffers and is not written to the image until the writeMetadata() method is called.
virtual void clearMetadata ()
Erase all buffered metadata. Metadata is not removed from the actual image until the writeMetadata() method is called.
virtual ExifData & exifData ()
Returns an ExifData instance containing currently buffered Exif data.
virtual IptcData & iptcData ()
Returns an IptcData instance containing currently buffered IPTC data.
virtual XmpData & xmpData ()
Returns an XmpData instance containing currently buffered XMP data.
virtual std::string & xmpPacket ()
Return a modifiable reference to the raw XMP packet.
void writeXmpFromPacket (bool flag)
Determine the source when writing XMP.
void setByteOrder (ByteOrder byteOrder)
Set the byte order to encode the Exif metadata in.
void printTiffStructure (BasicIo &io, std::ostream &out, PrintStructureOption option, int depth, size_t offset=0)
Print out the structure of image file.
void printIFDStructure (BasicIo &io, std::ostream &out, Exiv2::PrintStructureOption option, uint32_t start, bool bSwap, char c, int depth)
Print out the structure of a TIFF IFD.
bool isBigEndianPlatform ()
is the host platform bigEndian
bool isLittleEndianPlatform ()
is the host platform littleEndian
bool isStringType (uint16_t type)
bool isShortType (uint16_t type)
bool isLongType (uint16_t type)
bool isLongLongType (uint16_t type)
bool isRationalType (uint16_t type)
bool is2ByteType (uint16_t type)
bool is4ByteType (uint16_t type)
bool is8ByteType (uint16_t type)
bool isPrintXMP (uint16_t type, Exiv2::PrintStructureOption option)
bool isPrintICC (uint16_t type, Exiv2::PrintStructureOption option)
uint64_t byteSwap (uint64_t value, bool bSwap) const
uint32_t byteSwap (uint32_t value, bool bSwap) const
uint16_t byteSwap (uint16_t value, bool bSwap) const
uint16_t byteSwap2 (const DataBuf &buf, size_t offset, bool bSwap) const
uint32_t byteSwap4 (const DataBuf &buf, size_t offset, bool bSwap) const
uint64_t byteSwap8 (const DataBuf &buf, size_t offset, bool bSwap) const
Accessors
BasicIo::AutoPtr io_
Image data IO pointer.
ExifData exifData_
Exif data container.
IptcData iptcData_
IPTC data container.
XmpData xmpData_
XMP data container.
DataBuf iccProfile_
ICC buffer (binary data)
std::string comment_
User comment.
std::string xmpPacket_
XMP packet.
int pixelWidth_
image pixel width
int pixelHeight_
image pixel height
NativePreviewList nativePreviews_
list of native previews
ByteOrder byteOrder () const
Return the byte order in which the Exif metadata of the image is encoded. Initially, it is not set (invalidByteOrder).
bool good () const
Check if the Image instance is valid. Use after object construction.
virtual std::string mimeType () const =0
Return the MIME type of the image.
virtual int pixelWidth () const
Return the pixel width of the image.
virtual int pixelHeight () const
Return the pixel height of the image.
virtual const ExifData & exifData () const
Returns an ExifData instance containing currently buffered Exif data.
virtual const IptcData & iptcData () const
Returns an IptcData instance containing currently buffered IPTC data.
virtual const XmpData & xmpData () const
Returns an XmpData instance containing currently buffered XMP data.
virtual std::string comment () const
Return a copy of the image comment. May be an empty string.
virtual const std::string & xmpPacket () const
Return the raw XMP packet as a string.
virtual BasicIo & io () const
Return a reference to the BasicIo instance being used for Io.
AccessMode checkMode (MetadataId metadataId) const
Returns the access mode, i.e., the metadata functions, which this image supports for the metadata type metadataId.
bool supportsMetadata (MetadataId metadataId) const
Check if image supports a particular type of metadata. This method is deprecated. Use checkMode() instead.
bool writeXmpFromPacket () const
Return the flag indicating the source when writing XMP metadata.
const NativePreviewList & nativePreviews () const
Return list of native previews. This is meant to be used only by the PreviewManager.
void setTypeSupported (int imageType, uint16_t supportedMetadata)
set type support for this image format
int imageType () const
set type support for this image format
const std::string & tagName (uint16_t tag)
Return tag name for given tag id.
const char * typeName (uint16_t tag) const
Return tag type for given tag id.
Detailed Description
Abstract base class defining the interface for an image. This is the top-level interface to the Exiv2 library.
Image has containers to store image metadata and subclasses implement read and save metadata from and to specific image formats.
Most client apps will obtain an Image instance by calling a static ImageFactory method. The Image class can then be used to to read, write, and save metadata.
Member Function Documentation
checkMode()
AccessMode Exiv2::Image::checkMode (MetadataId metadataId) const
Returns the access mode, i.e., the metadata functions, which this image supports for the metadata type metadataId.
Parameters
metadataId The metadata identifier.
Returns
Access mode for the requested image type and metadata identifier.
References Exiv2::ImageFactory::checkMode().
Referenced by setMetadata().
clearXmpData()
void Exiv2::Image::clearXmpData () virtual
Erase any buffered XMP data. XMP data is not removed from the actual image until the writeMetadata() method is called.
This has the same effect as clearXmpPacket() but operates on the buffered parsed XMP data.
Subsequent calls to writeMetadata() encode the XMP data to a raw XMP packet and write the newly encoded packet to the image. In the process, the buffered raw XMP packet is updated. In order to write directly from the raw XMP packet, use writeXmpFromPacket(true) or setXmpPacket().
References Exiv2::XmpData::clear(), writeXmpFromPacket(), and xmpData_.
Referenced by clearMetadata().
clearXmpPacket()
void Exiv2::Image::clearXmpPacket () virtual
Erase the buffered XMP packet. XMP data is not removed from the actual image until the writeMetadata() method is called.
This has the same effect as clearXmpData() but operates on the buffered raw XMP packet only, not the parsed XMP data.
Subsequent calls to writeMetadata() write the XMP packet from the buffered raw XMP packet rather than from buffered parsed XMP data. In order to write from parsed XMP data again, use either writeXmpFromPacket(false) or setXmpData().
References writeXmpFromPacket(), and xmpPacket_.
Referenced by clearMetadata().
exifData() [1/2]
ExifData & Exiv2::Image::exifData () virtual
Returns an ExifData instance containing currently buffered Exif data.
The contained Exif data may have been read from the image by a previous call to readMetadata() or added directly. The Exif data in the returned instance will be written to the image when writeMetadata() is called.
Returns
modifiable ExifData instance containing Exif values
References exifData_.
Referenced by Exiv2::CrwParser::decode(), Exiv2::Jp2Image::readMetadata(), Exiv2::PgfImage::readMetadata(), Exiv2::Rw2Image::readMetadata(), setExifData(), and setMetadata().
exifData() [2/2]
const ExifData & Exiv2::Image::exifData () const virtual
Returns an ExifData instance containing currently buffered Exif data.
The Exif data may have been read from the image by a previous call to readMetadata() or added directly. The Exif data in the returned instance will be written to the image when writeMetadata() is called.
Returns
read only ExifData instance containing Exif values
References exifData_.
good()
bool Exiv2::Image::good () const
Check if the Image instance is valid. Use after object construction.
Returns
true if the Image is in a valid state.
References Exiv2::ImageFactory::checkType(), and io_.
io()
BasicIo & Exiv2::Image::io () const virtual
Return a reference to the BasicIo instance being used for Io.
This refence is particularly useful to reading the results of operations on a MemIo instance. For example after metadata has been modified and the writeMetadata() method has been called, this method can be used to get access to the modified image.
Returns
BasicIo instance that can be used to read or write image data directly.
Note
If the returned BasicIo is used to write to the image, the Image class will not see those changes until the readMetadata() method is called.
References io_.
Referenced by printIFDStructure(), Exiv2::Cr2Image::printStructure(), Exiv2::OrfImage::printStructure(), Exiv2::RafImage::printStructure(), Exiv2::Rw2Image::printStructure(), Exiv2::WebPImage::printStructure(), Exiv2::TiffImage::printStructure(), printTiffStructure(), and Exiv2::CrwImage::readMetadata().
iptcData() [1/2]
IptcData & Exiv2::Image::iptcData () virtual
Returns an IptcData instance containing currently buffered IPTC data.
The contained IPTC data may have been read from the image by a previous call to readMetadata() or added directly. The IPTC data in the returned instance will be written to the image when writeMetadata() is called.
Returns
modifiable IptcData instance containing IPTC values
References iptcData_.
Referenced by Exiv2::Jp2Image::readMetadata(), Exiv2::PgfImage::readMetadata(), setIptcData(), and setMetadata().
iptcData() [2/2]
const IptcData & Exiv2::Image::iptcData () const virtual
Returns an IptcData instance containing currently buffered IPTC data.
The contained IPTC data may have been read from the image by a previous call to readMetadata() or added directly. The IPTC data in the returned instance will be written to the image when writeMetadata() is called.
Returns
modifiable IptcData instance containing IPTC values
References iptcData_.
mimeType()
virtual std::string Exiv2::Image::mimeType () const pure virtual
Return the MIME type of the image.
Note
For each supported image format, the library knows only one MIME type. This may not be the most specific MIME type for that format. In particular, several RAW formats are variants of the TIFF format with the same magic as TIFF itself. Class TiffImage handles most of them and thus they all have MIME type "image/tiff", although a more specific MIME type may exist (e.g., "image/x-nikon-nef").
Implemented in Exiv2::AsfVideo, Exiv2::BmffImage, Exiv2::BmpImage, Exiv2::Cr2Image, Exiv2::CrwImage, Exiv2::EpsImage, Exiv2::GifImage, Exiv2::Jp2Image, Exiv2::JpegImage, Exiv2::ExvImage, Exiv2::MatroskaVideo, Exiv2::MrwImage, Exiv2::OrfImage, Exiv2::PgfImage, Exiv2::PngImage, Exiv2::PsdImage, Exiv2::QuickTimeVideo, Exiv2::RafImage, Exiv2::RiffVideo, Exiv2::Rw2Image, Exiv2::TgaImage, Exiv2::TiffImage, Exiv2::WebPImage, and Exiv2::XmpSidecar.
pixelHeight()
int Exiv2::Image::pixelHeight () const virtual
Return the pixel height of the image.
Reimplemented in Exiv2::BmffImage, Exiv2::Cr2Image, Exiv2::CrwImage, Exiv2::MrwImage, Exiv2::OrfImage, Exiv2::RafImage, Exiv2::Rw2Image, and Exiv2::TiffImage.
References pixelHeight_.
pixelWidth()
int Exiv2::Image::pixelWidth () const virtual
Return the pixel width of the image.
Reimplemented in Exiv2::BmffImage, Exiv2::Cr2Image, Exiv2::CrwImage, Exiv2::MrwImage, Exiv2::OrfImage, Exiv2::RafImage, Exiv2::Rw2Image, and Exiv2::TiffImage.
References pixelWidth_.
printStructure()
void Exiv2::Image::printStructure (std::ostream & out, PrintStructureOption option = kpsNone, int depth = 0) virtual
Print out the structure of image file.
Exceptions
Error if reading of the file fails or the image data is not valid (does not look like data of the specific image type).
Warning
This function is not thread safe and intended for exiv2 -pS for debugging.
You may need to put the stream into binary mode (see src/actions.cpp)
Reimplemented in Exiv2::BmffImage, Exiv2::Cr2Image, Exiv2::Jp2Image, Exiv2::JpegBase, Exiv2::OrfImage, Exiv2::PngImage, Exiv2::RafImage, Exiv2::RiffVideo, Exiv2::Rw2Image, Exiv2::WebPImage, and Exiv2::TiffImage.
References io_.
printTiffStructure()
void Exiv2::Image::printTiffStructure (BasicIo & io, std::ostream & out, Exiv2::PrintStructureOption option, int depth, size_t offset = 0)
Print out the structure of image file.
Exceptions
Error if reading of the file fails or the image data is not valid (does not look like data of the specific image type).
References io(), isBigEndianPlatform(), isLittleEndianPlatform(), Exiv2::DataBuf::pData_, and printIFDStructure().
Referenced by printIFDStructure(), Exiv2::Cr2Image::printStructure(), Exiv2::Jp2Image::printStructure(), Exiv2::OrfImage::printStructure(), Exiv2::Rw2Image::printStructure(), Exiv2::WebPImage::printStructure(), and Exiv2::TiffImage::printStructure().
readMetadata()
virtual void Exiv2::Image::readMetadata () pure virtual
Read all metadata supported by a specific image format from the image. Before this method is called, the image metadata will be cleared.
This method returns success even if no metadata is found in the image. Callers must therefore check the size of individual metadata types before accessing the data.
Exceptions
Error if opening or reading of the file fails or the image data is not valid (does not look like data of the specific image type).
Implemented in Exiv2::AsfVideo, Exiv2::BmffImage, Exiv2::BmpImage, Exiv2::Cr2Image, Exiv2::CrwImage, Exiv2::EpsImage, Exiv2::GifImage, Exiv2::Jp2Image, Exiv2::JpegBase, Exiv2::MatroskaVideo, Exiv2::MrwImage, Exiv2::OrfImage, Exiv2::PgfImage, Exiv2::PngImage, Exiv2::PsdImage, Exiv2::QuickTimeVideo, Exiv2::RafImage, Exiv2::RiffVideo, Exiv2::Rw2Image, Exiv2::TgaImage, Exiv2::TiffImage, Exiv2::WebPImage, and Exiv2::XmpSidecar.
setByteOrder()
void Exiv2::Image::setByteOrder (ByteOrder byteOrder)
Set the byte order to encode the Exif metadata in.
The setting is only used when new Exif metadata is created and may not be applicable at all for some image formats. If the target image already contains Exif metadata, the byte order of the existing data is used. If byte order is not set when writeMetadata() is called, little-endian byte order (II) is used by default.
References byteOrder().
Referenced by Exiv2::Cr2Image::readMetadata(), Exiv2::Jp2Image::readMetadata(), Exiv2::JpegBase::readMetadata(), Exiv2::MrwImage::readMetadata(), Exiv2::OrfImage::readMetadata(), Exiv2::RafImage::readMetadata(), Exiv2::Rw2Image::readMetadata(), Exiv2::TiffImage::readMetadata(), Exiv2::Cr2Image::writeMetadata(), Exiv2::OrfImage::writeMetadata(), and Exiv2::TiffImage::writeMetadata().
setComment()
void Exiv2::Image::setComment (const std::string & comment) virtual
Set the image comment. The new comment is not written to the image until the writeMetadata() method is called.
Parameters
comment String containing comment.
Reimplemented in Exiv2::BmffImage, Exiv2::BmpImage, Exiv2::Cr2Image, Exiv2::EpsImage, Exiv2::GifImage, Exiv2::Jp2Image, Exiv2::MrwImage, Exiv2::OrfImage, Exiv2::PsdImage, Exiv2::RafImage, Exiv2::Rw2Image, Exiv2::TgaImage, Exiv2::TiffImage, Exiv2::WebPImage, and Exiv2::XmpSidecar.
References comment(), and comment_.
Referenced by setMetadata().
setExifData()
void Exiv2::Image::setExifData (const ExifData & exifData) virtual
Assign new Exif data. The new Exif data is not written to the image until the writeMetadata() method is called.
Parameters
exifData An ExifData instance holding Exif data to be copied
Reimplemented in Exiv2::BmpImage, Exiv2::GifImage, Exiv2::MrwImage, Exiv2::RafImage, Exiv2::Rw2Image, and Exiv2::TgaImage.
References exifData(), and exifData_.
Referenced by setMetadata().
setIccProfile()
void Exiv2::Image::setIccProfile (Exiv2::DataBuf & iccProfile, bool bTestValid = true) virtual
Set the image iccProfile. The new profile is not written to the image until the writeMetadata() method is called.
Parameters
iccProfile DataBuf containing profile (binary)
bTestValid - tests that iccProfile contains credible data
References Exiv2::getULong(), iccProfile(), iccProfile_, Exiv2::DataBuf::pData_, and Exiv2::DataBuf::size_.
Referenced by Exiv2::Jp2Image::readMetadata(), Exiv2::JpegBase::readMetadata(), and setMetadata().
setIptcData()
void Exiv2::Image::setIptcData (const IptcData & iptcData) virtual
Assign new IPTC data. The new IPTC data is not written to the image until the writeMetadata() method is called.
Parameters
iptcData An IptcData instance holding IPTC data to be copied
Reimplemented in Exiv2::WebPImage, Exiv2::BmpImage, Exiv2::CrwImage, Exiv2::GifImage, Exiv2::MrwImage, Exiv2::RafImage, Exiv2::Rw2Image, and Exiv2::TgaImage.
References iptcData(), and iptcData_.
Referenced by setMetadata().
setMetadata()
void Exiv2::Image::setMetadata (const Image & image) virtual
Copy all existing metadata from source Image. The data is copied into internal buffers and is not written to the image until the writeMetadata() method is called.
Parameters
image Metadata source. All metadata types are copied.
References checkMode(), comment(), exifData(), iccProfile(), iptcData(), setComment(), setExifData(), setIccProfile(), setIptcData(), setXmpData(), setXmpPacket(), xmpData(), and xmpPacket().
setXmpData()
void Exiv2::Image::setXmpData (const XmpData & xmpData) virtual
Assign new XMP data. The new XMP data is not written to the image until the writeMetadata() method is called.
Subsequent calls to writeMetadata() encode the XMP data to a raw XMP packet and write the newly encoded packet to the image. In the process, the buffered raw XMP packet is updated. In order to write directly from the raw XMP packet, use writeXmpFromPacket(true) or setXmpPacket().
Parameters
xmpData An XmpData instance holding XMP data to be copied
References writeXmpFromPacket(), xmpData(), and xmpData_.
Referenced by setMetadata().
setXmpPacket()
void Exiv2::Image::setXmpPacket (const std::string & xmpPacket) virtual
Assign a raw XMP packet. The new XMP packet is not written to the image until the writeMetadata() method is called.
Subsequent calls to writeMetadata() write the XMP packet from the buffered raw XMP packet rather than from buffered parsed XMP data. In order to write from parsed XMP data again, use either writeXmpFromPacket(false) or setXmpData().
Parameters
xmpPacket A string containing the raw XMP packet.
References Exiv2::XmpParser::decode(), xmpData_, xmpPacket(), and xmpPacket_.
Referenced by setMetadata().
typeName()
const char * Exiv2::Image::typeName (uint16_t tag) const protected
Return tag type for given tag id.
List of TIFF image tags
References Exiv2::asciiString, Exiv2::signedByte, Exiv2::signedLong, Exiv2::signedRational, Exiv2::signedShort, Exiv2::tiffDouble, Exiv2::tiffFloat, Exiv2::tiffIfd, Exiv2::undefined, Exiv2::unsignedByte, Exiv2::unsignedLong, Exiv2::unsignedRational, and Exiv2::unsignedShort.
Referenced by printIFDStructure().
writeMetadata()
virtual void Exiv2::Image::writeMetadata () pure virtual
Write metadata back to the image.
All existing metadata sections in the image are either created, replaced, or erased. If values for a given metadata type have been assigned, a section for that metadata type will either be created or replaced. If no values have been assigned to a given metadata type, any exists section for that metadata type will be removed from the image.
Exceptions
Error if the operation fails
Implemented in Exiv2::AsfVideo, Exiv2::BmffImage, Exiv2::BmpImage, Exiv2::Cr2Image, Exiv2::CrwImage, Exiv2::EpsImage, Exiv2::GifImage, Exiv2::Jp2Image, Exiv2::JpegBase, Exiv2::MatroskaVideo, Exiv2::MrwImage, Exiv2::OrfImage, Exiv2::PgfImage, Exiv2::PngImage, Exiv2::PsdImage, Exiv2::QuickTimeVideo, Exiv2::RafImage, Exiv2::RiffVideo, Exiv2::Rw2Image, Exiv2::TgaImage, Exiv2::TiffImage, Exiv2::WebPImage, and Exiv2::XmpSidecar.
writeXmpFromPacket()
void Exiv2::Image::writeXmpFromPacket (bool flag)
Determine the source when writing XMP.
Depending on the setting of this flag, writeMetadata() writes XMP from the buffered raw XMP packet or from parsed XMP data. The default is to write from parsed XMP data. The switch is also set by all functions to set and clear the buffered raw XMP packet and parsed XMP data, so using this function should usually not be necessary.
If Exiv2 was compiled without XMP support, the default for this flag is true and it will never be changed in order to preserve access to the raw XMP packet.
xmpData() [1/2]
XmpData & Exiv2::Image::xmpData () virtual
Returns an XmpData instance containing currently buffered XMP data.
The contained XMP data may have been read from the image by a previous call to readMetadata() or added directly. The XMP data in the returned instance will be written to the image when writeMetadata() is called.
Returns
modifiable XmpData instance containing XMP values
References xmpData_.
Referenced by Exiv2::Jp2Image::readMetadata(), Exiv2::PgfImage::readMetadata(), setMetadata(), setXmpData(), and Exiv2::TiffImage::writeMetadata().
xmpData() [2/2]
const XmpData & Exiv2::Image::xmpData () const virtual
Returns an XmpData instance containing currently buffered XMP data.
The contained XMP data may have been read from the image by a previous call to readMetadata() or added directly. The XMP data in the returned instance will be written to the image when writeMetadata() is called.
Returns
modifiable XmpData instance containing XMP values
References xmpData_.
The documentation for this class was generated from the following files:
image.hpp
image.cpp