Exiv2: Exiv2::XmpTextValue Class Reference
Exiv2::XmpTextValue Class Reference
Value type suitable for simple XMP properties and XMP nodes of complex types which are not parsed into specific values.
#include <value.hpp>
Public Types
typedef std::auto_ptr< XmpTextValue > AutoPtr
Shortcut for a XmpTextValue auto pointer.
Public Types inherited from Exiv2::XmpValue
enum XmpArrayType { xaNone , xaAlt , xaBag , xaSeq }
XMP array types.
enum XmpStruct { xsNone , xsStruct }
XMP structure indicator.
typedef std::auto_ptr< XmpValue > AutoPtr
Shortcut for a XmpValue auto pointer.
Public Types inherited from Exiv2::Value
typedef std::auto_ptr< Value > AutoPtr
Shortcut for a Value auto pointer.
Public Member Functions
Creators
XmpTextValue ()
Constructor.
XmpTextValue (const std::string &buf)
Constructor, reads the value from a string.
Manipulators
virtual int read (const std::string &buf)
Read a simple property value from buf to set the value.
virtual int read (const byte *buf, long len, ByteOrder byteOrder=invalidByteOrder)
Read the value from a character buffer.
virtual int read (const std::string &buf)=0
Set the value from a string buffer. The format of the string corresponds to that of the write() method, i.e., a string obtained through the write() method can be read by this function.
Public Member Functions inherited from Exiv2::XmpValue
XmpValue (TypeId typeId)
XmpArrayType xmpArrayType () const
Return XMP array type, indicates if an XMP value is an array.
XmpStruct xmpStruct () const
Return XMP struct, indicates if an XMP value is a structure.
virtual long copy (byte *buf, ByteOrder byteOrder=invalidByteOrder) const
Write value to a character data buffer.
void setXmpArrayType (XmpArrayType xmpArrayType)
Set the XMP array type to indicate that an XMP value is an array.
void setXmpStruct (XmpStruct xmpStruct=xsStruct)
Set the XMP struct type to indicate that an XMP value is a structure.
Public Member Functions inherited from Exiv2::Value
Value (TypeId typeId)
Constructor, taking a type id to initialize the base class with.
virtual ~Value ()
Virtual destructor.
virtual int setDataArea (const byte *buf, long len)
Set the data area, if the value has one by copying (cloning) the buffer pointed to by buf.
TypeId typeId () const
Return the type identifier (Exif data format type).
AutoPtr clone () const
Return an auto-pointer to a copy of itself (deep copy). The caller owns this copy and the auto-pointer ensures that it will be deleted.
std::string toString () const
Return the value as a string. Implemented in terms of write(std::ostream& os) const of the concrete class.
virtual std::string toString (long n) const
Return the n-th component of the value as a string. The default implementation returns toString(). The behaviour of this method may be undefined if there is no n-th component.
virtual long sizeDataArea () const
Return the size of the data area, 0 if there is none.
virtual DataBuf dataArea () const
Return a copy of the data area if the value has one. The caller owns this copy and DataBuf ensures that it will be deleted.
bool ok () const
Check the ok status indicator. After a to<Type> conversion, this indicator shows whether the conversion was successful.
Accessors
std::string value_
Stores the string values.
AutoPtr clone () const
long size () const
Return the size of the value in bytes.
virtual long count () const
Return the number of components of the value.
virtual long toLong (long n=0) const
Convert the value to a long. The optional parameter n is not used and is ignored.
virtual float toFloat (long n=0) const
Convert the value to a float. The optional parameter n is not used and is ignored.
virtual Rational toRational (long n=0) const
Convert the value to a Rational. The optional parameter n is not used and is ignored.
virtual std::ostream & write (std::ostream &os) const
Write the value to an output stream. You do not usually have to use this function; it is used for the implementation of the output operator for Value, operator<<(std::ostream &os, const Value &value).
Additional Inherited Members
Static Public Member Functions inherited from Exiv2::XmpValue
static XmpArrayType xmpArrayType (TypeId typeId)
Return XMP array type for an array Value TypeId, xaNone if typeId is not an XMP array value type.
Static Public Member Functions inherited from Exiv2::Value
static AutoPtr create (TypeId typeId)
A (simple) factory to create a Value type.
Protected Member Functions inherited from Exiv2::XmpValue
XmpValue & operator= (const XmpValue &rhs)
Assignment operator. Protected so that it can only be used by subclasses but not directly.
Protected Member Functions inherited from Exiv2::Value
Value & operator= (const Value &rhs)
Assignment operator. Protected so that it can only be used by subclasses but not directly.
Protected Attributes inherited from Exiv2::Value
bool ok_
Indicates the status of the previous to<Type> conversion.
Detailed Description
Value type suitable for simple XMP properties and XMP nodes of complex types which are not parsed into specific values.
Uses a std::string to store the value.
Examples
xmpsample.cpp.
Member Function Documentation
count()
long Exiv2::XmpTextValue::count () const virtual
Return the number of components of the value.
Implements Exiv2::Value.
References size().
read() [1/3]
int Exiv2::XmpValue::read (const byte * buf, long len, ByteOrder byteOrder = invalidByteOrder) virtual
Read the value from a character buffer.
Uses read(const std::string& buf)
Note
The byte order is required by the interface but not used by this method, so just use the default.
Parameters
buf Pointer to the data buffer to read from
len Number of bytes in the data buffer
byteOrder Byte order. Not needed.
Returns
0 if successful.
Reimplemented from Exiv2::XmpValue.
read() [2/3]
int Exiv2::XmpTextValue::read (const std::string & buf) virtual
Read a simple property value from buf to set the value.
Sets the value to the contents of buf. A optional keyword, type is supported to set the XMP value type. This is useful for complex value types for which Exiv2 does not have direct support.
The format of buf is:
[type=["]Alt|Bag|Seq|Struct["] ]text
Returns
0 if successful.
Implements Exiv2::XmpValue.
References Exiv2::XmpValue::setXmpArrayType(), Exiv2::XmpValue::setXmpStruct(), and value_.
Referenced by XmpTextValue().
read() [3/3]
virtual int Exiv2::XmpValue::read (const std::string & buf) virtual
Set the value from a string buffer. The format of the string corresponds to that of the write() method, i.e., a string obtained through the write() method can be read by this function.
Parameters
buf The string to read from.
Returns
0 if successful.
Implements Exiv2::XmpValue.
size()
long Exiv2::XmpTextValue::size () const virtual
Return the size of the value in bytes.
Reimplemented from Exiv2::XmpValue.
References value_.
Referenced by count().
toFloat()
float Exiv2::XmpTextValue::toFloat (long n = 0) const virtual
Convert the value to a float. The optional parameter n is not used and is ignored.
Returns
The converted value.
Implements Exiv2::Value.
References Exiv2::Value::ok_, Exiv2::parseFloat(), and value_.
toLong()
long Exiv2::XmpTextValue::toLong (long n = 0) const virtual
Convert the value to a long. The optional parameter n is not used and is ignored.
Returns
The converted value.
Implements Exiv2::Value.
References Exiv2::Value::ok_, Exiv2::parseLong(), and value_.
toRational()
Rational Exiv2::XmpTextValue::toRational (long n = 0) const virtual
Convert the value to a Rational. The optional parameter n is not used and is ignored.
Returns
The converted value.
Implements Exiv2::Value.
References Exiv2::Value::ok_, Exiv2::parseRational(), and value_.
write()
std::ostream & Exiv2::XmpTextValue::write (std::ostream & os) const virtual
Write the value to an output stream. You do not usually have to use this function; it is used for the implementation of the output operator for Value, operator<<(std::ostream &os, const Value &value).
Implements Exiv2::Value.
The documentation for this class was generated from the following files:
value.hpp
value.cpp