Exiv2: Exiv2::Internal::Nikon3MnHeader Class Reference
Exiv2::Internal::Nikon3MnHeader Class Reference
Header of a Nikon 3 Makernote.
#include <makernote_int.hpp>
Public Member Functions
Creators
Nikon3MnHeader ()
Default constructor.
virtual ~Nikon3MnHeader ()
Virtual destructor.
Manipulators
virtual bool read (const byte *pData, uint32_t size, ByteOrder byteOrder)
Read the header from a data buffer, return true if ok.
virtual void setByteOrder (ByteOrder byteOrder)
Set the byte order for the makernote.
Public Member Functions inherited from Exiv2::Internal::MnHeader
virtual ~MnHeader ()
Virtual destructor.
Accessors
virtual uint32_t size () const
Return the size of the header (in bytes).
virtual uint32_t write (IoWrapper &ioWrapper, ByteOrder byteOrder) const
Write the header to a data buffer, return the number of bytes written.
virtual uint32_t ifdOffset () const
Return the offset to the start of the Makernote IFD from the start of the Makernote (= the start of the header).
virtual ByteOrder byteOrder () const
Return the byte order for the makernote. If the return value is invalidByteOrder, this means that the byte order of the the image should be used for the makernote.
virtual uint32_t baseOffset (uint32_t mnOffset) const
Return the base offset for the makernote IFD entries relative to the start of the TIFF header. mnOffset is the offset to the makernote from the start of the TIFF header.
static uint32_t sizeOfSignature ()
Return the size of the makernote header signature.
Detailed Description
Header of a Nikon 3 Makernote.
Member Function Documentation
baseOffset()
uint32_t Exiv2::Internal::Nikon3MnHeader::baseOffset (uint32_t mnOffset) const virtual
Return the base offset for the makernote IFD entries relative to the start of the TIFF header. mnOffset is the offset to the makernote from the start of the TIFF header.
Reimplemented from Exiv2::Internal::MnHeader.
byteOrder()
ByteOrder Exiv2::Internal::Nikon3MnHeader::byteOrder () const virtual
Return the byte order for the makernote. If the return value is invalidByteOrder, this means that the byte order of the the image should be used for the makernote.
Reimplemented from Exiv2::Internal::MnHeader.
Referenced by setByteOrder(), and write().
ifdOffset()
uint32_t Exiv2::Internal::Nikon3MnHeader::ifdOffset () const virtual
Return the offset to the start of the Makernote IFD from the start of the Makernote (= the start of the header).
Reimplemented from Exiv2::Internal::MnHeader.
read()
bool Exiv2::Internal::Nikon3MnHeader::read (const byte * pData, uint32_t size, ByteOrder byteOrder) virtual
Read the header from a data buffer, return true if ok.
Implements Exiv2::Internal::MnHeader.
References Exiv2::DataBuf::alloc(), Exiv2::Internal::TiffHeaderBase::byteOrder(), Exiv2::Internal::TiffHeaderBase::offset(), Exiv2::DataBuf::pData_, Exiv2::Internal::TiffHeaderBase::read(), size(), Exiv2::DataBuf::size_, and sizeOfSignature().
setByteOrder()
void Exiv2::Internal::Nikon3MnHeader::setByteOrder (ByteOrder byteOrder) virtual
Set the byte order for the makernote.
Reimplemented from Exiv2::Internal::MnHeader.
References byteOrder().
size()
uint32_t Exiv2::Internal::Nikon3MnHeader::size () const virtual
Return the size of the header (in bytes).
Implements Exiv2::Internal::MnHeader.
References sizeOfSignature().
Referenced by read().
write()
uint32_t Exiv2::Internal::Nikon3MnHeader::write (IoWrapper & ioWrapper, ByteOrder byteOrder) const virtual
Write the header to a data buffer, return the number of bytes written.
Implements Exiv2::Internal::MnHeader.
References byteOrder(), Exiv2::DataBuf::pData_, Exiv2::DataBuf::size_, Exiv2::Internal::TiffHeaderBase::write(), and Exiv2::Internal::IoWrapper::write().
The documentation for this class was generated from the following files:
makernote_int.hpp
makernote_int.cpp