Exiv2: Exiv2::DateValue Class Reference
Exiv2::DateValue Class Reference
Value for simple ISO 8601 dates
#include <value.hpp>
Classes
struct Date
Simple Date helper structure.
Public Types
typedef std::auto_ptr< DateValue > AutoPtr
Shortcut for a DateValue auto pointer.
Public Types inherited from Exiv2::Value
typedef std::auto_ptr< Value > AutoPtr
Shortcut for a Value auto pointer.
Public Member Functions
Creators
DateValue ()
Default constructor.
DateValue (int year, int month, int day)
Constructor.
virtual ~DateValue ()
Virtual destructor.
Manipulators
virtual int read (const byte *buf, long len, ByteOrder byteOrder=invalidByteOrder)
Read the value from a character buffer.
virtual int read (const std::string &buf)
Set the value to that of the string buf.
void setDate (const Date &src)
Set the date.
Public Member Functions inherited from Exiv2::Value
Value (TypeId typeId)
Constructor, taking a type id to initialize the base class with.
virtual ~Value ()
Virtual destructor.
virtual int setDataArea (const byte *buf, long len)
Set the data area, if the value has one by copying (cloning) the buffer pointed to by buf.
TypeId typeId () const
Return the type identifier (Exif data format type).
AutoPtr clone () const
Return an auto-pointer to a copy of itself (deep copy). The caller owns this copy and the auto-pointer ensures that it will be deleted.
std::string toString () const
Return the value as a string. Implemented in terms of write(std::ostream& os) const of the concrete class.
virtual std::string toString (long n) const
Return the n-th component of the value as a string. The default implementation returns toString(). The behaviour of this method may be undefined if there is no n-th component.
virtual long sizeDataArea () const
Return the size of the data area, 0 if there is none.
virtual DataBuf dataArea () const
Return a copy of the data area if the value has one. The caller owns this copy and DataBuf ensures that it will be deleted.
bool ok () const
Check the ok status indicator. After a to<Type> conversion, this indicator shows whether the conversion was successful.
Accessors
AutoPtr clone () const
virtual long copy (byte *buf, ByteOrder byteOrder=invalidByteOrder) const
Write value to a character data buffer.
virtual const Date & getDate () const
Return date struct containing date information.
virtual long count () const
Return the number of components of the value.
virtual long size () const
Return the size of the value in bytes.
virtual std::ostream & write (std::ostream &os) const
Write the value to an output stream. You do not usually have to use this function; it is used for the implementation of the output operator for Value, operator<<(std::ostream &os, const Value &value).
virtual long toLong (long n=0) const
Return the value as a UNIX calender time converted to long.
virtual float toFloat (long n=0) const
Return the value as a UNIX calender time converted to float.
virtual Rational toRational (long n=0) const
Return the value as a UNIX calender time converted to Rational.
Additional Inherited Members
Static Public Member Functions inherited from Exiv2::Value
static AutoPtr create (TypeId typeId)
A (simple) factory to create a Value type.
Protected Member Functions inherited from Exiv2::Value
Value & operator= (const Value &rhs)
Assignment operator. Protected so that it can only be used by subclasses but not directly.
Protected Attributes inherited from Exiv2::Value
bool ok_
Indicates the status of the previous to<Type> conversion.
Detailed Description
Value for simple ISO 8601 dates
This class is limited to parsing simple date strings in the ISO 8601 format CCYYMMDD (century, year, month, day).
Member Function Documentation
copy()
long Exiv2::DateValue::copy (byte * buf, ByteOrder byteOrder = invalidByteOrder) const virtual
Write value to a character data buffer.
The user must ensure that the buffer has enough memory. Otherwise the call results in undefined behaviour.
Note
The byte order is required by the interface but not used by this method, so just use the default.
Parameters
buf Data buffer to write to.
byteOrder Byte order. Not used.
Returns
Number of characters written.
Implements Exiv2::Value.
References Exiv2::DateValue::Date::day, Exiv2::DateValue::Date::month, and Exiv2::DateValue::Date::year.
count()
long Exiv2::DateValue::count () const virtual
Return the number of components of the value.
Implements Exiv2::Value.
References size().
read() [1/2]
int Exiv2::DateValue::read (const byte * buf, long len, ByteOrder byteOrder = invalidByteOrder) virtual
Read the value from a character buffer.
Note
The byte order is required by the interface but not used by this method, so just use the default.
Parameters
buf Pointer to the data buffer to read from
len Number of bytes in the data buffer
byteOrder Byte order. Not needed.
Returns
0 if successful
1 in case of an unsupported date format
Implements Exiv2::Value.
References Exiv2::DateValue::Date::day, EXV_WARNING, Exiv2::DateValue::Date::month, and Exiv2::DateValue::Date::year.
read() [2/2]
int Exiv2::DateValue::read (const std::string & buf) virtual
Set the value to that of the string buf.
Parameters
buf String containing the date
Returns
0 if successful
1 in case of an unsupported date format
Implements Exiv2::Value.
References Exiv2::DateValue::Date::day, EXV_WARNING, Exiv2::DateValue::Date::month, and Exiv2::DateValue::Date::year.
size()
long Exiv2::DateValue::size () const virtual
Return the size of the value in bytes.
Implements Exiv2::Value.
Referenced by count().
toFloat()
float Exiv2::DateValue::toFloat (long n = 0) const virtual
Return the value as a UNIX calender time converted to float.
Implements Exiv2::Value.
References toLong().
toLong()
long Exiv2::DateValue::toLong (long n = 0) const virtual
Return the value as a UNIX calender time converted to long.
Implements Exiv2::Value.
References Exiv2::DateValue::Date::day, Exiv2::DateValue::Date::month, Exiv2::Value::ok_, and Exiv2::DateValue::Date::year.
Referenced by toFloat(), and toRational().
toRational()
Rational Exiv2::DateValue::toRational (long n = 0) const virtual
Return the value as a UNIX calender time converted to Rational.
Implements Exiv2::Value.
References toLong().
write()
std::ostream & Exiv2::DateValue::write (std::ostream & os) const virtual
Write the value to an output stream. You do not usually have to use this function; it is used for the implementation of the output operator for Value, operator<<(std::ostream &os, const Value &value).
Implements Exiv2::Value.
References Exiv2::DateValue::Date::day, Exiv2::DateValue::Date::month, and Exiv2::DateValue::Date::year.
The documentation for this class was generated from the following files:
value.hpp
value.cpp