Exiv2: Exiv2::XmpArrayValue Class Reference
Exiv2::XmpArrayValue Class Reference
Value type for simple arrays. Each item in the array is a simple value, without qualifiers. The array may be an ordered (seq), unordered (bag) or alternative array (alt). The array items must not contain qualifiers. For language alternatives use LangAltValue.
#include <value.hpp>
Public Types
typedef std::auto_ptr< XmpArrayValue > AutoPtr
Shortcut for a XmpArrayValue auto pointer.
Public Types inherited from Exiv2::XmpValue
enum XmpArrayType { xaNone , xaAlt , xaBag , xaSeq }
XMP array types.
enum XmpStruct { xsNone , xsStruct }
XMP structure indicator.
typedef std::auto_ptr< XmpValue > AutoPtr
Shortcut for a XmpValue auto pointer.
Public Types inherited from Exiv2::Value
typedef std::auto_ptr< Value > AutoPtr
Shortcut for a Value auto pointer.
Public Member Functions
Creators
XmpArrayValue (TypeId typeId=xmpBag)
Constructor. typeId can be one of xmpBag, xmpSeq or xmpAlt.
Manipulators
virtual int read (const std::string &buf)
Read a simple property value from buf and append it to the value.
virtual int read (const byte *buf, long len, ByteOrder byteOrder=invalidByteOrder)
Read the value from a character buffer.
virtual int read (const std::string &buf)=0
Set the value from a string buffer. The format of the string corresponds to that of the write() method, i.e., a string obtained through the write() method can be read by this function.
Public Member Functions inherited from Exiv2::XmpValue
XmpValue (TypeId typeId)
XmpArrayType xmpArrayType () const
Return XMP array type, indicates if an XMP value is an array.
XmpStruct xmpStruct () const
Return XMP struct, indicates if an XMP value is a structure.
virtual long size () const
Return the size of the value in bytes.
virtual long copy (byte *buf, ByteOrder byteOrder=invalidByteOrder) const
Write value to a character data buffer.
void setXmpArrayType (XmpArrayType xmpArrayType)
Set the XMP array type to indicate that an XMP value is an array.
void setXmpStruct (XmpStruct xmpStruct=xsStruct)
Set the XMP struct type to indicate that an XMP value is a structure.
Public Member Functions inherited from Exiv2::Value
Value (TypeId typeId)
Constructor, taking a type id to initialize the base class with.
virtual ~Value ()
Virtual destructor.
virtual int setDataArea (const byte *buf, long len)
Set the data area, if the value has one by copying (cloning) the buffer pointed to by buf.
TypeId typeId () const
Return the type identifier (Exif data format type).
AutoPtr clone () const
Return an auto-pointer to a copy of itself (deep copy). The caller owns this copy and the auto-pointer ensures that it will be deleted.
std::string toString () const
Return the value as a string. Implemented in terms of write(std::ostream& os) const of the concrete class.
virtual long sizeDataArea () const
Return the size of the data area, 0 if there is none.
virtual DataBuf dataArea () const
Return a copy of the data area if the value has one. The caller owns this copy and DataBuf ensures that it will be deleted.
bool ok () const
Check the ok status indicator. After a to<Type> conversion, this indicator shows whether the conversion was successful.
Accessors
AutoPtr clone () const
virtual long count () const
Return the number of components of the value.
virtual std::string toString (long n) const
Return the n-th component of the value as a string. The behaviour of this method may be undefined if there is no n-th component.
virtual long toLong (long n=0) const
Convert the n-th component of the value to a long. The behaviour of this method may be undefined if there is no n-th component.
virtual float toFloat (long n=0) const
Convert the n-th component of the value to a float. The behaviour of this method may be undefined if there is no n-th component.
virtual Rational toRational (long n=0) const
Convert the n-th component of the value to a Rational. The behaviour of this method may be undefined if there is no n-th component.
virtual std::ostream & write (std::ostream &os) const
Write all elements of the value to os, separated by commas.
Additional Inherited Members
Static Public Member Functions inherited from Exiv2::XmpValue
static XmpArrayType xmpArrayType (TypeId typeId)
Return XMP array type for an array Value TypeId, xaNone if typeId is not an XMP array value type.
Static Public Member Functions inherited from Exiv2::Value
static AutoPtr create (TypeId typeId)
A (simple) factory to create a Value type.
Protected Member Functions inherited from Exiv2::XmpValue
XmpValue & operator= (const XmpValue &rhs)
Assignment operator. Protected so that it can only be used by subclasses but not directly.
Protected Member Functions inherited from Exiv2::Value
Value & operator= (const Value &rhs)
Assignment operator. Protected so that it can only be used by subclasses but not directly.
Protected Attributes inherited from Exiv2::Value
bool ok_
Indicates the status of the previous to<Type> conversion.
Detailed Description
Value type for simple arrays. Each item in the array is a simple value, without qualifiers. The array may be an ordered (seq), unordered (bag) or alternative array (alt). The array items must not contain qualifiers. For language alternatives use LangAltValue.
Uses a vector of std::string to store the value(s).
Member Function Documentation
count()
long Exiv2::XmpArrayValue::count () const virtual
Return the number of components of the value.
Implements Exiv2::Value.
read() [1/3]
int Exiv2::XmpValue::read (const byte * buf, long len, ByteOrder byteOrder = invalidByteOrder) virtual
Read the value from a character buffer.
Uses read(const std::string& buf)
Note
The byte order is required by the interface but not used by this method, so just use the default.
Parameters
buf Pointer to the data buffer to read from
len Number of bytes in the data buffer
byteOrder Byte order. Not needed.
Returns
0 if successful.
Reimplemented from Exiv2::XmpValue.
read() [2/3]
int Exiv2::XmpArrayValue::read (const std::string & buf) virtual
Read a simple property value from buf and append it to the value.
Appends buf to the value after the last existing array element. Subsequent calls will therefore populate multiple array elements in the order they are read.
Returns
0 if successful.
Implements Exiv2::XmpValue.
read() [3/3]
virtual int Exiv2::XmpValue::read (const std::string & buf) virtual
Set the value from a string buffer. The format of the string corresponds to that of the write() method, i.e., a string obtained through the write() method can be read by this function.
Parameters
buf The string to read from.
Returns
0 if successful.
Implements Exiv2::XmpValue.
toFloat()
float Exiv2::XmpArrayValue::toFloat (long n = 0) const virtual
Convert the n-th component of the value to a float. The behaviour of this method may be undefined if there is no n-th component.
Returns
The converted value.
Implements Exiv2::Value.
References Exiv2::Value::ok_, and Exiv2::parseFloat().
toLong()
long Exiv2::XmpArrayValue::toLong (long n = 0) const virtual
Convert the n-th component of the value to a long. The behaviour of this method may be undefined if there is no n-th component.
Returns
The converted value.
Implements Exiv2::Value.
References Exiv2::Value::ok_, and Exiv2::parseLong().
toRational()
Rational Exiv2::XmpArrayValue::toRational (long n = 0) const virtual
Convert the n-th component of the value to a Rational. The behaviour of this method may be undefined if there is no n-th component.
Returns
The converted value.
Implements Exiv2::Value.
References Exiv2::Value::ok_, and Exiv2::parseRational().
toString()
std::string Exiv2::XmpArrayValue::toString (long n) const virtual
Return the n-th component of the value as a string. The behaviour of this method may be undefined if there is no n-th component.
Reimplemented from Exiv2::Value.
References Exiv2::Value::ok_.
write()
std::ostream & Exiv2::XmpArrayValue::write (std::ostream & os) const virtual
Write all elements of the value to os, separated by commas.
Note
The output of this method cannot directly be used as the parameter for read().
Implements Exiv2::Value.
The documentation for this class was generated from the following files:
value.hpp
value.cpp