Exiv2: Exiv2::Internal Namespace Reference
Exiv2::Internal Namespace Reference
Contains internal objects which are not published and are not part of the libexiv2 API.
Namespaces
namespace Tag
Classes
struct ArrayCfg
Additional configuration for a binary array.
struct ArrayDef
Defines one tag in a binary array.
struct ArraySet
Combination of array configuration and definition for arrays.
struct binaryToStringHelper
Helper struct for binary data output via binaryToString.
class CanonMakerNote
MakerNote for Canon cameras.
class Casio2MakerNote
MakerNote for Casio2 cameras.
class Casio2MnHeader
Header of a Casio2 Makernote.
class CasioMakerNote
MakerNote for Casio cameras.
class CiffComponent
Interface class for components of the CIFF directory hierarchy of a CRW (Canon Raw data) image. Both CIFF directories as well as entries implement this interface. This class is implemented as NVI (non-virtual interface).
class CiffDirectory
This class models a CIFF directory of a CRW (Canon Raw data) image.
class CiffEntry
This class models one directory entry of a CIFF directory of a CRW (Canon Raw data) image.
class CiffHeader
This class models the header of a CRW (Canon Raw data) image. It is the head of a CIFF parse tree, consisting of CiffDirectory and CiffEntry objects. Most of its methods will walk the parse tree to perform the requested action.
struct ConstSliceBase
This class provides the public-facing const-qualified methods of a slice.
struct ContainerStorage
class Cr2Header
Canon CR2 header structure.
class CrwMap
Static class providing mapping functionality from CRW entries to image metadata and vice versa.
struct CrwMapping
Structure for a mapping table for conversion of CIFF entries to image metadata and vice versa.
struct CrwSubDir
Structure for the CIFF directory hierarchy.
class FindExifdatum
Unary predicate that matches an Exifdatum with a given IfdId.
class FujiMakerNote
MakerNote for Fujifilm cameras.
class FujiMnHeader
Header of a Fujifilm Makernote.
class IoWrapper
Simple IO wrapper to ensure that the header is only written if there is any other data at all.
struct LensIdFct
A lens id and a pretty-print function for special treatment of the id.
class LensInfoNotFound
struct LensTypeAndFocalLengthAndMaxAperture
Helper structure.
class MinoltaMakerNote
MakerNote for Minolta cameras.
class MnHeader
Makernote header interface. This class is used with TIFF makernotes.
struct MutableSliceBase
class Nikon1MakerNote
A MakerNote format used by Nikon cameras, such as the E990 and D1.
class Nikon2MakerNote
A second MakerNote format used by Nikon cameras, including the E700, E800, E900, E900S, E910, E950.
class Nikon2MnHeader
Header of a Nikon 2 Makernote.
class Nikon3MakerNote
A third MakerNote format used by Nikon cameras, e.g., E5400, SQ, D2H, D70.
class Nikon3MnHeader
Header of a Nikon 3 Makernote.
struct NikonArrayIdx
Structure for an index into the array set of complex binary arrays.
class OffsetWriter
Class to insert pointers or offsets to computed addresses at specific locations in an image. Used for offsets which are best computed during the regular write process. They are written in a second pass, using the writeOffsets() method.
class Olympus2MnHeader
Header of an Olympus II Makernote.
class OlympusMakerNote
MakerNote for Olympus cameras.
class OlympusMnHeader
Header of an Olympus Makernote.
class OrfHeader
Olympus ORF header structure.
class PanasonicMakerNote
MakerNote for Panasonic cameras.
class PanasonicMnHeader
Header of a Panasonic Makernote.
class PentaxDngMnHeader
Header of an Pentax DNG Makernote.
class PentaxMakerNote
MakerNote for Pentaxfilm cameras.
class PentaxMnHeader
Header of an Pentax Makernote.
class PngChunk
Stateless parser class for data in PNG chunk format. Images use this class to decode and encode PNG-based data.
struct PtrSliceStorage
Implementation of the storage concept for slices of C arrays.
struct remove_const
struct remove_const< const T >
struct remove_cv
struct remove_pointer
struct remove_pointer< T * >
struct remove_pointer< T *const >
struct remove_volatile
struct remove_volatile< volatile T >
class Rw2Header
Panasonic RW2 header structure.
class Samsung2MakerNote
MakerNote for Samsung cameras.
class SamsungMnHeader
Header of a Samsung Makernote, only used for the relative offset.
struct SectionInfo
The details of a section.
class SigmaMakerNote
MakerNote for Sigma (Foveon) cameras.
class SigmaMnHeader
Header of a Sigma Makernote.
struct SliceBase
class SonyMakerNote
MakerNote for Sony cameras.
class SonyMnHeader
Header of a Sony Makernote.
struct TagDetails
Helper structure for lookup tables for translations of numeric tag values to human readable labels.
struct TagDetailsBitmask
Helper structure for lookup tables for translations of bitmask values to human readable labels.
struct TagVocabulary
Helper structure for lookup tables for translations of controlled vocabulary strings to their descriptions.
class TiffBinaryArray
Composite to model an array of different tags. The tag types as well as other aspects of the array are configurable. The elements of this component are of type TiffBinaryElement.
class TiffBinaryElement
Element of a TiffBinaryArray.
class TiffComponent
Interface class for components of a TIFF directory hierarchy (Composite pattern). Both TIFF directories as well as entries implement this interface. A component can be uniquely identified by a tag, group tupel. This class is implemented as a NVI (Non-Virtual Interface) and it has an interface for visitors (Visitor pattern) to perform operations on all components.
class TiffCopier
Copy all image tags from the source tree (the tree that is traversed) to a target tree, which is empty except for the root element provided in the constructor.
class TiffCreator
TIFF component factory.
class TiffDataEntry
A standard TIFF IFD entry consisting of a value which is an offset to a data area and the data area. The size of the data area is provided in a related TiffSizeEntry, tag and group of which are set in the constructor.
class TiffDataEntryBase
Interface for a standard TIFF IFD entry consisting of a value which is a set of offsets to a data area. The sizes of these "strips" are provided in a related TiffSizeEntry, tag and group of which are set in the constructor. The implementations of this interface differ in whether the data areas are extracted to the higher level metadata (TiffDataEntry) or not (TiffImageEntry).
class TiffDecoder
TIFF composite visitor to decode metadata from the TIFF tree and add it to an Image, which is supplied in the constructor (Visitor pattern). Used by TiffParser to decode the metadata from a TIFF composite.
class TiffDirectory
This class models a TIFF directory (Ifd). It is a composite component of the TIFF tree.
class TiffEncoder
TIFF composite visitor to encode metadata from an image to the TIFF tree. The metadata containers and root element of the tree are supplied in the constructor. Used by TiffParserWorker to encode the metadata into a TIFF composite.
class TiffEntry
A standard TIFF IFD entry.
class TiffEntryBase
This abstract base class provides the common functionality of an IFD directory entry and defines an extended interface for derived concrete entries, which allows access to the attributes of the entry.
class TiffFinder
Search the composite for a component with tag and group. Return a pointer to the component or 0, if not found. The class is ready for a first search after construction and can be re-initialized with init().
struct TiffGroupStruct
Data structure used as a row (element) of a table (array) defining the TIFF component used for each tag in a group.
class TiffHeader
Standard TIFF header structure.
class TiffHeaderBase
Abstract base class defining the interface of an image header. Used internally by classes for TIFF-based images. Default implementation is for the regular TIFF header.
class TiffIfdMakernote
Tiff IFD Makernote. This is a concrete class suitable for all IFD makernotes.
class TiffImageEntry
A standard TIFF IFD entry consisting of a value which is an array of offsets to image data areas. The sizes of the image data areas are provided in a related TiffSizeEntry, tag and group of which are set in the constructor.
struct TiffImgTagStruct
Data structure used to list image tags for TIFF and TIFF-like images.
class TiffMapping
Table of TIFF decoding and encoding functions and find functions. This class is separated from the metadata decoder and encoder visitors so that the parser can be parametrized with a different table if needed. This is used, eg., for CR2 format, which uses a different decoder table.
struct TiffMappingInfo
TIFF mapping table for functions to decode special cases.
class TiffMnCreator
TIFF makernote factory for concrete TIFF makernotes.
class TiffMnEntry
This class is the basis for Makernote support in TIFF. It contains a pointer to a concrete Makernote. The TiffReader visitor has the responsibility to create the correct Make/Model specific Makernote for a particular TIFF file. Calls to child management methods are forwarded to the concrete Makernote, if there is one.
struct TiffMnRegistry
Makernote registry structure.
class TiffParserWorker
Stateless parser class for data in TIFF format. Images use this class to decode and encode TIFF-based data.
class TiffPathItem
A tupel consisting of extended Tag and group used as an item in TIFF paths.
class TiffReader
TIFF composite visitor to read the TIFF structure from a block of memory and build the composite from it (Visitor pattern). Used by TiffParser to read the TIFF data from a block of memory.
class TiffRwState
Simple state class containing relevant state information for the TIFF reader. This is in a separate class so that the reader can change state if needed (e.g., to read certain complex makernotes).
class TiffSizeEntry
A TIFF IFD entry containing the size of a data area of a related TiffDataEntry. This component is used, e.g. for Exif.Thumbnail.JPEGInterchangeFormatLength, which contains the size of Exif.Thumbnail.JPEGInterchangeFormat.
class TiffSubIfd
This class models a TIFF sub-directory (sub-IFD). A sub-IFD is an entry with one or more values that are pointers to IFD structures containing an IFD. The TIFF standard defines some important tags to be sub-IFDs, including the Exif and GPS tags.
struct TiffTreeStruct
Data structure used as a row of the table which describes TIFF trees. Multiple trees are needed as TIFF-based RAW image formats do not always use standard TIFF layout.
class TiffVisitor
Abstract base class defining the interface for TIFF composite visitors (Visitor pattern)
Typedefs
typedef void(* CrwDecodeFct) (const CiffComponent &, const CrwMapping *, Image &, ByteOrder)
Function pointer for functions to decode Exif tags from a CRW entry.
typedef void(* CrwEncodeFct) (const Image &, const CrwMapping *, CiffHeader *)
Function pointer for functions to encode CRW entries from Exif tags.
typedef std::stack< CrwSubDir > CrwDirs
Stack to hold a path of CRW directories.
typedef TiffComponent *(* NewMnFct) (uint16_t tag, IfdId group, IfdId mnGroup, const byte *pData, uint32_t size, ByteOrder byteOrder)
Type for a pointer to a function creating a makernote (image)
typedef TiffComponent *(* NewMnFct2) (uint16_t tag, IfdId group, IfdId mnGroup)
Type for a pointer to a function creating a makernote (group)
typedef uint16_t TiffType
TIFF value type.
typedef int(* CfgSelFct) (uint16_t, const byte *, uint32_t, TiffComponent *const)
Function pointer type for a function to determine which cfg + def of a corresponding array set to use.
typedef DataBuf(* CryptFct) (uint16_t, const byte *, uint32_t, TiffComponent *const)
Function pointer type for a crypt function used for binary arrays.
typedef void(TiffDecoder::* DecoderFct) (const TiffEntryBase *)
Function pointer type for a TiffDecoder member function to decode a TIFF component.
typedef void(TiffEncoder::* EncoderFct) (TiffEntryBase *, const Exifdatum *)
Function pointer type for a TiffDecoder member function to decode a TIFF component.
typedef DecoderFct(* FindDecoderFct) (const std::string &make, uint32_t extendedTag, IfdId group)
Type for a function pointer for a function to decode a TIFF component.
typedef EncoderFct(* FindEncoderFct) (const std::string &make, uint32_t extendedTag, IfdId group)
Type for a function pointer for a function to encode a TIFF component.
typedef std::auto_ptr< TiffComponent >(* NewTiffCompFct) (uint16_t tag, IfdId group)
Type for a function pointer for a function to create a TIFF component. Use TiffComponent::AutoPtr, it is not used in this declaration only to reduce dependencies.
typedef std::stack< TiffPathItem > TiffPath
Stack to hold a path from the TIFF root element to a TIFF entry.
typedef std::vector< IfdId > PrimaryGroups
Type for a list of primary image groups.
Enumerations
enum DataLocId { valueData , directoryData , lastDataLocId }
Type to identify where the data is stored in a directory.
enum IfdId {
ifdIdNotSet , ifd0Id , ifd1Id , ifd2Id ,
ifd3Id , exifId , gpsId , iopId ,
mpfId , subImage1Id , subImage2Id , subImage3Id ,
subImage4Id , subImage5Id , subImage6Id , subImage7Id ,
subImage8Id , subImage9Id , subThumb1Id , panaRawId ,
mnId , canonId , canonAf2Id , canonAf3Id ,
canonAfCId , canonAfMiAdjId , canonAmId , canonAsId ,
canonCbId , canonCiId , canonCsId , canonFilId ,
canonFlId , canonHdrId , canonLeId , canonMeId ,
canonMoID , canonMvId , canonRawBId , canonSiId ,
canonCfId , canonContrastId , canonFcd1Id , canonFcd2Id ,
canonFcd3Id , canonLiOpId , canonMyColorID , canonPiId ,
canonPaId , canonTiId , canonFiId , canonPrId ,
canonPreID , canonVigCorId , canonVigCor2Id , canonWbId ,
casioId , casio2Id , fujiId , minoltaId ,
minoltaCs5DId , minoltaCs7DId , minoltaCsOldId , minoltaCsNewId ,
nikon1Id , nikon2Id , nikon3Id , nikonPvId ,
nikonVrId , nikonPcId , nikonWtId , nikonIiId ,
nikonAfId , nikonAf21Id , nikonAf22Id , nikonAFTId ,
nikonFiId , nikonMeId , nikonFl1Id , nikonFl2Id ,
nikonFl3Id , nikonSi1Id , nikonSi2Id , nikonSi3Id ,
nikonSi4Id , nikonSi5Id , nikonSi6Id , nikonLd1Id ,
nikonLd2Id , nikonLd3Id , nikonLd4Id , nikonCb1Id ,
nikonCb2Id , nikonCb2aId , nikonCb2bId , nikonCb3Id ,
nikonCb4Id , olympusId , olympus2Id , olympusCsId ,
olympusEqId , olympusRdId , olympusRd2Id , olympusIpId ,
olympusFiId , olympusFe1Id , olympusFe2Id , olympusFe3Id ,
olympusFe4Id , olympusFe5Id , olympusFe6Id , olympusFe7Id ,
olympusFe8Id , olympusFe9Id , olympusRiId , panasonicId ,
pentaxId , pentaxDngId , samsung2Id , samsungPvId ,
samsungPwId , sigmaId , sony1Id , sony2Id ,
sonyMltId , sony1CsId , sony1Cs2Id , sony2CsId ,
sony2Cs2Id , sony2FpId , sony2010eId , sony1MltCs7DId ,
sony1MltCsOldId , sony1MltCsNewId , sony1MltCsA100Id , tagInfoMvId ,
lastId , ignoreId = lastId
}
Type to specify the IFD to which a metadata belongs.
enum SectionId {
sectionIdNotSet , imgStruct , recOffset , imgCharacter ,
otherTags , exifFormat , exifVersion , imgConfig ,
userInfo , relatedFile , dateTime , captureCond ,
gpsTags , iopTags , mpfTags , makerTags ,
dngTags , panaRaw , tiffEp , tiffPm6 ,
adobeOpi , lastSectionId
}
Section identifiers to logically group tags. A section consists of nothing more than a name, based on the Exif standard.
Functions
std::ostream & printCsLensByFocalLengthAndMaxAperture (std::ostream &os, const Value &value, const ExifData *metadata)
Special treatment pretty-print function for non-unique lens ids.
std::ostream & printCsLensByFocalLength (std::ostream &os, const Value &value, const ExifData *metadata)
Special treatment pretty-print function for non-unique lens ids.
std::ostream & printCsLensByFocalLengthTC (std::ostream &os, const Value &value, const ExifData *metadata)
Special treatment pretty-print function for non-unique lens ids.
std::ostream & printCsLensFFFF (std::ostream &os, const Value &value, const ExifData *metadata)
Special treatment pretty-print function for non-unique lens ids.
bool operator== (const TagDetails &td, const LensTypeAndFocalLengthAndMaxAperture &ltfl)
Compare tag details with a lens entry.
void extractLensFocalLength (LensTypeAndFocalLengthAndMaxAperture &ltfl, const ExifData *metadata)
extractLensFocalLength from metadata
void convertFocalLength (LensTypeAndFocalLengthAndMaxAperture &ltfl, double divisor)
convertFocalLength to a human readable string
float canonEv (long val)
Convert Canon hex-based EV (modulo 0x20) to real number Ported from Phil Harvey's Image::ExifTool::Canon::CanonEv by Will Stokes.
DataBuf packIfdId (const ExifData &exifData, IfdId ifdId, ByteOrder byteOrder)
Pack the tag values of all ifdId tags in exifData into a data buffer. This function is used to pack Canon Camera Settings1,2 and Custom Function tags.
std::string stringFormat (const char *format,...) ATTRIBUTE_FORMAT_PRINTF
format a string in the pattern of sprintf .
std::string binaryToHex (const byte *data, size_t size)
format binary for display of raw data .
std::string indent (int32_t depth)
indent output for kpsRecursive in printStructure() .
template<typename T >
std::ostream & operator<< (std::ostream &stream, const binaryToStringHelper< T > &binToStr)
Actual implementation of the output algorithm described in binaryToString.
template<typename T >
binaryToStringHelper< T > binaryToString (const Slice< T > sl) throw ()
format binary data for display in Image::printStructure()
std::string getExiv2ConfigPath ()
Determine the path to the Exiv2 configuration file.
std::string readExiv2Config (const std::string &section, const std::string &value, const std::string &def)
Read value from Exiv2 configuration file.
TiffComponent * newIfdMn (uint16_t tag, IfdId group, IfdId mnGroup, const byte *pData, uint32_t size, ByteOrder byteOrder)
Function to create a simple IFD makernote (Canon, Minolta, Nikon1)
TiffComponent * newIfdMn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create a simple IFD makernote (Canon, Minolta, Nikon1)
TiffComponent * newOlympusMn (uint16_t tag, IfdId group, IfdId mnGroup, const byte *pData, uint32_t size, ByteOrder byteOrder)
Function to create an Olympus makernote.
TiffComponent * newOlympusMn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create an Olympus makernote.
TiffComponent * newOlympus2Mn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create an Olympus II makernote.
TiffComponent * newFujiMn (uint16_t tag, IfdId group, IfdId mnGroup, const byte *pData, uint32_t size, ByteOrder byteOrder)
Function to create a Fujifilm makernote.
TiffComponent * newFujiMn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create a Fujifilm makernote.
TiffComponent * newNikonMn (uint16_t tag, IfdId group, IfdId mnGroup, const byte *pData, uint32_t size, ByteOrder byteOrder)
Function to create a Nikon makernote. This will create the appropriate Nikon 1, 2 or 3 makernote, based on the arguments.
TiffComponent * newNikon2Mn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create a Nikon2 makernote.
TiffComponent * newNikon3Mn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create a Nikon3 makernote.
TiffComponent * newPanasonicMn (uint16_t tag, IfdId group, IfdId mnGroup, const byte *pData, uint32_t size, ByteOrder byteOrder)
Function to create a Panasonic makernote.
TiffComponent * newPanasonicMn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create a Panasonic makernote.
TiffComponent * newPentaxMn (uint16_t tag, IfdId group, IfdId mnGroup, const byte *pData, uint32_t size, ByteOrder byteOrder)
Function to create an Pentax makernote.
TiffComponent * newPentaxMn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create an Pentax makernote.
TiffComponent * newPentaxDngMn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create an Pentax DNG makernote.
TiffComponent * newSamsungMn (uint16_t tag, IfdId group, IfdId mnGroup, const byte *pData, uint32_t size, ByteOrder byteOrder)
Function to create a Samsung makernote.
TiffComponent * newSamsungMn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create a Samsung makernote.
TiffComponent * newSigmaMn (uint16_t tag, IfdId group, IfdId mnGroup, const byte *pData, uint32_t size, ByteOrder byteOrder)
Function to create a Sigma makernote.
TiffComponent * newSigmaMn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create a Sigma makernote.
TiffComponent * newSonyMn (uint16_t tag, IfdId group, IfdId mnGroup, const byte *pData, uint32_t size, ByteOrder byteOrder)
Function to create a Sony makernote.
TiffComponent * newSony1Mn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create a Sony1 makernote.
TiffComponent * newSony2Mn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create a Sony2 makernote.
TiffComponent * newCasioMn (uint16_t tag, IfdId group, IfdId mnGroup, const byte *pData, uint32_t size, ByteOrder byteOrder)
Function to create a Casio2 makernote.
TiffComponent * newCasio2Mn2 (uint16_t tag, IfdId group, IfdId mnGroup)
Function to create a Casio2 makernote.
int nikonSelector (uint16_t tag, const byte *pData, uint32_t size, TiffComponent *const pRoot)
Function to select cfg + def of a Nikon complex binary array.
int nikonAf2Selector (uint16_t tag, const byte *pData, uint32_t size, TiffComponent *const pRoot)
Function to select cfg + def of a Nikon complex binary array.
DataBuf nikonCrypt (uint16_t tag, const byte *pData, uint32_t size, TiffComponent *const pRoot)
Encrypt and decrypt Nikon data.
int sonyCsSelector (uint16_t tag, const byte *pData, uint32_t size, TiffComponent *const pRoot)
Function to select cfg + def of the Sony Camera Settings complex binary array.
int sony2010eSelector (uint16_t tag, const byte *pData, uint32_t size, TiffComponent *const pRoot)
Function to select cfg + def of the Sony 2010 Miscellaneous Information complex binary array.
std::string & ltrim (std::string &s, const char *t=" \t\n\r\f\v")
std::string & rtrim (std::string &s, const char *t=" \t\n\r\f\v")
trim from right
std::string & trim (std::string &s, const char *t=" \t\n\r\f\v")
trim from left & right
std::ostream & printMinoltaSonyLensID (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony Lens id values to readable labels.
std::ostream & printMinoltaSonyColorMode (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony Color Mode values to readable labels.
std::ostream & printMinoltaSonyBoolValue (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony bool function values to readable labels.
std::ostream & printMinoltaSonyBoolInverseValue (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony bool inverse function values to readable labels.
std::ostream & printMinoltaSonyAFAreaMode (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony AF Area Mode values to readable labels.
std::ostream & printMinoltaSonyLocalAFAreaPoint (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony Local AF Area Point values to readable labels.
std::ostream & printMinoltaSonyDynamicRangeOptimizerMode (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony dynamic range optimizer mode values to readable labels.
std::ostream & printMinoltaSonyPrioritySetupShutterRelease (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony priority setup shutter release values to readable labels.
std::ostream & printMinoltaSonyQualityCs (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony Quality values to readable labels.
std::ostream & printMinoltaSonyRotation (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony Rotation values to readable labels.
std::ostream & printMinoltaSonySceneMode (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony Scene Mode values to readable labels.
std::ostream & printMinoltaSonyImageQuality (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony Image Quality values to readable labels.
std::ostream & printMinoltaSonyTeleconverterModel (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony Teleconverter Model values to readable labels.
std::ostream & printMinoltaSonyWhiteBalanceStd (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony White Balance Std values to readable labels.
std::ostream & printMinoltaSonyZoneMatching (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony ZoneMatching values to readable labels.
std::ostream & printMinoltaSonyFlashExposureComp (std::ostream &, const Value &, const ExifData *)
Print Minolta/Sony FlashExposureComp values to readable labels.
std::ostream & resolveLens0x32c (std::ostream &os, const Value &value, const ExifData *metadata)
resolveLens0x32c print lens in human format
std::ostream & resolveLens0x3ff (std::ostream &os, const Value &value, const ExifData *metadata)
resolveLens0x3ff print lens in human format
std::ostream & resolveLens0x8ff (std::ostream &os, const Value &value, const ExifData *metadata)
resolveLens0x8ff print lens in human format
std::ostream & resolveLens0x319 (std::ostream &os, const Value &value, const ExifData *metadata)
resolveLens0x319 print lens in human format
std::ostream & resolveLensType (std::ostream &os, const Value &value, const ExifData *metadata)
resolveLensType print lens in human format
std::ostream & printLensType (std::ostream &os, const Value &value, const ExifData *metadata)
A lens id and a pretty-print function for special treatment of the id.
template<int N, const TagDetails(&) array, int count, int ignoredcount, int ignoredcountmax>
std::ostream & printCombiTag (std::ostream &os, const Value &value, const ExifData *metadata)
Print function to translate Pentax "combi-values" to a description by looking up a reference table.
std::ostream & printCameraTemperature (std::ostream &os, const Value &value, const ExifData *)
Print the camera temperature.
std::ostream & printFocalLength35 (std::ostream &os, const Value &value, const ExifData *)
Print the 35mm focal length.
std::ostream & printPwColor (std::ostream &os, const Value &value, const ExifData *)
Print the PictureWizard Color tag value.
std::ostream & printValueMinus4 (std::ostream &os, const Value &value, const ExifData *)
Print the tag value minus 4.
DataBuf sonyTagDecipher (uint16_t tag, const byte *bytes, uint32_t size, TiffComponent *const object)
DataBuf sonyTagEncipher (uint16_t tag, const byte *bytes, uint32_t size, TiffComponent *const object)
const TagInfo * ifdTagList ()
Return read-only list of built-in IFD0/1 tags.
const TagInfo * exifTagList ()
Return read-only list of built-in Exif IFD tags.
const TagInfo * gpsTagList ()
Return read-only list of built-in GPS tags.
const TagInfo * mpfTagList ()
Return read-only list of built-in mfp Tags http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/MPF.html.
const TagInfo * iopTagList ()
Return read-only list of built-in IOP tags.
const TagInfo * mnTagList ()
Return read-only list of built-in Exiv2 Makernote info tags.
bool isMakerIfd (IfdId ifdId)
Return true if ifdId is a makernote IFD id. (Note: returns false for makerIfd)
bool isExifIfd (IfdId ifdId)
Return true if ifdId is an Exif IFD id.
void taglist (std::ostream &os, IfdId ifdId)
Print the list of tags for ifdId to the output stream os.
const TagInfo * tagList (IfdId ifdId)
Return the tag list for ifdId.
const TagInfo * tagInfo (uint16_t tag, IfdId ifdId)
Return the tag info for tag and ifdId.
const TagInfo * tagInfo (const std::string &tagName, IfdId ifdId)
Return the tag info for tagName and ifdId.
IfdId groupId (const std::string &groupName)
Return the group id for a group name.
const char * ifdName (IfdId ifdId)
Return the name of the IFD.
const char * groupName (IfdId ifdId)
Return the group name for a group id.
uint16_t tagNumber (const std::string &tagName, IfdId ifdId)
Return the tag number for one combination of IFD id and tagName. If the tagName is not known, it expects tag names in the form "0x01ff" and converts them to unsigned integer.
const GroupInfo * groupList ()
const TagInfo * tagList (const std::string &groupName)
template<int N, const TagDetails(&) array>
std::ostream & printTag (std::ostream &os, const Value &value, const ExifData *)
Generic pretty-print function to translate a long value to a description by looking up a reference table.
template<int N, const TagDetailsBitmask(&) array>
std::ostream & printTagBitmask (std::ostream &os, const Value &value, const ExifData *)
Generic print function to translate a long value to a description by looking up bitmasks in a reference table.
template<int N, const TagVocabulary(&) array>
std::ostream & printTagVocabulary (std::ostream &os, const Value &value, const ExifData *)
Generic pretty-print function to translate a controlled vocabulary value (string) to a description by looking up a reference table.
TypeId toTypeId (TiffType tiffType, uint16_t tag, IfdId group)
Convert the tiffType of a tag and group to an Exiv2 typeId.
TiffType toTiffType (TypeId typeId)
Convert the Exiv2 typeId to a TIFF value type.
bool cmpTagLt (TiffComponent const *lhs, TiffComponent const *rhs)
Compare two TIFF component pointers by tag. Return true if the tag of component lhs is less than that of rhs.
bool cmpGroupLt (TiffComponent const *lhs, TiffComponent const *rhs)
Compare two TIFF component pointers by group. Return true if the group of component lhs is less than that of rhs.
TiffComponent::AutoPtr newTiffEntry (uint16_t tag, IfdId group)
Function to create and initialize a new TIFF entry.
TiffComponent::AutoPtr newTiffMnEntry (uint16_t tag, IfdId group)
Function to create and initialize a new TIFF makernote entry.
TiffComponent::AutoPtr newTiffBinaryElement (uint16_t tag, IfdId group)
Function to create and initialize a new binary array element.
template<IfdId newGroup>
TiffComponent::AutoPtr newTiffDirectory (uint16_t tag, IfdId)
Function to create and initialize a new TIFF directory.
template<IfdId newGroup>
TiffComponent::AutoPtr newTiffSubIfd (uint16_t tag, IfdId group)
Function to create and initialize a new TIFF sub-directory.
template<const ArrayCfg * arrayCfg, int N, const ArrayDef(&) arrayDef>
TiffComponent::AutoPtr newTiffBinaryArray0 (uint16_t tag, IfdId group)
Function to create and initialize a new binary array entry.
template<const ArrayCfg * arrayCfg>
TiffComponent::AutoPtr newTiffBinaryArray1 (uint16_t tag, IfdId group)
Function to create and initialize a new simple binary array entry.
template<const ArraySet * arraySet, int N, CfgSelFct cfgSelFct>
TiffComponent::AutoPtr newTiffBinaryArray2 (uint16_t tag, IfdId group)
Function to create and initialize a new complex binary array entry.
template<uint16_t szTag, IfdId szGroup>
TiffComponent::AutoPtr newTiffThumbData (uint16_t tag, IfdId group)
Function to create and initialize a new TIFF entry for a thumbnail (data)
template<uint16_t dtTag, IfdId dtGroup>
TiffComponent::AutoPtr newTiffThumbSize (uint16_t tag, IfdId group)
Function to create and initialize a new TIFF entry for a thumbnail (size)
template<uint16_t szTag, IfdId szGroup>
TiffComponent::AutoPtr newTiffImageData (uint16_t tag, IfdId group)
Function to create and initialize a new TIFF entry for image data.
template<uint16_t dtTag, IfdId dtGroup>
TiffComponent::AutoPtr newTiffImageSize (uint16_t tag, IfdId group)
Function to create and initialize a new TIFF entry for image data (size)
bool isTiffImageTag (uint16_t tag, IfdId group)
Convenience function to check if tag, group is in the list of TIFF image tags.
Functions printing interpreted tag values
std::ostream & printValue (std::ostream &os, const Value &value, const ExifData *)
Default print function, using the Value output operator.
std::ostream & printBitmask (std::ostream &os, const Value &value, const ExifData *)
Print a bitmask as (none) | n | n,m... where: (none) = no bits set | n = bit n from left (0=left-most) | n,m.. = multiple bits ".
float fnumber (float apertureValue)
Calculate F number from an APEX aperture value.
URational exposureTime (float shutterSpeedValue)
Calculate the exposure time from an APEX shutter speed value.
std::ostream & printLong (std::ostream &os, const Value &value, const ExifData *)
Print the value converted to a long.
std::ostream & printFloat (std::ostream &os, const Value &value, const ExifData *)
Print a Rational or URational value in floating point format.
std::ostream & printDegrees (std::ostream &os, const Value &value, const ExifData *)
Print a longitude or latitude value.
std::ostream & printUcs2 (std::ostream &os, const Value &value, const ExifData *)
Print function converting from UCS-2LE to UTF-8.
std::ostream & printExifUnit (std::ostream &os, const Value &value, const ExifData *)
Print function for Exif units.
std::ostream & print0x0000 (std::ostream &os, const Value &value, const ExifData *)
Print GPS version.
std::ostream & print0x0005 (std::ostream &os, const Value &value, const ExifData *)
Print GPS altitude ref.
std::ostream & print0x0006 (std::ostream &os, const Value &value, const ExifData *)
Print GPS altitude.
std::ostream & print0x0007 (std::ostream &os, const Value &value, const ExifData *)
Print GPS timestamp.
std::ostream & print0x0009 (std::ostream &os, const Value &value, const ExifData *)
Print GPS status.
std::ostream & print0x000a (std::ostream &os, const Value &value, const ExifData *)
Print GPS measurement mode.
std::ostream & print0x000c (std::ostream &os, const Value &value, const ExifData *)
Print GPS speed ref.
std::ostream & print0x0019 (std::ostream &os, const Value &value, const ExifData *)
Print GPS destination distance ref.
std::ostream & print0x001e (std::ostream &os, const Value &value, const ExifData *)
Print GPS differential correction.
std::ostream & print0x0112 (std::ostream &os, const Value &value, const ExifData *)
Print orientation.
std::ostream & print0x0213 (std::ostream &os, const Value &value, const ExifData *)
Print YCbCrPositioning.
std::ostream & print0x8298 (std::ostream &os, const Value &value, const ExifData *)
Print the copyright.
std::ostream & print0x829a (std::ostream &os, const Value &value, const ExifData *)
Print the exposure time.
std::ostream & print0x829d (std::ostream &os, const Value &value, const ExifData *)
Print the f-number.
std::ostream & print0x8822 (std::ostream &os, const Value &value, const ExifData *)
Print exposure program.
std::ostream & print0x8827 (std::ostream &os, const Value &value, const ExifData *)
Print ISO speed ratings.
std::ostream & print0x9101 (std::ostream &os, const Value &value, const ExifData *)
Print components configuration specific to compressed data.
std::ostream & print0x9201 (std::ostream &os, const Value &value, const ExifData *)
Print exposure time converted from APEX shutter speed value.
std::ostream & print0x9202 (std::ostream &os, const Value &value, const ExifData *)
Print f-number converted from APEX aperture value.
std::ostream & print0x9204 (std::ostream &os, const Value &value, const ExifData *)
Print the exposure bias value.
std::ostream & print0x9206 (std::ostream &os, const Value &value, const ExifData *)
Print the subject distance.
std::ostream & print0x9207 (std::ostream &os, const Value &value, const ExifData *)
Print metering mode.
std::ostream & print0x9208 (std::ostream &os, const Value &value, const ExifData *)
Print light source.
std::ostream & print0x920a (std::ostream &os, const Value &value, const ExifData *)
Print the actual focal length of the lens.
std::ostream & print0xa001 (std::ostream &os, const Value &value, const ExifData *)
Print color space.
std::ostream & print0xa217 (std::ostream &os, const Value &value, const ExifData *)
Print sensing method.
std::ostream & print0xa300 (std::ostream &os, const Value &value, const ExifData *)
Print file source.
std::ostream & print0xa301 (std::ostream &os, const Value &value, const ExifData *)
Print scene type.
std::ostream & print0xa401 (std::ostream &os, const Value &value, const ExifData *)
Print custom rendered.
std::ostream & print0xa402 (std::ostream &os, const Value &value, const ExifData *)
Print exposure mode.
std::ostream & print0xa403 (std::ostream &os, const Value &value, const ExifData *)
Print white balance.
std::ostream & print0xa404 (std::ostream &os, const Value &value, const ExifData *)
Print digital zoom ratio.
std::ostream & print0xa405 (std::ostream &os, const Value &value, const ExifData *)
Print 35mm equivalent focal length.
std::ostream & print0xa406 (std::ostream &os, const Value &value, const ExifData *)
Print scene capture type.
std::ostream & print0xa407 (std::ostream &os, const Value &value, const ExifData *)
Print gain control.
std::ostream & print0xa409 (std::ostream &os, const Value &value, const ExifData *)
Print saturation.
std::ostream & print0xa40c (std::ostream &os, const Value &value, const ExifData *)
Print subject distance range.
std::ostream & printGPSDirRef (std::ostream &os, const Value &value, const ExifData *)
Print GPS direction ref.
std::ostream & printNormalSoftHard (std::ostream &os, const Value &value, const ExifData *)
Print contrast, sharpness (normal, soft, hard)
std::ostream & printExifVersion (std::ostream &os, const Value &value, const ExifData *)
Print any version packed in 4 Bytes format : major major minor minor.
std::ostream & printXmpVersion (std::ostream &os, const Value &value, const ExifData *)
Print any version encoded in the ASCII string majormajorminorminor.
std::ostream & printXmpDate (std::ostream &os, const Value &value, const ExifData *)
Print a date following the format YYYY-MM-DDTHH:MM:SSZ.
Variables
const TagDetails canonOffOn []
OffOn, multiple tags.
const TagDetails canonModelId []
ModelId, tag 0x0010.
const TagDetails canonSerialNumberFormat []
SerialNumberFormat, tag 0x0015.
const TagDetails canonSuperMacro []
SuperMacro, tag 0x001a.
const TagDetails canonDateStampMode []
const TagDetails canonCategories []
const TagDetails canonPictureStyle []
PictureStyle Values.
const TagDetails canonSiWhiteBalance []
WhiteBalance, multiple tags.
const TagDetails canonColorSpace []
ColorSpace, tag 0x00b4.
const TagDetails canonAFAreaMode []
Canon AF Area Mode, tag 0x2601.
const TagDetails canonMyColors []
const TagDetails canonContrastInfo []
const TagDetails canonAspectInfo []
const TagDetails canonModifiedToneCurve []
const TagDetails canonModifiedSharpnessFreq []
const TagDetails canonPreviewQuality []
const TagDetails canonAFMicroAdjMode []
const TagDetails canonAutoLightingOptimizer []
const TagDetails canonLongExposureNoiseReduction []
const TagDetails canonHighISONoiseReduction []
const TagDetails canonAmbienceSelection []
const TagDetails canonMultiExposure []
const TagDetails canonMultiExposureControl []
const TagDetails canonFilterInfo []
const TagDetails canonMiniatureFilterOrientation []
const TagDetails canonHdr []
const TagDetails canonHdrEffect []
const TagDetails canonAIServoFirstImage []
const TagDetails canonAIServoSecondImage []
const TagDetails canonUSMLensElectronicMF []
const TagDetails canonAFAssistBeam []
const TagDetails canonOneShotAFRelease []
const TagDetails canonAutoAFPointSelEOSiTRAF []
const TagDetails canonLensDriveWhenAFImpossible []
const TagDetails canonSelectAFAreaSelectionMode []
const TagDetails canonAFAreaSelectionMethod []
const TagDetails canonOrientationLinkedAF []
const TagDetails canonManualAFPointSelPattern []
const TagDetails canonAFPointDisplayDuringFocus []
const TagDetails canonAVFDisplayIllumination []
const TagDetails canonAFStatusViewfinder []
const TagDetails canonInitialAFPointInServo []
const TagDetails canonCsMacro []
Macro, tag 0x0001.
const TagDetails canonCsQuality []
Quality, tag 0x0003.
const TagDetails canonCsFlashMode []
FlashMode, tag 0x0004.
const TagDetails canonCsDriveMode []
DriveMode, tag 0x0005.
const TagDetails canonCsFocusMode []
FocusMode, tag 0x0007.
const TagDetails canonCsRecordMode []
RecordMode, tag 0x0009.
const TagDetails canonCsImageSize []
ImageSize, tag 0x000a.
const TagDetails canonCsEasyMode []
EasyMode, tag 0x000b.
const TagDetails canonCsDigitalZoom []
DigitalZoom, tag 0x000c.
const TagDetails canonCsLnh []
Contrast, Saturation Sharpness, tags 0x000d, 0x000e, 0x000f.
const TagDetails canonCsISOSpeed []
ISOSpeeds, tag 0x0010.
const TagDetails canonCsMeteringMode []
MeteringMode, tag 0x0011.
const TagDetails canonCsFocusType []
FocusType, tag 0x0012.
const TagDetails canonCsAfPoint []
AFPoint, tag 0x0013.
const TagDetails canonCsExposureProgram []
ExposureProgram, tag 0x0014.
const TagDetails canonCsLensType []
LensType, tag 0x0016.
const LensIdFct lensIdFct []
List of lens ids which require special treatment with the medicine.
const TagDetails canonCsFlashActivity []
FlashActivity, tag 0x001c.
const TagDetailsBitmask canonCsFlashDetails []
FlashDetails, tag 0x001d.
const TagDetails canonCsFocusContinuous []
FocusContinuous, tag 0x0020.
const TagDetails canonCsAESetting []
AESetting, tag 0x0021.
const TagDetails canonCsImageStabilization []
ImageStabilization, tag 0x0022.
const TagDetails canonCsSpotMeteringMode []
SpotMeteringMode, tag 0x0027.
const TagDetails canonCsPhotoEffect []
PhotoEffect, tag 0x0028.
const TagDetails canonCsManualFlashOutput []
ManualFlashOutput, tag 0x0029.
const TagDetails canonCsSRAWQuality []
SRAWQuality, tag 0x002e.
const TagDetailsBitmask canonSiAFPointUsed []
AFPointUsed, tag 0x000e.
const TagDetails canonSiFlashBias []
FlashBias, tag 0x000f.
const TagDetails cameraType []
const TagDetails autoExposureBracketing []
const TagDetails slowShutter []
const TagDetails canonPaDirection []
PanoramaDirection, tag 0x0005.
const TagDetailsBitmask canonPiAFPointsUsed []
AFPointsUsed, tag 0x0016.
const TagDetailsBitmask canonPiAFPointsUsed20D []
AFPointsUsed20D, tag 0x001a.
const TagDetails canonBracketMode []
BracketMode, tag 0x0003.
const TagDetails canonRawJpgSize []
RawJpgSize, tag 0x0007.
const TagDetails canonNoiseReduction []
NoiseReduction, tag 0x0008.
const TagDetails canonWBBracketMode []
WBBracketMode, tag 0x0009.
const TagDetails canonFilterEffect []
FilterEffect, tag 0x000e.
const TagDetails canonToningEffect []
ToningEffect, tag 0x000e.
const TagDetails canonRFLensType []
RFLensType, tag 0x003D.
const TagDetails canonToneCurve []
Tone Curve Values.
const TagDetails canonSharpnessFrequency []
Sharpness Frequency Values.
const TagDetails canonTimeZoneCity []
canonTimeZoneCity - array of cityID/cityName used by Canon
const TagDetails casioRecordingMode []
RecordingMode, tag 0x0001.
const TagDetails casioQuality []
Quality, tag 0x0002.
const TagDetails casioFocusMode []
Focus Mode, tag 0x0003.
const TagDetails casioFlashMode []
FlashMode, tag 0x0004.
const TagDetails casioFlashIntensity []
Flash intensity, tag 0x0005.
const TagDetails casioWhiteBalance []
white balance, tag 0x0007
const TagDetails casioDigitalZoom []
Flash intensity, tag 0x0005.
const TagDetails casioSharpness []
Sharpness, tag 0x000b.
const TagDetails casioContrast []
Contrast, tag 0x000c.
const TagDetails casioSaturation []
Saturation, tag 0x000d.
const TagDetails casioEnhancement []
Enhancement, tag 0x0016.
const TagDetails casioColorFilter []
Color filter, tag 0x0017.
const TagDetails casioFlashIntensity2 []
flash intensity 2, tag 0x0019
const TagDetails casioCCDSensitivity []
CCD Sensitivity intensity, tag 0x0020.
const TagDetails casio2QualityMode []
Quality Mode, tag 0x0004.
const TagDetails casio2ImageSize []
Image Size, tag 0x0009.
const TagDetails casio2FocusMode []
Focus Mode, tag 0x000d.
const TagDetails casio2IsoSpeed []
ISO Speed, tag 0x0014.
const TagDetails casio2WhiteBalance []
White Balance, tag 0x0019.
const TagDetails casio2Saturation []
Saturation, tag 0x001f.
const TagDetails casio2Contrast []
Contrast, tag 0x0020.
const TagDetails casio2Sharpness []
Sharpness, tag 0x0021.
const TagDetails casio2WhiteBalance2 []
White Balance2, tag 0x2012.
const TagDetails casio2ReleaseMode []
Release Mode, tag 0x3001.
const TagDetails casio2Quality []
Quality, tag 0x3002.
const TagDetails casio2FocusMode2 []
Focus Mode 2, tag 0x3003.
const TagDetails casio2AutoISO []
AutoISO, tag 0x3008.
const TagDetails casio2AFMode []
AFMode, tag 0x3009.
const TagDetails casio2ColorMode []
ColorMode, tag 0x3015.
const TagDetails casio2Enhancement []
Enhancement, tag 0x3016.
const TagDetails casio2ColorFilter []
Color Filter, tag 0x3017.
const TagDetails casio2ArtMode []
Art Mode, tag 0x301b.
const TagDetails casio2LightingMode []
Lighting Mode, tag 0x302a.
const TagDetails casio2PortraitRefiner []
Portrait Refiner, tag 0x302b.
const TagDetails casio2SpecialEffectSetting []
Special Effect Setting, tag 0x3031.
const TagDetails casio2DriveMode []
Drive Mode, tag 0x3103.
const TagDetails casio2VideoQuality []
Video Quality, tag 0x4003.
const TagDetails fujiOffOn []
OffOn, multiple tags.
const TagDetails fujiSharpness []
Sharpness, tag 0x1001.
const TagDetails fujiWhiteBalance []
WhiteBalance, tag 0x1002.
const TagDetails fujiColor []
Color, tag 0x1003.
const TagDetails fujiTone []
Tone, tag 0x1004.
const TagDetails fujiFlashMode []
FlashMode, tag 0x1010.
const TagDetails fujiFocusMode []
FocusMode, tag 0x1021.
const TagDetails fujiPictureMode []
PictureMode, tag 0x1031.
const TagDetails fujiSHTone []
ShadowTone, tag 0x1040 HighlightTone, tag 0x041.
const TagDetails fujiContinuous []
Continuous, tag 0x1100.
const TagDetails fujiFinePixColor []
FinePixColor, tag 0x1210.
const TagDetails fujiDynamicRange []
DynamicRange, tag 0x1400.
const TagDetails fujiFilmMode []
FilmMode, tag 0x1401.
const TagDetails fujiDynamicRangeSetting []
DynamicRange, tag 0x1402.
const TagDetails fujiCropMode []
CropMode, tag 0x104d.
const TagDetails fujiDRangePriority []
DRangePriority, tag 0x1443.
const TagDetails fujiDRangePriorityAuto []
DRangePriorityAuto, tag 0x1444.
const TagDetails fujiDRangePriorityFixed []
DRangePriorityFixed, tag 0x1445.
const NikonArrayIdx nikonArrayIdx []
Nikon binary array version lookup table.
const TagDetails minoltaColorMode []
Lookup table to translate Minolta color mode values to readable labels.
const TagDetails minoltaImageQuality []
Lookup table to translate Minolta image quality values to readable labels.
const TagDetails minoltaImageStabilization []
Lookup table to translate Minolta image stabilization values.
const TagDetails minoltaExposureModeStd []
Lookup table to translate Minolta Std camera settings exposure mode values to readable labels.
const TagDetails minoltaFlashModeStd []
Lookup table to translate Minolta Std camera settings flash mode values to readable labels.
const TagDetails minoltaWhiteBalanceStd []
Lookup table to translate Minolta Std camera settings white balance values to readable labels.
const TagDetails minoltaImageSizeStd []
Lookup table to translate Minolta Std camera settings image size values to readable labels.
const TagDetails minoltaImageQualityStd []
Lookup table to translate Minolta Std camera settings image quality values to readable labels.
const TagDetails minoltaDriveModeStd []
Lookup table to translate Minolta Std camera settings drive mode values to readable labels.
const TagDetails minoltaMeteringModeStd []
Lookup table to translate Minolta Std camera settings metering mode values to readable labels.
const TagDetails minoltaDigitalZoomStd []
Lookup table to translate Minolta Std camera settings digital zoom values to readable labels.
const TagDetails minoltaBracketStepStd []
Lookup table to translate Minolta Std camera bracket step mode values to readable labels.
const TagDetails minoltaAFPointsStd []
Lookup table to translate Minolta Std camera settings AF points values to readable labels.
const TagDetails minoltaFlashFired []
Lookup table to translate Minolta Std camera settings flash fired values to readable labels.
const TagDetails minoltaSharpnessStd []
Lookup table to translate Minolta Std camera settings sharpness values to readable labels.
const TagDetails minoltaSubjectProgramStd []
Lookup table to translate Minolta Std camera settings subject program values to readable labels.
const TagDetails minoltaISOSettingStd []
Lookup table to translate Minolta Std camera settings ISO settings values to readable labels.
const TagDetails minoltaModelStd []
Lookup table to translate Minolta Std camera settings model values to readable labels.
const TagDetails minoltaIntervalModeStd []
Lookup table to translate Minolta Std camera settings interval mode values to readable labels.
const TagDetails minoltaFolderNameStd []
Lookup table to translate Minolta Std camera settings folder name values to readable labels.
const TagDetails minoltaColorModeStd []
Lookup table to translate Minolta Std camera settings color mode values to readable labels.
const TagDetails minoltaWideFocusZoneStd []
Lookup table to translate Minolta Std camera settings wide focus zone values to readable labels.
const TagDetails minoltaFocusModeStd []
Lookup table to translate Minolta Std camera settings focus mode values to readable labels.
const TagDetails minoltaFocusAreaStd []
Lookup table to translate Minolta Std camera settings focus area values to readable labels.
const TagDetails minoltaDECPositionStd []
Lookup table to translate Minolta Std camera settings DEC switch position values to readable labels.
const TagDetails minoltaColorProfileStd []
Lookup table to translate Minolta Std camera settings color profile values to readable labels.
const TagDetails minoltaDataImprintStd []
Lookup table to translate Minolta Std camera settings data Imprint values to readable labels.
const TagDetails minoltaFlashMeteringStd []
Lookup table to translate Minolta Std camera settings flash metering values to readable labels.
const TagDetails minoltaExposureMode7D []
Lookup table to translate Minolta Dynax 7D camera settings exposure mode values to readable labels.
const TagDetails minoltaImageSize7D []
Lookup table to translate Minolta Dynax 7D camera settings image size values to readable labels.
const TagDetails minoltaImageQuality7D []
Lookup table to translate Minolta Dynax 7D camera settings image quality values to readable labels.
const TagDetails minoltaWhiteBalance7D []
Lookup table to translate Minolta Dynax 7D camera settings white balance values to readable labels.
const TagDetails minoltaFocusMode7D []
Lookup table to translate Minolta Dynax 7D camera settings focus mode values to readable labels.
const TagDetails minoltaAFPoints7D []
Lookup table to translate Minolta Dynax 7D camera settings AF points values to readable labels.
const TagDetails minoltaISOSetting7D []
Lookup table to translate Minolta Dynax 7D camera settings ISO settings values to readable labels.
const TagDetails minoltaColorSpace7D []
Lookup table to translate Minolta Dynax 7D camera settings color space values to readable labels.
const TagDetails minoltaRotation7D []
Lookup table to translate Minolta Dynax 7D camera settings rotation values to readable labels.
const TagDetails minoltaExposureMode5D []
Lookup table to translate Minolta Dynax 5D camera settings exposure mode values to readable labels.
const TagDetails minoltaImageSize5D []
Lookup table to translate Minolta Dynax 5D camera settings image size values to readable labels.
const TagDetails minoltaImageQuality5D []
Lookup table to translate Minolta Dynax 5D camera settings image quality values to readable labels.
const TagDetails minoltaWhiteBalance5D []
Lookup table to translate Minolta Dynax 5D camera settings white balance values to readable labels.
const TagDetails minoltaMeteringMode5D []
Lookup table to translate Minolta Dynax 5D camera settings metering mode values to readable labels.
const TagDetails minoltaISOSetting5D []
Lookup table to translate Minolta Dynax 5D camera settings ISO settings values to readable labels.
const TagDetails minoltaColorSpace5D []
Lookup table to translate Minolta Dynax 5D camera settings color space values to readable labels.
const TagDetails minoltaRotation5D []
Lookup table to translate Minolta Dynax 5D camera settings rotation values to readable labels.
const TagDetails minoltaFocusPosition5D []
Lookup table to translate Minolta Dynax 5D camera settings focus position values to readable labels.
const TagDetails minoltaFocusArea5D []
Lookup table to translate Minolta Dynax 5D camera settings focus area values to readable labels.
const TagDetails minoltaAFMode5D []
Lookup table to translate Minolta Dynax 5D camera settings focus mode values to readable labels.
const TagDetails minoltaPictureFinish5D []
Lookup table to translate Minolta Dynax 5D camera settings picture finish values to readable labels.
const TagDetails sonyDriveMode2A100 []
Lookup table to translate Sony A100 camera settings drive mode 2 values to readable labels.
const TagDetails sonyFocusModeA100 []
Lookup table to translate Sony A100 camera settings focus mode values to readable labels.
const TagDetails sonyFlashModeA100 []
Lookup table to translate Sony A100 camera settings flash mode values to readable labels.
const TagDetails sonyMeteringModeA100 []
Lookup table to translate Sony A100 camera settings metering mode values to readable labels.
const TagDetails sonyZoneMatchingModeA100 []
Lookup table to translate Sony A100 camera settings zone matching mode values to readable labels.
const TagDetails sonyColorSpaceA100 []
Lookup table to translate Sony A100 camera settings color space values to readable labels.
const TagDetails sonyDriveModeA100 []
Lookup table to translate Sony A100 camera settings drive mode values to readable labels.
const TagDetails sonySelfTimerTimeA100 []
Lookup table to translate Sony A100 camera settings self timer time values to readable labels.
const TagDetails sonyContinuousBracketingA100 []
Lookup table to translate Sony A100 camera settings continuous bracketing values to readable labels.
const TagDetails sonySingleFrameBracketingA100 []
Lookup table to translate Sony A100 camera settings single frame bracketing values to readable labels.
const TagDetails sonyWhiteBalanceBracketingA100 []
Lookup table to translate Sony A100 camera settings white balance bracketing values to readable labels.
const TagDetails sonyWhiteBalanceSettingA100 []
Lookup table to translate Sony A100 camera settings white balance setting values to readable labels.
const TagDetails sonyPresetWhiteBalanceA100 []
Lookup table to translate Sony A100 camera settings preset white balance values to readable labels.
const TagDetails sonyColorTemperatureSettingA100 []
Lookup table to translate Sony A100 camera settings color temperature setting values to readable labels.
const TagDetails sonyCustomWBSettingA100 []
Lookup table to translate Sony A100 camera settings custom WB setting values to readable labels.
const TagDetails sonyCustomWBErrorA100 []
Lookup table to translate Sony A100 camera settings custom WB error values to readable labels.
const TagDetails sonyImageSizeA100 []
Lookup table to translate Sony A100 camera settings image size values to readable labels.
const TagDetails sonyInstantPlaybackSetupA100 []
Lookup table to translate Sony A100 camera settings instant playback setup values to readable labels.
const TagDetails sonyFlashDefaultA100 []
Lookup table to translate Sony A100 camera settings flash default setup values to readable labels.
const TagDetails sonyAutoBracketOrderA100 []
Lookup table to translate Sony A100 camera settings auto bracket order values to readable labels.
const TagDetails sonyFocusHoldButtonA100 []
Lookup table to translate Sony A100 camera settings focus hold button values to readable labels.
const TagDetails sonyAELButtonA100 []
Lookup table to translate Sony A100 camera settings AEL button values to readable labels.
const TagDetails sonyControlDialSetA100 []
Lookup table to translate Sony A100 camera settings control dial set values to readable labels.
const TagDetails sonyExposureCompensationModeA100 []
Lookup table to translate Sony A100 camera settings exposure compensation mode values to readable labels.
const TagDetails sonyAFAreaIlluminationA100 []
Lookup table to translate Sony A100 camera settings sony AF area illumination values to readable labels.
const TagDetails sonyMonitorDisplayOffA100 []
Lookup table to translate Sony A100 camera settings monitor display off values to readable labels.
const TagDetails sonyRecordDisplayA100 []
Lookup table to translate Sony A100 camera settings record display values to readable labels.
const TagDetails sonyPlayDisplayA100 []
Lookup table to translate Sony A100 camera settings play display values to readable labels.
const TagDetails sonyMeteringOffScaleIndicatorA100 []
Lookup table to translate Sony A100 camera settings metering off scale indicator values to readable labels.
const TagDetails sonyExposureIndicatorA100 []
Lookup table to translate Sony A100 camera settings exposure indicator values to readable labels.
const TagDetails sonyFocusModeSwitchA100 []
Lookup table to translate Sony A100 camera settings focus mode switch values to readable labels.
const TagDetails sonyFlashTypeA100 []
Lookup table to translate Sony A100 camera settings flash type switch values to readable labels.
const TagDetails sonyBatteryLevelA100 []
Lookup table to translate Sony A100 camera settings battery level switch values to readable labels.
TagDetails const minoltaSonyLensID []
Lookup table to translate Minolta/Sony Lens id values to readable labels.
const TagDetails minoltaSonyColorMode []
Lookup table to translate Minolta A100 and all other Sony Alpha camera color mode values to readable labels.
const TagDetails minoltaSonyBoolFunction []
Lookup table to translate Minolta/Sony bool function values to readable labels.
const TagDetails minoltaSonyBoolInverseFunction []
Lookup table to translate Minolta/Sony bool inverse function values to readable labels.
const TagDetails minoltaSonyAFAreaMode []
Lookup table to translate Sony camera settings focus mode values to readable labels.
const TagDetails minoltaSonyLocalAFAreaPoint []
Lookup table to translate Sony camera settings Local AF Area Point values to readable labels.
const TagDetails minoltaSonyDynamicRangeOptimizerMode []
Lookup table to translate Sony camera settings dynamic range optimizer mode values to readable labels.
const TagDetails minoltaSonyPrioritySetupShutterRelease []
Lookup table to translate Sony camera settings priority setup shutter release values to readable labels.
const TagDetails minoltaSonyQualityCs []
Lookup table to translate Sony camera settings quality values to readable labels.
const TagDetails minoltaSonyRotation []
Lookup table to translate Sony camera settings rotation values to readable labels.
const TagDetails minoltaSonySceneMode []
Lookup table to translate Minolta/Sony scene mode values to readable labels.
const TagDetails minoltaSonyImageQuality []
Lookup table to translate Sony/Minolta image quality values to readable labels.
const TagDetails minoltaSonyTeleconverterModel []
Lookup table to translate Sony/Minolta teleconverter model values to readable labels.
const TagDetails minoltaSonyWhiteBalanceStd []
Lookup table to translate Sony/Minolta Std camera settings white balance values to readable labels.
const TagDetails minoltaSonyZoneMatching []
Lookup table to translate Sony/Minolta zone matching values to readable labels.
const TagDetails nikonOffOn []
OffOn, multiple tags.
const TagDetails nikonOlnh []
Off, Low, Normal, High, multiple tags.
const TagDetails nikonActiveDLighning []
Off, Low, Normal, High, multiple tags.
const char *const nikonFocusarea []
Focus area for Nikon cameras.
const char *const nikonFocuspoints []
Focus points for Nikon cameras, used for Nikon 1 and Nikon 3 makernotes.
const TagDetails nikonShutterModes []
Shutter Modes (credits to exiftool)
const TagDetails nikonFlashComp []
FlashComp, tag 0x0012.
const TagDetails nikonColorSpace []
ColorSpace, tag 0x001e.
const TagDetails nikonFlashMode []
FlashMode, tag 0x0087.
const TagDetailsBitmask nikonShootingMode []
ShootingMode, tag 0x0089.
const TagDetailsBitmask nikonShootingModeD70 []
ShootingMode D70, tag 0x0089.
const TagDetails nikonAutoBracketRelease []
AutoBracketRelease, tag 0x008a.
const TagDetails nikonNefCompression []
NEFCompression, tag 0x0093.
const TagDetails nikonRetouchHistory []
RetouchHistory, tag 0x009e.
const TagDetails nikonHighISONoiseReduction []
HighISONoiseReduction, tag 0x00b1.
const TagDetails nikon2Quality []
Quality, tag 0x0003.
const TagDetails nikon2ColorMode []
ColorMode, tag 0x0004.
const TagDetails nikon2ImageAdjustment []
ImageAdjustment, tag 0x0005.
const TagDetails nikon2IsoSpeed []
ISOSpeed, tag 0x0006.
const TagDetails nikon2WhiteBalance []
WhiteBalance, tag 0x0007.
const TagDetails nikonYesNo []
YesNo, used for DaylightSavings, tag index 2.
const TagDetails nikonDateDisplayFormat []
DateDisplayFormat, tag index 3.
const TagDetails nikonOnOff []
OnOff.
const TagDetails nikonAdjust []
Adjust.
const TagDetails nikonFilterEffect []
FilterEffect.
const TagDetails nikonToningEffect []
ToningEffect.
const TagDetails aftOnOff []
OnOff.
const TagDetails nikonIsoExpansion []
ISOExpansion, tag index 4 and 10.
const TagDetails nikonAfAreaMode []
AfAreaMode.
const TagDetails nikonAfPoint []
AfPoint.
const TagDetailsBitmask nikonAfPointsInFocus []
AfPointsInFocus.
const TagDetails nikonPhaseDetectAF []
PhaseDetectAF.
const TagDetails nikonMultiExposureMode []
MultiExposureMode.
const TagDetails nikonFlashSource []
FlashSource.
const TagDetails nikonFlashFirmware []
FlashFirmware.
const TagDetails nikonFlashGNDistance []
FlashGNDistance.
const TagDetails nikonFlashControlMode []
FlashControlMode.
const TagDetails nikonExternalFlashFlags []
ExternalFlashFlags.
const TagDetails nikonFlashColorFilter []
FlashColorFilter.
const TagDetails nikonAfFineTuneAdj1 []
AfFineTuneAdj D300 (a)
const TagDetails nikonAfFineTuneAdj2 []
AfFineTuneAdj D300 (b)
const TagDetails nikonOffOn2 []
VibrationReduction.
const TagDetails nikonOffOn3 []
VibrationReduction2.
const TagDetails olympusOffOn []
OffOn, multiple tags.
const TagDetails olympusNoYes []
NoYes, multiple tags.
const TagDetails olympusQuality []
Quality, tag 0x0201.
const TagDetails olympusMacro []
Macro, tag 0x0202.
const TagDetails olympusOneTouchWb []
OneTouchWB, tag 0x0302.
const TagDetails olympusSceneMode []
SceneMode, tag 0x403 and CameraSettings tag 0x509.
const TagDetails olympusFlashDevice []
FlashDevice, tag 0x1005.
const TagDetails olympusFocusRange []
FocusRange, tag 0x100a.
const TagDetails olympusFocusMode []
FocusMode, tag 0x100b.
const TagDetails olympusSharpness []
Sharpness, tag 0x100f.
const TagDetails olympusContrast []
Contrast, tag 0x1029.
const TagDetails olympusCCDScanMode []
CCDScanMode, tag 0x1039.
const TagDetails olympusExposureMode []
ExposureMode, tag 0x0200.
const TagDetails olympusMeteringMode []
MeteringMode, tag 0x0202.
const TagDetails olympusMacroMode []
MacroMode, tag 0x0300.
const TagDetails olympusCsFocusMode []
FocusMode, tag 0x0301.
const TagDetails olympusFocusProcess []
FocusProcess, tag 0x0302.
const TagDetails olympusAFSearch []
AFSearch, tag 0x0303.
const TagDetailsBitmask olympusFlashMode []
FlashMode, tag 0x0400.
const TagDetails olympusFlashRemoteControl []
FlashRemoteControl, tag 0x0403.
const TagDetails olympusFlashControlMode []
FlashControlMode, tag 0x0404.
const TagDetails olympusWhiteBalance []
WhiteBalance, tag 0x0500.
const TagDetails olympusModifiedSaturation []
ModifiedSaturation, tag 0x0504.
const TagDetails olympusColorSpace []
ColorSpace, tag 0x0507.
const TagDetailsBitmask olympusNoiseReduction []
NoiseReduction, tag 0x050a.
const TagDetails olympusPictureMode []
PictureMode, tag 0x0520.
const TagDetails olympusPictureModeBWFilter []
PictureModeBWFilter, tag 0x0525.
const TagDetails olympusPictureModeTone []
PictureModeTone, tag 0x0526.
const TagDetails olympusCsQuality []
OlympusCs Quality, tag 0x0603.
const TagDetails olympusImageStabilization []
Olympus ImageStabilization, tag 0x0604.
const TagDetails olympusEqFlashType []
OlympusEq FlashType, tag 0x1000.
const TagDetails olympusEqFlashModel []
OlympusEq FlashModel, tag 0x1001.
const TagDetails olympusRdColorSpace []
OlympusRd ColorSpace, tag 0x0108.
const TagDetails olympusRdEngine []
OlympusRd Engine, tag 0x0109.
const TagDetails olympusRdEditStatus []
OlympusRd EditStatus, tag 0x010b.
const TagDetailsBitmask olympusRdSettings []
OlympusRd Settings, tag 0x010c.
const TagDetails olympusRd2WhiteBalance []
OlympusRd2 WhiteBalance, tag 0x0101.
const TagDetails olympusRd2ColorSpace []
OlympusRd2 ColorSpace, tag 0x0109.
const TagDetails olympusRd2Engine []
OlympusRd2 Engine, tag 0x010b.
const TagDetails olympusRd2PictureMode []
OlympusRd2 PictureMode, tag 0x010c.
const TagDetails olympusRd2PM_BWFilter []
OlympusRd2 PM_BWFilter, tag 0x0110.
const TagDetails olympusRd2PMPictureTone []
OlympusRd2 PMPictureTone, tag 0x0111.
const TagDetails olympusIpMultipleExposureMode []
OlympusIp MultipleExposureMode, tag 0x101c.
const TagDetails olympusIpAspectRatio []
OlympusIp olympusIpAspectRatio, tag 0x101c.
const TagDetails olympusFiExternalFlashBounce []
OlympusFi ExternalFlashBounce, tag 0x1204.
const TagDetails olympusRiLightSource []
OlympusRi LightSource, tag 0x1000.
const TagDetails panasonicQuality []
Quality, tag 0x0001.
const TagDetails panasonicWhiteBalance []
WhiteBalance, tag 0x0003.
const TagDetails panasonicFocusMode []
FocusMode, tag 0x0007.
const TagDetails panasonicImageStabilizer []
ImageStabilizer, tag 0x001a.
const TagDetails panasonicMacro []
Macro, tag 0x001c.
const TagDetails panasonicShootingMode []
ShootingMode, tag 0x001f and SceneMode, tag 0x8001.
const TagDetails panasonicAudio []
Audio, tag 0x0020.
const TagDetails panasonicColorEffect []
ColorEffect, tag 0x0028.
const TagDetails panasonicBurstMode []
BustMode, tag 0x002a.
const TagDetails panasonicContrast []
Contrast, tag 0x002c.
const TagDetails panasonicNoiseReduction []
NoiseReduction, tag 0x002d.
const TagDetails panasonicSelfTimer []
SelfTimer, tag 0x002e.
const TagDetails panasonicRotation []
Rotation, tag 0x0030.
const TagDetails panasonicAFAssistLamp []
AFAssistLamp, tag 0x0031.
const TagDetails panasonicColorMode []
ColorMode, tag 0x0032.
const TagDetails panasonicOpticalZoomMode []
OpticalZoomMode, tag 0x0034.
const TagDetails panasonicConversionLens []
ConversionLens, tag 0x0035.
const TagDetails panasonicWorldTimeLocation []
WorldTimeLocation, tag 0x003a.
const TagDetails panasonicTextStamp []
TextStamp, tag 0x003b, 0x003e, 000x8008 and 0x8009.
const TagDetails panasonicFilmMode []
FilmMode, tag 0x0042.
const TagDetails panasonicBracketSettings []
Bracket Settings, tag 0x0045.
const TagDetails panasonicFlashCurtain []
Flash curtain, tag 0x0048.
const TagDetails panasonicLongShutterNoiseReduction []
Long Shutter Noise Reduction, tag 0x0049.
const TagDetails panasonicIntelligentExposure []
Intelligent exposure, tag 0x005d.
const TagDetails panasonicFlashWarning []
Flash warning, tag 0x0062.
const TagDetails panasonicIntelligentResolution []
Intelligent resolution, tag 0x0070.
const TagDetails panasonicIntelligentDRange []
Intelligent D-Range, tag 0x0079.
const TagDetails panasonicClearRetouch []
Clear Retouch, tag 0x007c.
const TagDetails panasonicPhotoStyle []
Photo Style, tag 0x0089.
const TagDetails panasonicShadingCompensation []
Shading compensation, tag 0x008a.
const TagDetails panasonicCameraOrientation []
Camera orientation, tag 0x008f.
const TagDetails panasonicSweepPanoramaDirection []
Sweep panorama direction, tag 0x0093.
const TagDetails panasonicTimerRecording []
Timer recording, tag 0x0096.
const TagDetails panasonicHDR []
HDR, tag 0x009e.
const TagDetails panasonicShutterType []
Shutter Type, tag 0x009f.
const TagDetails panasonicTouchAE []
Touch AE, tag 0x00ab.
const TagDetails panasonicFlashFired []
Flash Fired, tag 0x8007.
const TagDetails pentaxShootingMode []
ShootingMode, tag 0x0001.
const TagDetails pentaxModel []
CameraModel, tag 0x0005.
const TagDetails pentaxQuality []
Quality, tag 0x0008.
const TagDetails pentaxSize []
Size, tag 0x0009.
const TagDetails pentaxFlash []
Flash, tag 0x000c.
const TagDetails pentaxFocus []
Focus, tag 0x000d.
const TagDetails pentaxAFPoint []
AFPoint, tag 0x000e.
const TagDetails pentaxAFPointFocus []
AFPointInFocus, tag 0x000f.
const TagDetails pentaxISO []
ISO, tag 0x0014.
const TagDetails pentaxOffOn []
Generic for Off/On switches.
const TagDetails pentaxYesNo []
Generic for Yes/No switches.
const TagDetails pentaxMeteringMode []
MeteringMode, tag 0x0017.
const TagDetails pentaxWhiteBalance []
WhiteBalance, tag 0x0019.
const TagDetails pentaxWhiteBalanceMode []
WhiteBalance, tag 0x001a.
const TagDetails pentaxSaturation []
Saturation, tag 0x001f.
const TagDetails pentaxContrast []
Contrast, tag 0x0020.
const TagDetails pentaxSharpness []
Sharpness, tag 0x0021.
const TagDetails pentaxLocation []
Location, tag 0x0022.
const TagDetails pentaxCities []
City names, tags 0x0023 and 0x0024.
const TagDetails pentaxImageProcessing []
ImageProcessing, combi-tag 0x0032 (4 bytes)
const TagDetails pentaxPictureMode []
PictureMode, combi-tag 0x0033 (3 bytes)
const TagDetails pentaxDriveMode []
DriveMode, combi-tag 0x0034 (4 bytes)
const TagDetails pentaxColorSpace []
ColorSpace, tag 0x0037.
const TagDetails pentaxLensType []
LensType, combi-tag 0x003f (2 unsigned long)
const TagDetails pentaxImageTone []
ImageTone, tag 0x004f.
const TagDetails pentaxDynamicRangeExpansion []
DynamicRangeExpansion, tag 0x0069.
const TagDetails pentaxHighISONoiseReduction []
HighISONoiseReduction, tag 0x0071.
const TagDetails samsung2LensType []
LensType, tag 0xa003.
const TagDetails samsung2ColorSpace []
ColorSpace, tag 0xa011.
const TagDetails samsung2SmartRange []
SmartRange, tag 0xa012.
const TagDetails samsungPwMode []
PictureWizard Mode.
const TagDetails sonyHDRMode []
Lookup table to translate Sony Auto HDR values to readable labels.
const TagDetails sonyModelId []
Lookup table to translate Sony model ID values to readable labels.
const TagDetails print0xb025 []
Lookup table to translate Sony dynamic range optimizer values to readable labels.
const TagDetails sonyExposureMode []
Lookup table to translate Sony exposure mode values to readable labels.
const TagDetails sonyJPEGQuality []
Lookup table to translate Sony JPEG Quality values to readable labels.
const TagDetails sonyAntiBlur []
Lookup table to translate Sony anti-blur values to readable labels.
const TagDetails print0xb04f []
Lookup table to translate Sony dynamic range optimizer values to readable labels.
const TagDetails sonyIntelligentAuto []
Lookup table to translate Sony Intelligent Auto values to readable labels.
const TagDetails sonyWhiteBalance []
Lookup table to translate Sony WB values to readable labels.
const TagDetails sonyFocusMode []
Lookup table to translate Sony AF mode values to readable labels.
const TagDetails sonyAFMode []
Lookup table to translate Sony AF mode values to readable labels.
const TagDetails sonyAFIlluminator []
Lookup table to translate Sony AF illuminator values to readable labels.
const TagDetails sonyMacroMode []
Lookup table to translate Sony macro mode values to readable labels.
const TagDetails sonyFlashLevel []
Lookup table to translate Sony flash level values to readable labels.
const TagDetails sonyReleaseMode []
Lookup table to translate Sony release mode values to readable labels.
const TagDetails sonySequenceNumber []
Lookup table to translate Sony sequence number values to readable labels.
const TagDetails sonyLongExposureNoiseReduction []
Lookup table to translate Sony long exposure noise reduction values to readable labels.
const TagDetails sonyDriveModeStd []
Lookup table to translate Sony camera settings drive mode values to readable labels.
const TagDetails sonyCSFocusMode []
Lookup table to translate Sony camera settings focus mode values to readable labels.
const TagDetails sonyMeteringMode []
Lookup table to translate Sony camera settings metering mode values to readable labels.
const TagDetails sonyCreativeStyle []
Lookup table to translate Sony camera settings creative style values to readable labels.
const TagDetails sonyFlashMode []
Lookup table to translate Sony camera settings flash mode values to readable labels.
const TagDetails sonyAFIlluminatorCS []
Lookup table to translate Sony AF illuminator values to readable labels.
const TagDetails sonyImageStyle []
Lookup table to translate Sony camera settings image style values to readable labels.
const TagDetails sonyExposureProgram []
Lookup table to translate Sony camera settings exposure program values to readable labels.
const TagDetails sonyImageSize []
Lookup table to translate Sony camera settings image size values to readable labels.
const TagDetails sonyAspectRatio []
Lookup table to translate Sony aspect ratio values to readable labels.
const TagDetails sonyExposureLevelIncrements []
Lookup table to translate Sony exposure level increments values to readable labels.
const GroupInfo groupInfo []
List of all known Exif groups. Important: Group name (3rd column) must be unique!
const TagDetails exifUnit []
Units for measuring X and Y resolution, tags 0x0128, 0xa210.
const TagDetails exifOrientation []
Orientation, tag 0x0112.
const TagDetails exifPlanarConfiguration []
PlanarConfiguration, tag 0x011c.
const TagDetails exifPredictor []
Predictor, tag 0x013d.
const TagDetails exifInkSet []
InkSet, tag 0x014c.
const TagDetails exifNewSubfileType []
NewSubfileType, TIFF tag 0x00fe - this is actually a bitmask.
const TagDetails exifSubfileType []
SubfileType, TIFF tag 0x00ff.
const TagDetails exifCompression []
Compression, tag 0x0103.
const TagDetails exifPhotometricInterpretation []
PhotometricInterpretation, tag 0x0106.
const TagDetails exifThresholding []
Thresholding, tag 0x0107.
const TagDetails exifSampleFormat []
SampleFormat, tag 0x0153.
const TagDetails exifIndexed []
Indexed, tag 0x015a.
const TagDetails exifJpegLosslessPredictor []
exifJpegLosslessPredictor, tag 0x0205
const TagDetails exifLightSource []
LightSource, tag 0x9208.
const TagDetails exifFlash []
Flash, Exif tag 0x9209.
const TagDetails tiffFocalPlaneResolutionUnit []
FocalPlaneResolutionUnit, TIFF/EP tag 0x9210.
const TagDetails tiffSensingMethod []
SensingMethod, TIFF/EP tag 0x9217.
const TagDetails dngCfaLayout []
CFALayout, DNG tag 0xc617.
const TagDetails dngMakerNoteSafety []
MakerNoteSafety, DNG tag 0xc635.
const TagDetails dngColorimetricReference []
ColorimetricReference, DNG 1.2 tag 0xc6bf.
const TagDetails dngProfileEmbedPolicy []
ProfileEmbedPolicy, DNG 1.2 tag 0xc6fd.
const TagDetails dngPreviewColorSpace []
PreviewColorSpace, DNG 1.2 tag 0xc71a.
const TagDetails dngProfileEncoding []
ProfileEncoding, DNG 1.4 tags 0xc7a3, 0xc7a4.
const TagDetails dngDefaultBlackRender []
DefaultBlackRender, DNG 1.4 tag 0xc7a6.
const TagDetails dngDepthFormat []
DepthFormat, DNG 1.5 tag 0xc7e9.
const TagDetails dngDepthUnits []
DepthUnits, DNG 1.5 tag 0xc7ec.
const TagDetails dngDepthMeasureType []
DepthMeasureType, DNG 1.5 tag 0xc7ed.
const TagDetails exifCompositeImage []
CompositeImage, tag 0xa460.
const TagDetails exifGPSLatitudeRef []
GPS latitude reference, tag 0x0001; also GPSDestLatitudeRef, tag 0x0013.
const TagDetails exifGPSLongitudeRef []
GPS longitude reference, tag 0x0003; also GPSDestLongitudeRef, tag 0x0015.
const TagDetails exifGPSAltitudeRef []
GPS altitude reference, tag 0x0005.
const TagDetails exifGPSStatus []
GPS status, tag 0x0009.
const TagDetails exifGPSMeasureMode []
GPS measurement mode, tag 0x000a.
const TagDetails exifGPSSpeedRef []
GPS speed reference, tag 0x000c.
const TagDetails exifGPSDirRef []
GPS direction ref, tags 0x000e, 0x0010, 0x0017.
const TagDetails exifGPSDestDistanceRef []
GPS Destination distance ref, tag 0x0019.
const TagDetails exifGPSDifferential []
GPS Differential, tag 0x001e.
const TagDetails exifYCbCrPositioning []
YCbCrPositioning, tag 0x0213.
const TagDetails exifExposureProgram []
ExposureProgram, tag 0x8822.
const TagDetails exifMeteringMode []
MeteringMode, tag 0x9207.
const TagDetails exifColorSpace []
ColorSpace, tag 0xa001.
const TagDetails exifSensingMethod []
SensingMethod, tag 0xa217.
const TagDetails exifFileSource []
FileSource, tag 0xa300.
const TagDetails exifSceneType []
SceneType, tag 0xa301.
const TagDetails exifCustomRendered []
CustomRendered, tag 0xa401.
const TagDetails exifExposureMode []
ExposureMode, tag 0xa402.
const TagDetails exifWhiteBalance []
WhiteBalance, tag 0xa403.
const TagDetails exifSceneCaptureType []
SceneCaptureType, tag 0xa406.
const TagDetails exifGainControl []
GainControl, tag 0xa407.
const TagDetails exifSaturation []
Saturation, tag 0xa409.
const TagDetails exifSubjectDistanceRange []
SubjectDistanceRange, tag 0xa40c.
const TagDetails exifNormalSoftHard []
Contrast, tag 0xa408 and Sharpness, tag 0xa40a.
const TiffType ttUnsignedByte = 1
Exif BYTE type.
const TiffType ttAsciiString = 2
Exif ASCII type.
const TiffType ttUnsignedShort = 3
Exif SHORT type.
const TiffType ttUnsignedLong = 4
Exif LONG type.
const TiffType ttUnsignedRational = 5
Exif RATIONAL type.
const TiffType ttSignedByte = 6
Exif SBYTE type.
const TiffType ttUndefined = 7
Exif UNDEFINED type.
const TiffType ttSignedShort = 8
Exif SSHORT type.
const TiffType ttSignedLong = 9
Exif SLONG type.
const TiffType ttSignedRational =10
Exif SRATIONAL type.
const TiffType ttTiffFloat =11
TIFF FLOAT type.
const TiffType ttTiffDouble =12
TIFF DOUBLE type.
const TiffType ttTiffIfd =13
TIFF IFD type.
const CryptFct notEncrypted = 0
Constant for non-encrypted binary arrays.
const ArrayCfg canonCsCfg
Canon Camera Settings binary array - configuration.
const ArrayDef canonCsDef []
Canon Camera Settings binary array - definition.
const ArrayCfg canonSiCfg
Canon Shot Info binary array - configuration.
const ArrayCfg canonPaCfg
Canon Panorama binary array - configuration.
const ArrayCfg canonCfCfg
Canon Custom Function binary array - configuration.
const ArrayCfg canonPiCfg
Canon Picture Info binary array - configuration.
const ArrayCfg canonTiCfg
Canon Time Info binary array - configuration.
const ArrayCfg canonFiCfg
Canon File Info binary array - configuration.
const ArrayDef canonFiDef []
Canon File Info binary array - definition.
const ArrayCfg canonPrCfg
Canon Processing Info binary array - configuration.
const ArrayCfg nikonVrCfg
Nikon Vibration Reduction binary array - configuration.
const ArrayDef nikonVrDef []
Nikon Vibration Reduction binary array - definition.
const ArrayCfg nikonPcCfg
Nikon Picture Control binary array - configuration.
const ArrayDef nikonPcDef []
Nikon Picture Control binary array - definition.
const ArrayCfg nikonWtCfg
Nikon World Time binary array - configuration.
const ArrayDef nikonWtDef []
Nikon World Time binary array - definition.
const ArrayCfg nikonIiCfg
Nikon ISO info binary array - configuration.
const ArrayDef nikonIiDef []
Nikon ISO info binary array - definition.
const ArrayCfg nikonAfCfg
Nikon Auto Focus binary array - configuration.
const ArrayDef nikonAfDef []
Nikon Auto Focus binary array - definition.
const ArrayCfg nikonAf21Cfg
Nikon Auto Focus 21 binary array - configuration.
const ArrayDef nikonAf21Def []
Nikon Auto Focus 21 binary array - definition.
const ArrayCfg nikonAf22Cfg
Nikon Auto Focus 22 binary array - configuration.
const ArrayDef nikonAf22Def []
Nikon Auto Focus 22 binary array - definition.
const ArraySet nikonAf2Set []
Nikon AF2 configuration and definitions.
const ArrayCfg nikonAFTCfg
Nikon AF Fine Tune binary array - configuration.
const ArrayDef nikonAFTDef []
Nikon AF Fine Tune binary array - definition.
const ArrayCfg nikonFiCfg
Nikon File Info binary array - configuration.
const ArrayDef nikonFiDef []
Nikon File Info binary array - definition.
const ArrayCfg nikonMeCfg
Nikon Multi Exposure binary array - configuration.
const ArrayDef nikonMeDef []
Nikon Multi Exposure binary array - definition.
const ArrayCfg nikonFl1Cfg
Nikon Flash Info binary array - configuration 1.
const ArrayDef nikonFl1Def []
Nikon Flash Info binary array - definition 1.
const ArrayCfg nikonFl2Cfg
Nikon Flash Info binary array - configuration 2.
const ArrayDef nikonFl2Def []
Nikon Flash Info binary array - definition 2.
const ArrayCfg nikonFl3Cfg
Nikon Flash Info binary array - configuration 3.
const ArrayDef nikonFl3Def []
Nikon Flash Info binary array - definition.
const ArraySet nikonFlSet []
Nikon Lens Data configurations and definitions.
const ArrayCfg nikonSi1Cfg
Nikon Shot Info binary array - configuration 1 (D80)
const ArrayDef nikonSi1Def []
Nikon Shot Info binary array - definition 1 (D80)
const ArrayCfg nikonSi2Cfg
Nikon Shot Info binary array - configuration 2 (D40)
const ArrayDef nikonSi2Def []
Nikon Shot Info binary array - definition 2 (D40)
const ArrayCfg nikonSi3Cfg
Nikon Shot Info binary array - configuration 3 (D300a)
const ArrayDef nikonSi3Def []
Nikon Shot Info binary array - definition 3 (D300a)
const ArrayCfg nikonSi4Cfg
Nikon Shot Info binary array - configuration 4 (D300b)
const ArrayDef nikonSi4Def []
Nikon Shot Info binary array - definition 4 (D300b)
const ArrayCfg nikonSi5Cfg
Nikon Shot Info binary array - configuration 5 (ver 02.xx)
const ArrayDef nikonSi5Def []
Nikon Shot Info binary array - definition 5 (ver 01.xx and ver 02.xx)
const ArrayCfg nikonSi6Cfg
Nikon Shot Info binary array - configuration 6 (ver 01.xx)
const ArraySet nikonSiSet []
Nikon Lens Data configurations and definitions.
const ArrayCfg nikonLd1Cfg
Nikon Lens Data binary array - configuration 1.
const ArrayCfg nikonLd2Cfg
Nikon Lens Data binary array - configuration 2.
const ArrayCfg nikonLd3Cfg
Nikon Lens Data binary array - configuration 3.
const ArrayCfg nikonLd4Cfg
Nikon Lens Data binary array - configuration 3.
const ArrayDef nikonLdDef []
Nikon Lens Data binary array - definition.
const ArrayDef nikonLd4Def []
Nikon Lens Data binary array - definition.
const ArraySet nikonLdSet []
Nikon Lens Data configurations and definitions.
const ArrayCfg nikonCb1Cfg
Nikon Color Balance binary array - configuration 1.
const ArrayCfg nikonCb2Cfg
Nikon Color Balance binary array - configuration 2.
const ArrayCfg nikonCb2aCfg
Nikon Color Balance binary array - configuration 2a.
const ArrayCfg nikonCb2bCfg
Nikon Color Balance binary array - configuration 2b.
const ArrayCfg nikonCb3Cfg
Nikon Color Balance binary array - configuration 3.
const ArrayCfg nikonCb4Cfg
Nikon Color Balance binary array - configuration 4.
const ArrayDef nikonCb1Def []
Nikon Color Balance binary array - definition 1 (D100)
const ArrayDef nikonCb2Def []
Nikon Color Balance binary array - definition 2 (D2H)
const ArrayDef nikonCb2aDef []
Nikon Color Balance binary array - definition 2a (D50)
const ArrayDef nikonCb2bDef []
Nikon Color Balance binary array - definition 2b (D2X=0204,D2Hs=0206,D200=0207,D40=0208)
const ArrayDef nikonCb3Def []
Nikon Color Balance binary array - definition 3 (D70)
const ArrayDef nikonCb4Def []
Nikon Color Balance binary array - definition 4 (D3)
const ArraySet nikonCbSet []
Nikon Color Balance configurations and definitions.
const ArrayCfg minoCsoCfg
Minolta Camera Settings (old) binary array - configuration.
const ArrayCfg minoCsnCfg
Minolta Camera Settings (new) binary array - configuration.
const ArrayCfg minoCs7Cfg
Minolta 7D Camera Settings binary array - configuration.
const ArrayDef minoCs7Def []
Minolta 7D Camera Settings binary array - definition.
const ArrayCfg minoCs5Cfg
Minolta 5D Camera Settings binary array - configuration.
const ArrayDef minoCs5Def []
Minolta 5D Camera Settings binary array - definition.
const ArrayCfg sony1CsCfg
Sony1 Camera Settings binary array - configuration.
const ArrayCfg sony1Cs2Cfg
Sony1 Camera Settings 2 binary array - configuration.
const ArrayCfg sony2FpCfg
const ArrayDef sony2FpDef []
const ArrayCfg sony2010eCfg
const ArrayDef sony2010eDef []
const ArraySet sony2010eSet []
Sony1 Camera Settings configurations and definitions.
const ArrayDef sonyCsDef []
Sony[12] Camera Settings binary array - definition.
const ArrayCfg sony2CsCfg
Sony2 Camera Settings binary array - configuration.
const ArrayCfg sony2Cs2Cfg
Sony2 Camera Settings 2 binary array - configuration.
const ArrayDef sonyCs2Def []
Sony[12] Camera Settings 2 binary array - definition.
const ArraySet sony1CsSet []
Sony1 Camera Settings configurations and definitions.
const ArraySet sony2CsSet []
Sony2 Camera Settings configurations and definitions.
const ArrayCfg sony1MCsoCfg
Sony Minolta Camera Settings (old) binary array - configuration.
const ArrayCfg sony1MCsnCfg
Sony Minolta Camera Settings (new) binary array - configuration.
const ArrayCfg sony1MCs7Cfg
Sony Minolta 7D Camera Settings binary array - configuration.
const ArrayCfg sony1MCsA100Cfg
Sony Minolta A100 Camera Settings binary array - configuration.
const ArrayDef sony1MCsA100Def []
Sony Minolta A100 Camera Settings binary array - definition.
const ArrayCfg samsungPwCfg
Samsung PictureWizard binary array - configuration.
const ArrayDef samsungPwDef []
Samsung PictureWizard binary array - definition.
Detailed Description
Contains internal objects which are not published and are not part of the libexiv2 API.
Function Documentation
binaryToString()
template<typename T > binaryToStringHelper< T > Exiv2::Internal::binaryToString (const Slice< T > sl) throw () inline
format binary data for display in Image::printStructure()
This function creates a new helper class that can be passed to a std::ostream for output. It creates a printable version of the binary data in the slice sl according to the following rules:
characters with numeric values larger than 0x20 (= space) and smaller or equal to 0x7F (Delete) are printed as ordinary characters
characters outside of that range are printed as '.'
if the last element of the slice is 0, then it is omitted
Parameters
[in] sl Slice containing binary data buffer that should be printed.
Returns
Helper object, that can be passed into a std::ostream and produces an output according to the aforementioned rules.
Exceptions
This function does not throw. The output of the helper object to the stream throws neither.
Referenced by Exiv2::Image::printIFDStructure(), Exiv2::IptcData::printStructure(), Exiv2::Jp2Image::printStructure(), Exiv2::RafImage::printStructure(), and Exiv2::WebPImage::printStructure().
canonEv()
float Exiv2::Internal::canonEv (long val)
Convert Canon hex-based EV (modulo 0x20) to real number Ported from Phil Harvey's Image::ExifTool::Canon::CanonEv by Will Stokes.
0x00 -> 0 0x0c -> 0.33333 0x10 -> 0.5 0x14 -> 0.66666 0x20 -> 1 .. 160 -> 5 128 -> 4 143 -> 4.46875
Referenced by printCsLensByFocalLengthAndMaxAperture(), Exiv2::Internal::CanonMakerNote::printSi0x0001(), Exiv2::Internal::CanonMakerNote::printSi0x0002(), Exiv2::Internal::CanonMakerNote::printSi0x0015(), and Exiv2::Internal::CanonMakerNote::printSi0x0016().
isTiffImageTag()
bool Exiv2::Internal::isTiffImageTag (uint16_t tag, IfdId group)
Convenience function to check if tag, group is in the list of TIFF image tags.
List of TIFF image tags
References Exiv2::find(), and groupName().
Referenced by Exiv2::Internal::Cr2Header::isImageTag(), and Exiv2::Internal::TiffHeader::isImageTag().
ltrim()
std::string & Exiv2::Internal::ltrim (std::string & s, const char * t = " \t\n\r\f\v") inline
http://stackoverflow.com/questions/1798112/removing-leading-and-trailing-spaces-from-a-string trim from left
Referenced by trim().
nikonAf2Selector()
int Exiv2::Internal::nikonAf2Selector (uint16_t tag, const byte * pData, uint32_t size, TiffComponent *const pRoot)
Function to select cfg + def of a Nikon complex binary array.
Parameters
tag Tag number of the binary array
pData Pointer to the raw array data.
size Size of the array data.
pRoot Pointer to the root component of the TIFF tree.
Returns
An index into the array set, -1 if no match was found.
nikonCrypt()
DataBuf Exiv2::Internal::nikonCrypt (uint16_t tag, const byte * pData, uint32_t size, TiffComponent *const pRoot)
Encrypt and decrypt Nikon data.
Checks the version of the Nikon data array and en/decrypts (portions of) it as needed. (The Nikon encryption algorithm is symmetric.)
Note
This function requires access to other components of the composite, it should only be called after all other components are read.
Parameters
tag Tag number of the binary array
pData Pointer to the start of the data to en/decrypt.
size Size of the data buffer.
pRoot Pointer to the root element of the composite.
Returns
En/decrypted data. Ownership of the memory is passed to the caller. The buffer may be empty in case no decryption was needed.
References Exiv2::Internal::TiffComponent::accept(), Exiv2::DataBuf::alloc(), Exiv2::Value::count(), Exiv2::find(), Exiv2::Internal::TiffFinder::init(), Exiv2::model(), nikonArrayIdx, Exiv2::DataBuf::pData_, Exiv2::Internal::TiffEntryBase::pValue(), Exiv2::Internal::TiffFinder::result(), Exiv2::DataBuf::size_, Exiv2::Internal::NikonArrayIdx::start_, Exiv2::Value::toLong(), and Exiv2::Value::toString().
nikonSelector()
int Exiv2::Internal::nikonSelector (uint16_t tag, const byte * pData, uint32_t size, TiffComponent *const pRoot)
Function to select cfg + def of a Nikon complex binary array.
Parameters
tag Tag number of the binary array
pData Pointer to the raw array data.
size Size of the array data.
pRoot Pointer to the root component of the TIFF tree.
Returns
An index into the array set, -1 if no match was found.
References Exiv2::find(), Exiv2::Internal::NikonArrayIdx::idx_, and nikonArrayIdx.
operator<<()
template<typename T > std::ostream & Exiv2::Internal::operator<< (std::ostream & stream, const binaryToStringHelper< T > & binToStr)
Actual implementation of the output algorithm described in binaryToString.
Exceptions
nothing
printCsLensByFocalLength()
std::ostream & Exiv2::Internal::printCsLensByFocalLength (std::ostream & os, const Value & value, const ExifData * metadata)
Special treatment pretty-print function for non-unique lens ids.
printCsLensByFocalLength to human readable string
References canonCsLensType, convertFocalLength(), Exiv2::Value::count(), extractLensFocalLength(), Exiv2::find(), Exiv2::Internal::LensTypeAndFocalLengthAndMaxAperture::focalLength_, Exiv2::Internal::LensTypeAndFocalLengthAndMaxAperture::focalLengthMax_, Exiv2::Internal::TagDetails::label_, Exiv2::Internal::LensTypeAndFocalLengthAndMaxAperture::lensType_, Exiv2::Value::toLong(), Exiv2::Value::typeId(), and Exiv2::unsignedShort.
printCsLensByFocalLengthAndMaxAperture()
std::ostream & Exiv2::Internal::printCsLensByFocalLengthAndMaxAperture (std::ostream & os, const Value & value, const ExifData * metadata)
Special treatment pretty-print function for non-unique lens ids.
printCsLensByFocalLengthAndMaxAperture to human readable string
References canonCsLensType, canonEv(), convertFocalLength(), Exiv2::Value::count(), Exiv2::ExifData::end(), extractLensFocalLength(), Exiv2::find(), Exiv2::ExifData::findKey(), fnumber(), Exiv2::Internal::LensTypeAndFocalLengthAndMaxAperture::focalLengthMax_, Exiv2::Internal::TagDetails::label_, Exiv2::Internal::LensTypeAndFocalLengthAndMaxAperture::lensType_, Exiv2::Internal::LensTypeAndFocalLengthAndMaxAperture::maxAperture_, Exiv2::Value::toLong(), Exiv2::Value::typeId(), and Exiv2::unsignedShort.
printCsLensByFocalLengthTC()
std::ostream & Exiv2::Internal::printCsLensByFocalLengthTC (std::ostream & os, const Value & value, const ExifData * metadata)
Special treatment pretty-print function for non-unique lens ids.
printCsLensByFocalLengthTC to human readable string
References canonCsLensType, convertFocalLength(), Exiv2::Value::count(), extractLensFocalLength(), Exiv2::find(), Exiv2::Internal::LensTypeAndFocalLengthAndMaxAperture::focalLengthMax_, Exiv2::Internal::TagDetails::label_, Exiv2::Internal::LensTypeAndFocalLengthAndMaxAperture::lensType_, Exiv2::Value::toLong(), Exiv2::Value::typeId(), and Exiv2::unsignedShort.
sony2010eSelector()
int Exiv2::Internal::sony2010eSelector (uint16_t tag, const byte * pData, uint32_t size, TiffComponent *const pRoot)
Function to select cfg + def of the Sony 2010 Miscellaneous Information complex binary array.
Parameters
tag Tag number of the binary array
pData Pointer to the raw array data.
size Size of the array data.
pRoot Pointer to the root component of the TIFF tree.
Returns
An index into the array set, -1 if no match was found.
References Exiv2::model().
sonyCsSelector()
int Exiv2::Internal::sonyCsSelector (uint16_t tag, const byte * pData, uint32_t size, TiffComponent *const pRoot)
Function to select cfg + def of the Sony Camera Settings complex binary array.
Parameters
tag Tag number of the binary array
pData Pointer to the raw array data.
size Size of the array data.
pRoot Pointer to the root component of the TIFF tree.
Returns
An index into the array set, -1 if no match was found.
References Exiv2::model().
tagNumber()
uint16_t Exiv2::Internal::tagNumber (const std::string & tagName, IfdId ifdId)
Return the tag number for one combination of IFD id and tagName. If the tagName is not known, it expects tag names in the form "0x01ff" and converts them to unsigned integer.
Exceptions
Error if the tagname or ifdId is invalid
References Exiv2::isHex(), Exiv2::TagInfo::tag_, and tagInfo().
Referenced by Exiv2::ExifKey::Impl::decomposeKey().
Variable Documentation
aftOnOff
const TagDetails Exiv2::Internal::aftOnOff[] extern
Initial value:
= {
        {  0, N_("Off")  },
        {  1, N_("On") },
        {  2, N_("On") }
    }
OnOff.
autoExposureBracketing
const TagDetails Exiv2::Internal::autoExposureBracketing[] extern
Initial value:
= {
        { 65535, "On"          },
        { 0,     "Off"         },
        { 1,     "On (shot 1)" },
        { 2,     "On (shot 2)" },
        { 3,     "On (shot 3)" },
    }
cameraType
const TagDetails Exiv2::Internal::cameraType[] extern
Initial value:
= {
        {   0, "n/a"           },
        { 248, "EOS High-end"  },
        { 250, "Compact"       },
        { 252, "EOS Mid-range" },
        { 255, "DV Camera"     },
    }
canonAFAreaMode
const TagDetails Exiv2::Internal::canonAFAreaMode[] extern
Initial value:
= {
         {   0, N_("Off (Manual Focus)")           },
         {   1, N_("AF Point Expansion (surround)")},
         {   2, N_("Single-point AF")              },
         {   4, N_("Multi-point AF")               },
         {   5, N_("Face Detect AF")               },
         {   6, N_("Face + Tracking")              },
         {   7, N_("Zone AF")                      },
         {   8, N_("AF Point Expansion (4 point)") },
         {   9, N_("Spot AF")                      },
         {  10, N_("AF Point Expansion (8 point)") },
         {  11, N_("Flexizone Multi (49 point)")   },
         {  12, N_("Flexizone Multi (9 point)")    },
         {  13, N_("Flexizone Single")             },
         {  14, N_("Large Zone AF")                },
     }
Canon AF Area Mode, tag 0x2601.
canonAFAreaSelectionMethod
const TagDetails Exiv2::Internal::canonAFAreaSelectionMethod[] extern
Initial value:
= {
        { 0, N_("M-Fn Button") },
        { 1, N_("Main Dial") }
    }
canonAFAssistBeam
const TagDetails Exiv2::Internal::canonAFAssistBeam[] extern
Initial value:
= {
        { 0, N_("Enable") },
        { 1, N_("Disable") },
        { 2, N_("IR AF Assist Beam Mode") }
    }
canonAFMicroAdjMode
const TagDetails Exiv2::Internal::canonAFMicroAdjMode[] extern
Initial value:
= {
        { 0, N_("Disable") },
        { 1, N_("Adjust all by the same amount") },
        { 2, N_("Adjust by lens") }
    }
canonAFPointDisplayDuringFocus
const TagDetails Exiv2::Internal::canonAFPointDisplayDuringFocus[] extern
Initial value:
= {
        { 0, N_("Selected (constant)") },
        { 1, N_("All (constant)") },
        { 1, N_("Selected (pre-AF, focused)") },
        { 1, N_("Selected (focused)") },
        { 1, N_("Disabled") }
    }
canonAFStatusViewfinder
const TagDetails Exiv2::Internal::canonAFStatusViewfinder[] extern
Initial value:
= {
        { 0, N_("Auto") },
        { 1, N_("Enable") },
        { 2, N_("Disable") },
    }
canonAIServoFirstImage
const TagDetails Exiv2::Internal::canonAIServoFirstImage[] extern
Initial value:
= {
        { 0, N_("Equal Priority") },
        { 1, N_("Release Priority") },
        { 2, N_("Focus Priority") }
    }
canonAIServoSecondImage
const TagDetails Exiv2::Internal::canonAIServoSecondImage[] extern
Initial value:
= {
        { 0, N_("Equal Priority") },
        { 1, N_("Release Priority") },
        { 2, N_("Focus Priority") },
        { 3, N_("Release High Priority") },
        { 4, N_("Focus High Priority") },
    }
canonAmbienceSelection
const TagDetails Exiv2::Internal::canonAmbienceSelection[] extern
Initial value:
= {
        { 0, N_("Standard") },
        { 1, N_("Vivid") },
        { 2, N_("Warm") },
        { 3, N_("Soft") },
        { 4, N_("Cool") },
        { 5, N_("Intense") },
        { 6, N_("Brighter") },
        { 7, N_("Darker") },
        { 8, N_("Monochrome") }
    }
canonAspectInfo
const TagDetails Exiv2::Internal::canonAspectInfo[] extern
Initial value:
= {
        { 0, N_("3:2") },
        { 1, N_("1:1") },
        { 2, N_("4:3") },
        { 7, N_("16:9") },
        { 8, N_("4:5") },
        { 12, N_("3:2 (APS-H crop)") },
        { 13, N_("3:2 (APS-C crop)") }
    }
canonAutoAFPointSelEOSiTRAF
const TagDetails Exiv2::Internal::canonAutoAFPointSelEOSiTRAF[] extern
Initial value:
= {
        { 0, N_("Enable") },
        { 1, N_("Disable") }
    }
canonAutoLightingOptimizer
const TagDetails Exiv2::Internal::canonAutoLightingOptimizer[] extern
Initial value:
= {
        { 0, N_("Standard") },
        { 1, N_("Low") },
        { 2, N_("Strong") },
        { 2, N_("Off") }
    }
canonAVFDisplayIllumination
const TagDetails Exiv2::Internal::canonAVFDisplayIllumination[] extern
Initial value:
= {
        { 0, N_("Auto") },
        { 1, N_("Enable") },
        { 2, N_("Disable") },
    }
canonBracketMode
const TagDetails Exiv2::Internal::canonBracketMode[] extern
Initial value:
= {
        { 0, N_("Off") },
        { 1, N_("AEB") },
        { 2, N_("FEB") },
        { 3, N_("ISO") },
        { 4, N_("WB")  }
    }
BracketMode, tag 0x0003.
canonCategories
const TagDetails Exiv2::Internal::canonCategories[] extern
Initial value:
= {
        { 0x0001, N_("People")  },
        { 0x0002, N_("Scenery") },
        { 0x0004, N_("Events")  },
        { 0x0008, N_("User 1")  },
        { 0x0016, N_("User 2")  },
        { 0x0032, N_("User 3")  },
        { 0x0064, N_("To Do")   }
    }
canonCfCfg
const ArrayCfg Exiv2::Internal::canonCfCfg extern
Initial value:
= {
        canonCfId,
        invalidByteOrder,
        ttUnsignedShort,
        notEncrypted,
        true,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Canon Custom Function binary array - configuration.
canonColorSpace
const TagDetails Exiv2::Internal::canonColorSpace[] extern
Initial value:
= {
        {  1, N_("sRGB")      },
        {  2, N_("Adobe RGB") }
    }
ColorSpace, tag 0x00b4.
canonContrastInfo
const TagDetails Exiv2::Internal::canonContrastInfo[] extern
Initial value:
= {
        { 0x0, N_("Off")  },
        { 0x8, N_("On") },
        { 0xfff, N_("n/a") }
    }
canonCsAESetting
const TagDetails Exiv2::Internal::canonCsAESetting[] extern
Initial value:
= {
        { 0, N_("Normal AE")                       },
        { 1, N_("Exposure compensation")           },
        { 2, N_("AE lock")                         },
        { 3, N_("AE lock + exposure compensation") },
        { 4, N_("No AE")                           }
    }
AESetting, tag 0x0021.
canonCsAfPoint
const TagDetails Exiv2::Internal::canonCsAfPoint[] extern
Initial value:
= {
        { 0x2005, N_("Manual AF point selection") },
        { 0x3000, N_("None (MF)")                 },
        { 0x3001, N_("Auto-selected")             },
        { 0x3002, N_("Right")                     },
        { 0x3003, N_("Center")                    },
        { 0x3004, N_("Left")                      },
        { 0x4001, N_("Auto AF point selection")   },
        { 0x4006, N_("Face Detect")               }
    }
AFPoint, tag 0x0013.
canonCsCfg
const ArrayCfg Exiv2::Internal::canonCsCfg extern
Initial value:
= {
        canonCsId,
        invalidByteOrder,
        ttUnsignedShort,
        notEncrypted,
        true,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Canon Camera Settings binary array - configuration.
canonCsDef
const ArrayDef Exiv2::Internal::canonCsDef[] extern
Initial value:
= {
        { 46, ttUnsignedShort, 3 }
    }
Canon Camera Settings binary array - definition.
canonCsDigitalZoom
const TagDetails Exiv2::Internal::canonCsDigitalZoom[] extern
Initial value:
= {
        { 0, N_("None")  },
        { 1, "2x"        },
        { 2, "4x"        },
        { 3, N_("Other") },
        { 3, N_("Other") }
    }
DigitalZoom, tag 0x000c.
canonCsDriveMode
const TagDetails Exiv2::Internal::canonCsDriveMode[] extern
Initial value:
= {
        {  0, N_("Single / timer")             },
        {  1, N_("Continuous")                 },
        {  2, N_("Movie")                      },
        {  3, N_("Continuous, speed priority") },
        {  3, N_("Continuous, tracking priority") },
        {  4, N_("Continuous, low")            },
        {  5, N_("Continuous, high")           },
        {  6, N_("Silent Single")              },
        {  9, N_("Single, Silent")             },
        { 10, N_("Continuous, Silent")         }
    }
DriveMode, tag 0x0005.
canonCsExposureProgram
const TagDetails Exiv2::Internal::canonCsExposureProgram[] extern
Initial value:
= {
        { 0, N_("Easy shooting (Auto)")   },
        { 1, N_("Program (P)")            },
        { 2, N_("Shutter priority (Tv)")  },
        { 3, N_("Aperture priority (Av)") },
        { 4, N_("Manual (M)")             },
        { 5, N_("A-DEP")                  },
        { 6, N_("M-DEP")                  },
        { 7, N_("Bulb")                   }
    }
ExposureProgram, tag 0x0014.
canonCsFlashActivity
const TagDetails Exiv2::Internal::canonCsFlashActivity[] extern
Initial value:
= {
        { 0, N_("Did not fire") },
        { 1, N_("Fired")        }
    }
FlashActivity, tag 0x001c.
canonCsFlashDetails
const TagDetailsBitmask Exiv2::Internal::canonCsFlashDetails[] extern
Initial value:
= {
        { 0x4000, N_("External flash")        },
        { 0x2000, N_("Internal flash")        },
        { 0x0001, N_("Manual")                },
        { 0x0002, N_("TTL")                   },
        { 0x0004, N_("A-TTL")                 },
        { 0x0008, N_("E-TTL")                 },
        { 0x0010, N_("FP sync enabled")       },
        { 0x0080, N_("2nd-curtain sync used") },
        { 0x0800, N_("FP sync used")          }
    }
FlashDetails, tag 0x001d.
canonCsFlashMode
const TagDetails Exiv2::Internal::canonCsFlashMode[] extern
Initial value:
= {
        {  0, N_("Off")            },
        {  1, N_("Auto")           },
        {  2, N_("On")             },
        {  3, N_("Red-eye")        },
        {  4, N_("Slow sync")      },
        {  5, N_("Auto + red-eye") },
        {  6, N_("On + red-eye")   },
        { 16, N_("External")       },
        { 16, N_("External")       }
    }
FlashMode, tag 0x0004.
canonCsFocusContinuous
const TagDetails Exiv2::Internal::canonCsFocusContinuous[] extern
Initial value:
= {
        { 0, N_("Single")     },
        { 1, N_("Continuous") },
        { 8, N_("Manual")     }
    }
FocusContinuous, tag 0x0020.
canonCsFocusMode
const TagDetails Exiv2::Internal::canonCsFocusMode[] extern
Initial value:
= {
        {   0, N_("One shot AF")      },
        {   1, N_("AI servo AF")      },
        {   2, N_("AI focus AF")      },
        {   3, N_("Manual focus (3)") },
        {   4, N_("Single")           },
        {   5, N_("Continuous")       },
        {   6, N_("Manual focus (6)") },
        {  16, N_("Pan focus")        },
        { 256, N_("AF + MF")          },
        { 512, N_("Movie Snap Focus") },
        { 519, N_("Movie Servo AF")   },
        { 519, N_("Movie Servo AF")   }
    }
FocusMode, tag 0x0007.
canonCsFocusType
const TagDetails Exiv2::Internal::canonCsFocusType[] extern
Initial value:
= {
        {  0, N_("Manual")       },
        {  1, N_("Auto")         },
        {  2, N_("Not known")    },
        {  3, N_("Macro")        },
        {  4, N_("Very close")   },
        {  5, N_("Close")        },
        {  6, N_("Middle range") },
        {  7, N_("Far range")    },
        {  8, N_("Pan focus")    },
        {  9, N_("Super macro")  },
        { 10, N_("Infinity")     }
    }
FocusType, tag 0x0012.
canonCsImageSize
const TagDetails Exiv2::Internal::canonCsImageSize[] extern
Initial value:
= {
        {   0, N_("Large")             },
        {   1, N_("Medium")            },
        {   2, N_("Small")             },
        {   5, N_("Medium 1")          },
        {   6, N_("Medium 2")          },
        {   7, N_("Medium 3")          },
        {   8, N_("Postcard")          },
        {   9, N_("Widescreen")        },
        {  10, N_("Medium Widescreen") },
        {  14, N_("Small 1")           },
        {  15, N_("Small 2")           },
        {  16, N_("Small 3")           },
        { 128, N_("640x480 Movie")     },
        { 129, N_("Medium Movie")      },
        { 130, N_("Small Movie")       },
        { 137, N_("1280x720 Movie")    },
        { 142, N_("1920x1080 Movie")   }
    }
ImageSize, tag 0x000a.
canonCsImageStabilization
const TagDetails Exiv2::Internal::canonCsImageStabilization[] extern
Initial value:
= {
        {   0, N_("Off")            },
        {   1, N_("On")             },
        {   2, N_("Shoot Only")     },
        {   3, N_("Panning")        },
        {   4, N_("Dynamic")        },
        { 256, N_("Off (2)")        },
        { 257, N_("On (2)")         },
        { 258, N_("Shoot Only (2)") },
        { 259, N_("Panning (2)")    },
        { 260, N_("Dynamic (2)")    }
    }
ImageStabilization, tag 0x0022.
canonCsLnh
const TagDetails Exiv2::Internal::canonCsLnh[] extern
Initial value:
= {
        { 0xffff, N_("Low")    },
        { 0x0000, N_("Normal") },
        { 0x0001, N_("High")   }
    }
Contrast, Saturation Sharpness, tags 0x000d, 0x000e, 0x000f.
canonCsMacro
const TagDetails Exiv2::Internal::canonCsMacro[] extern
Initial value:
= {
        { 1, N_("On")  },
        { 2, N_("Off") }
    }
Macro, tag 0x0001.
canonCsManualFlashOutput
const TagDetails Exiv2::Internal::canonCsManualFlashOutput[] extern
Initial value:
= {
        { 0x0000, N_("n/a")    },
        { 0x0500, N_("Full")   },
        { 0x0502, N_("Medium") },
        { 0x0504, N_("Low")    },
        { 0x7fff, N_("n/a")    }
    }
ManualFlashOutput, tag 0x0029.
canonCsMeteringMode
const TagDetails Exiv2::Internal::canonCsMeteringMode[] extern
Initial value:
= {
        { 0, N_("Default")                 },
        { 1, N_("Spot")                    },
        { 2, N_("Average")                 },
        { 3, N_("Evaluative")              },
        { 4, N_("Partial")                 },
        { 5, N_("Center-weighted average") }
    }
MeteringMode, tag 0x0011.
canonCsPhotoEffect
const TagDetails Exiv2::Internal::canonCsPhotoEffect[] extern
Initial value:
= {
        { 0,   N_("Off")           },
        { 1,   N_("Vivid")         },
        { 2,   N_("Neutral")       },
        { 3,   N_("Smooth")        },
        { 4,   N_("Sepia")         },
        { 5,   N_("B&W")           },
        { 6,   N_("Custom")        },
        { 100, N_("My color data") },
        { 100, N_("My color data") }
    }
PhotoEffect, tag 0x0028.
canonCsQuality
const TagDetails Exiv2::Internal::canonCsQuality[] extern
Initial value:
= {
        { -1,  N_("n/a")          },
        { 1,   N_("Economy")      },
        { 2,   N_("Normal")       },
        { 3,   N_("Fine")         },
        { 4,   N_("RAW")          },
        { 5,   N_("Superfine")    },
        { 7,   N_("CRAW")         },
        { 130, N_("Normal Movie") },
        { 131, N_("Movie (2)")    }
    }
Quality, tag 0x0003.
canonCsRecordMode
const TagDetails Exiv2::Internal::canonCsRecordMode[] extern
Initial value:
= {
        {   1, N_("JPEG")               },
        {   2, N_("CRW+THM")            },
        {   3, N_("AVI+THM")            },
        {   4, N_("TIF")                },
        {   5, N_("TIF+JPEG")           },
        {   6, N_("CR2")                },
        {   7, N_("CR2+JPEG")           },
        {  9, N_("MOV")                 },
        { 10, N_("MP4")                 },
        { 11, N_("CRM")                 },
        { 12, N_("CR3")                 },
        { 13, N_("CR3+JPEG")            },
        { 14, N_("HIF")                 },
        { 15, N_("CR3+HIF")             }
    }
RecordMode, tag 0x0009.
canonCsSpotMeteringMode
const TagDetails Exiv2::Internal::canonCsSpotMeteringMode[] extern
Initial value:
= {
        { 0,   N_("Center")   },
        { 1,   N_("AF Point") }
    }
SpotMeteringMode, tag 0x0027.
canonCsSRAWQuality
const TagDetails Exiv2::Internal::canonCsSRAWQuality[] extern
Initial value:
= {
        { 0, N_("n/a")          },
        { 1, N_("sRAW1 (mRAW)") },
        { 2, N_("sRAW2 (sRAW)") }
    }
SRAWQuality, tag 0x002e.
canonDateStampMode
const TagDetails Exiv2::Internal::canonDateStampMode[] extern
Initial value:
= {
        { 0, N_("Off")  },
        { 1, N_("Date") },
        { 2, N_("Date & Time") }
    }
canonFiCfg
const ArrayCfg Exiv2::Internal::canonFiCfg extern
Initial value:
= {
        canonFiId,
        invalidByteOrder,
        ttUnsignedShort,
        notEncrypted,
        true,
        false,
        false,
        { 0, ttSignedShort, 1 }
    }
Canon File Info binary array - configuration.
canonFiDef
const ArrayDef Exiv2::Internal::canonFiDef[] extern
Initial value:
= {
        { 2, ttUnsignedLong, 1 }
    }
Canon File Info binary array - definition.
canonFilterEffect
const TagDetails Exiv2::Internal::canonFilterEffect[] extern
Initial value:
= {
        { 0, N_("None")   },
        { 1, N_("Yellow") },
        { 2, N_("Orange") },
        { 3, N_("Red")    },
        { 4, N_("Green")  }
    }
FilterEffect, tag 0x000e.
canonFilterInfo
const TagDetails Exiv2::Internal::canonFilterInfo[] extern
Initial value:
= {
        { -1, N_("Off") }
    }
canonHdr
const TagDetails Exiv2::Internal::canonHdr[] extern
Initial value:
= {
        { 0, N_("Off") },
        { 1, N_("On") },
        { 2, N_("On (RAW") }
    }
canonHdrEffect
const TagDetails Exiv2::Internal::canonHdrEffect[] extern
Initial value:
= {
        { 0, N_("Natural") },
        { 1, N_("Art (standard)") },
        { 2, N_("Art (vivid)") },
        { 3, N_("Art (bold)") },
        { 4, N_("Art (embossed)") }
    }
canonHighISONoiseReduction
const TagDetails Exiv2::Internal::canonHighISONoiseReduction[] extern
Initial value:
= {
        { 0, N_("Standard") },
        { 1, N_("Low") },
        { 2, N_("Strong") },
        { 2, N_("off") }
    }
canonInitialAFPointInServo
const TagDetails Exiv2::Internal::canonInitialAFPointInServo[] extern
Initial value:
= {
        { 0, N_("Initial AF Point Selected") },
        { 1, N_("Manual AF Point") },
        { 2, N_("Auto") },
    }
canonLensDriveWhenAFImpossible
const TagDetails Exiv2::Internal::canonLensDriveWhenAFImpossible[] extern
Initial value:
= {
        { 0, N_("Continue Focus Search") },
        { 1, N_("Stop Focus Search") }
    }
canonLongExposureNoiseReduction
const TagDetails Exiv2::Internal::canonLongExposureNoiseReduction[] extern
Initial value:
= {
        { 0, N_("Off") },
        { 1, N_("Auto") },
        { 2, N_("On") }
    }
canonManualAFPointSelPattern
const TagDetails Exiv2::Internal::canonManualAFPointSelPattern[] extern
Initial value:
= {
        { 0, N_("Stops at AF Area Edges") },
        { 1, N_("Continous") }
    }
canonMiniatureFilterOrientation
const TagDetails Exiv2::Internal::canonMiniatureFilterOrientation[] extern
Initial value:
= {
        { 0, N_("Horizontal") },
        { 1, N_("Vertical") }
    }
canonModifiedSharpnessFreq
const TagDetails Exiv2::Internal::canonModifiedSharpnessFreq[] extern
Initial value:
= {
        { 0, N_("n/a") },
        { 1, N_("Lowest") },
        { 2, N_("Low") },
        { 3, N_("Standard") },
        { 4, N_("High") },
        { 5, N_("Highest") }
    }
canonModifiedToneCurve
const TagDetails Exiv2::Internal::canonModifiedToneCurve[] extern
Initial value:
= {
        { 0, N_("Standard") },
        { 1, N_("Manual") },
        { 2, N_("Custom") }
    }
canonMultiExposure
const TagDetails Exiv2::Internal::canonMultiExposure[] extern
Initial value:
= {
        { 0, N_("Off") },
        { 1, N_("On") },
        { 2, N_("On (RAW)") }
    }
canonMultiExposureControl
const TagDetails Exiv2::Internal::canonMultiExposureControl[] extern
Initial value:
= {
        { 0, N_("Additive") },
        { 1, N_("Average") },
        { 2, N_("Bright (comparative)") },
        { 3, N_("Dark (comparative)") }
    }
canonMyColors
const TagDetails Exiv2::Internal::canonMyColors[] extern
Initial value:
= {
        { 0, N_("Off")  },
        { 1, N_("Positive Film") },
        { 2, N_("Light Skin Tone") },
        { 3, N_("Dark Skin Tone")  },
        { 4, N_("Vivid Blue") },
        { 5, N_("Vivid Green") },
        { 6, N_("Vivid Red")  },
        { 7, N_("Color Accent") },
        { 8, N_("Color Swap") },
        { 9, N_("Custom")  },
        { 12, N_("Vivid") },
        { 13, N_("Neutral") },
        { 14, N_("Sepia") },
        { 15, N_("B&W") }
    }
canonNoiseReduction
const TagDetails Exiv2::Internal::canonNoiseReduction[] extern
Initial value:
= {
        { 0, N_("Off")  },
        { 1, N_("On 1") },
        { 2, N_("On 2") },
        { 3, N_("On")   },
        { 4, N_("Auto") }
    }
NoiseReduction, tag 0x0008.
canonOffOn
const TagDetails Exiv2::Internal::canonOffOn[] extern
Initial value:
= {
        {  0, N_("Off") },
        {  1, N_("On")  }
    }
OffOn, multiple tags.
canonOneShotAFRelease
const TagDetails Exiv2::Internal::canonOneShotAFRelease[] extern
Initial value:
= {
        { 0, N_("Focus Priority") },
        { 1, N_("Release Priortiy") }
    }
canonOrientationLinkedAF
const TagDetails Exiv2::Internal::canonOrientationLinkedAF[] extern
Initial value:
= {
        { 0, N_("Same for Vert/Horiz Points") },
        { 1, N_("Separate for Vert/Horiz Points") },
        { 2, N_("Separate Area+Points") }
    }
canonPaCfg
const ArrayCfg Exiv2::Internal::canonPaCfg extern
Initial value:
= {
        canonPaId,
        invalidByteOrder,
        ttUnsignedShort,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Canon Panorama binary array - configuration.
canonPaDirection
const TagDetails Exiv2::Internal::canonPaDirection[] extern
Initial value:
= {
        { 0, N_("Left to right")          },
        { 1, N_("Right to left")          },
        { 2, N_("Bottom to top")          },
        { 3, N_("Top to bottom")          },
        { 4, N_("2x2 matrix (Clockwise)") }
    }
PanoramaDirection, tag 0x0005.
canonPiAFPointsUsed
const TagDetailsBitmask Exiv2::Internal::canonPiAFPointsUsed[] extern
Initial value:
= {
        { 0x01, N_("right")     },
        { 0x02, N_("mid-right") },
        { 0x04, N_("bottom")    },
        { 0x08, N_("center")    },
        { 0x10, N_("top")       },
        { 0x20, N_("mid-left")  },
        { 0x40, N_("left")      }
    }
AFPointsUsed, tag 0x0016.
canonPiAFPointsUsed20D
const TagDetailsBitmask Exiv2::Internal::canonPiAFPointsUsed20D[] extern
Initial value:
= {
        { 0x001, N_("top")         },
        { 0x002, N_("upper-left")  },
        { 0x004, N_("upper-right") },
        { 0x008, N_("left")        },
        { 0x010, N_("center")      },
        { 0x020, N_("right")       },
        { 0x040, N_("lower-left")  },
        { 0x080, N_("lower-right") },
        { 0x100, N_("bottom")      }
    }
AFPointsUsed20D, tag 0x001a.
canonPiCfg
const ArrayCfg Exiv2::Internal::canonPiCfg extern
Initial value:
= {
        canonPiId,
        invalidByteOrder,
        ttUnsignedShort,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Canon Picture Info binary array - configuration.
canonPictureStyle
const TagDetails Exiv2::Internal::canonPictureStyle[] extern
Initial value:
= {
        { 0x00, N_("None")            },
        { 0x01, N_("Standard")        },
        { 0x02, N_("Portrait")        },
        { 0x03, N_("High Saturation") },
        { 0x04, N_("Adobe RGB")       },
        { 0x05, N_("Low Saturation")  },
        { 0x06, N_("CM Set 1")        },
        { 0x07, N_("CM Set 2")        },
        { 0x21, N_("User Def. 1")     },
        { 0x22, N_("User Def. 2")     },
        { 0x23, N_("User Def. 3")     },
        { 0x41, N_("PC 1")            },
        { 0x42, N_("PC 2")            },
        { 0x43, N_("PC 3")            },
        { 0x81, N_("Standard")        },
        { 0x82, N_("Portrait")        },
        { 0x83, N_("Landscape")       },
        { 0x84, N_("Neutral")         },
        { 0x85, N_("Faithful")        },
        { 0x86, N_("Monochrome")      },
        { 0x87, N_("Auto")            },
        { 0x88, N_("Fine Detail")     }
    }
PictureStyle Values.
canonPrCfg
const ArrayCfg Exiv2::Internal::canonPrCfg extern
Initial value:
= {
        canonPrId,
        invalidByteOrder,
        ttUnsignedShort,
        notEncrypted,
        true,
        false,
        false,
        { 0, ttSignedShort, 1 }
    }
Canon Processing Info binary array - configuration.
canonPreviewQuality
const TagDetails Exiv2::Internal::canonPreviewQuality[] extern
Initial value:
= {
        { -1, N_("n/a") },
        { 1, N_("Economy") },
        { 2, N_("Normal") },
        { 3, N_("Fine") },
        { 4, N_("RAW") },
        { 5, N_("Superfine") },
        { 7, N_("CRAW") },
        { 130, N_("Normal Movie") },
        { 131, N_("Movie (2)") }
    }
canonRawJpgSize
const TagDetails Exiv2::Internal::canonRawJpgSize[] extern
Initial value:
= {
        {  -1, N_("n/a")               },
        {   0, N_("Large")             },
        {   1, N_("Medium")            },
        {   2, N_("Small")             },
        {   5, N_("Medium 1")          },
        {   6, N_("Medium 2")          },
        {   7, N_("Medium 3")          },
        {   8, N_("Postcard")          },
        {   9, N_("Widescreen")        },
        {  10, N_("Medium Widescreen") },
        {  14, N_("Small 1")           },
        {  15, N_("Small 2")           },
        {  16, N_("Small 3")           },
        { 128, N_("640x480 Movie")     },
        { 129, N_("Medium Movie")      },
        { 130, N_("Small Movie")       },
        { 137, N_("1280x720 Movie")    },
        { 142, N_("1920x1080 Movie")   },
        { 143, N_("4096x2160 Movie")   }
    }
RawJpgSize, tag 0x0007.
canonRFLensType
const TagDetails Exiv2::Internal::canonRFLensType[] extern
Initial value:
= {
        { 0, N_("n/a")   },
        { 257, N_("Canon RF 50mm F1.2L USM")  },
        { 257, N_("Canon RF 24-105mm F4L IS USM")  },
        { 257, N_("Canon RF 28-70mm F2L USM")  },
        { 257, N_("Canon RF 35mm F1.8 MACRO IS STM")  },
        { 257, N_("Canon RF 85mm F1.2L USM")  },
        { 257, N_("Canon RF 85mm F1.2L USM DS")  },
        { 257, N_("Canon RF 24-70mm F2.8L IS USM")  },
        { 257, N_("Canon RF 15-35mm F2.8L IS USM")  },
        { 257, N_("Canon RF 24-240mm F4-6.3 IS USM")  },
        { 257, N_("Canon RF 70-200mm F2.8L IS USM")  },
        { 257, N_("Canon RF 85mm F2 MACRO IS STM")  },
        { 257, N_("Canon RF 600mm F11 IS STM")  },
        { 257, N_("Canon RF 600mm F11 IS STM + RF1.4x")  },
        { 257, N_("Canon RF 600mm F11 IS STM + RF2x")  },
        { 257, N_("Canon RF 800mm F11 IS STM")  },
        { 257, N_("Canon RF 800mm F11 IS STM + RF1.4x")  },
        { 257, N_("Canon RF 800mm F11 IS STM + RF2x")  },
        { 257, N_("Canon RF 24-105mm F4-7.1 IS STM")  },
        { 257, N_("Canon RF 100-500mm F4.5-7.1L IS USM")  },
        { 257, N_("Canon RF 100-500mm F4.5-7.1L IS USM + RF1.4x")  },
        { 257, N_("Canon RF 100-500mm F4.5-7.1L IS USM + RF2x")  }
    }
RFLensType, tag 0x003D.
canonSelectAFAreaSelectionMode
const TagDetails Exiv2::Internal::canonSelectAFAreaSelectionMode[] extern
Initial value:
= {
        { 0, N_("Single-Point-AF") },
        { 1, N_("Auto") },
        { 2, N_("Zone AF") },
        { 3, N_("AF Point Expansion (4 point)") },
        { 4, N_("Spot AF") },
        { 5, N_("AF Point Expansion (8 point)") }
    }
canonSerialNumberFormat
const TagDetails Exiv2::Internal::canonSerialNumberFormat[] extern
Initial value:
= {
        {  (long int)0x90000000, N_("Format 1") },
        {  (long int)0xa0000000, N_("Format 2") },
    }
SerialNumberFormat, tag 0x0015.
canonSharpnessFrequency
const TagDetails Exiv2::Internal::canonSharpnessFrequency[] extern
Initial value:
= {
        { 0, N_("n/a")      },
        { 1, N_("Lowest")   },
        { 2, N_("Low")      },
        { 3, N_("Standard") },
        { 4, N_("High")     },
        { 5, N_("Highest")  }
    }
Sharpness Frequency Values.
canonSiAFPointUsed
const TagDetailsBitmask Exiv2::Internal::canonSiAFPointUsed[] extern
Initial value:
= {
        { 0x0004, N_("left")   },
        { 0x0002, N_("center") },
        { 0x0001, N_("right")  }
    }
AFPointUsed, tag 0x000e.
Referenced by Exiv2::Internal::CanonMakerNote::printSi0x000e().
canonSiCfg
const ArrayCfg Exiv2::Internal::canonSiCfg extern
Initial value:
= {
        canonSiId,
        invalidByteOrder,
        ttUnsignedShort,
        notEncrypted,
        true,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Canon Shot Info binary array - configuration.
canonSiFlashBias
const TagDetails Exiv2::Internal::canonSiFlashBias[] extern
Initial value:
= {
        { 0xffc0, "-2 EV"    },
        { 0xffcc, "-1.67 EV" },
        { 0xffd0, "-1.50 EV" },
        { 0xffd4, "-1.33 EV" },
        { 0xffe0, "-1 EV"    },
        { 0xffec, "-0.67 EV" },
        { 0xfff0, "-0.50 EV" },
        { 0xfff4, "-0.33 EV" },
        { 0x0000, "0 EV"     },
        { 0x000c, "0.33 EV"  },
        { 0x0010, "0.50 EV"  },
        { 0x0014, "0.67 EV"  },
        { 0x0020, "1 EV"     },
        { 0x002c, "1.33 EV"  },
        { 0x0030, "1.50 EV"  },
        { 0x0034, "1.67 EV"  },
        { 0x0040, "2 EV"     }
    }
FlashBias, tag 0x000f.
canonSiWhiteBalance
const TagDetails Exiv2::Internal::canonSiWhiteBalance[] extern
Initial value:
= {
        {  0, N_("Auto")                        },
        {  1, N_("Daylight")                    },
        {  2, N_("Cloudy")                      },
        {  3, N_("Tungsten")                    },
        {  4, N_("Fluorescent")                 },
        {  5, N_("Flash")                       },
        {  6, N_("Custom")                      },
        {  7, N_("Black & White")               },
        {  8, N_("Shade")                       },
        {  9, N_("Manual Temperature (Kelvin)") },
        { 10, N_("PC Set 1")                    },
        { 11, N_("PC Set 2")                    },
        { 12, N_("PC Set 3")                    },
        { 14, N_("Daylight Fluorescent")        },
        { 15, N_("Custom 1")                    },
        { 16, N_("Custom 2")                    },
        { 17, N_("Underwater")                  },
        { 18, N_("Custom 3")                    },
        { 19, N_("Custom 3")                    },
        { 20, N_("PC Set 4")                    },
        { 21, N_("PC Set 5")                    },
        { 23, N_("Auto (ambience priority)")    }
    }
WhiteBalance, multiple tags.
canonSuperMacro
const TagDetails Exiv2::Internal::canonSuperMacro[] extern
Initial value:
= {
        {  0, N_("Off")     },
        {  1, N_("On (1)")  },
        {  2, N_("On (2)")  }
    }
SuperMacro, tag 0x001a.
canonTiCfg
const ArrayCfg Exiv2::Internal::canonTiCfg extern
Initial value:
= {
        canonTiId,
        invalidByteOrder,
        ttSignedLong,
        notEncrypted,
        true,
        false,
        false,
        { 0, ttSignedLong, 1 }
    }
Canon Time Info binary array - configuration.
canonToneCurve
const TagDetails Exiv2::Internal::canonToneCurve[] extern
Initial value:
= {
        { 0, N_("Standard") },
        { 1, N_("Manual")   },
        { 2, N_("Custom")   }
    }
Tone Curve Values.
canonToningEffect
const TagDetails Exiv2::Internal::canonToningEffect[] extern
Initial value:
= {
        { 0, N_("None")   },
        { 1, N_("Sepia")  },
        { 2, N_("Blue")   },
        { 3, N_("Purple") },
        { 4, N_("Green")  }
    }
ToningEffect, tag 0x000e.
canonUSMLensElectronicMF
const TagDetails Exiv2::Internal::canonUSMLensElectronicMF[] extern
Initial value:
= {
        { 0, N_("Enable After AF") },
        { 1, N_("Disable After AF") },
        { 2, N_("Disable in AF Mode") }
    }
canonWBBracketMode
const TagDetails Exiv2::Internal::canonWBBracketMode[] extern
Initial value:
= {
        { 0, N_("Off")           },
        { 1, N_("On (shift AB)") },
        { 2, N_("On (shift GM)") }
    }
WBBracketMode, tag 0x0009.
casio2AFMode
const TagDetails Exiv2::Internal::casio2AFMode[] extern
Initial value:
= {
        { 0, N_("Off")            },
        { 1, N_("Spot")           },
        { 2, N_("Multi")          },
        { 3, N_("Face Detection") },
        { 4, N_("Tracking")       },
        { 5, N_("Intelligent")    }
    }
AFMode, tag 0x3009.
casio2ArtMode
const TagDetails Exiv2::Internal::casio2ArtMode[] extern
Initial value:
= {
        {  0, N_("Normal")                },
        {  8, N_("Silent Movie")          },
        { 39, N_("HDR")                   },
        { 45, N_("Premium Auto")          },
        { 47, N_("Painting")              },
        { 49, N_("Crayon Drawing")        },
        { 51, N_("Panorama")              },
        { 52, N_("Art HDR")               },
        { 62, N_("High Speed Night Shot") },
        { 64, N_("Monochrome")            },
        { 67, N_("Toy Camera")            },
        { 68, N_("Pop Art")               },
        { 69, N_("Light Tone")            }
    }
Art Mode, tag 0x301b.
casio2AutoISO
const TagDetails Exiv2::Internal::casio2AutoISO[] extern
Initial value:
= {
        {  1, N_("On")                   },
        {  2, N_("Off")                  },
        {  7, N_("On (high sensitiviy)") },
        {  8, N_("On (anti-shake)")      },
        { 10, N_("High Speed")           }
    }
AutoISO, tag 0x3008.
casio2ColorFilter
const TagDetails Exiv2::Internal::casio2ColorFilter[] extern
Initial value:
= {
        { 0, N_("Off")    },
        { 1, N_("Blue")   },
        { 3, N_("Green")  },
        { 4, N_("Yellow") },
        { 5, N_("Red")    },
        { 6, N_("Purple") },
        { 7, N_("Pink")   }
    }
Color Filter, tag 0x3017.
casio2ColorMode
const TagDetails Exiv2::Internal::casio2ColorMode[] extern
Initial value:
= {
        { 0, N_("Off")           },
        { 2, N_("Black & White") },
        { 3, N_("Sepia")         }
    }
ColorMode, tag 0x3015.
casio2Contrast
const TagDetails Exiv2::Internal::casio2Contrast[] extern
Initial value:
= {
        { 0, N_("Low")    },
        { 1, N_("Normal") },
        { 2, N_("High")   }
    }
Contrast, tag 0x0020.
casio2DriveMode
const TagDetails Exiv2::Internal::casio2DriveMode[] extern
Initial value:
= {
        {   0, N_("Single Shot")         },
        {   1, N_("Continuous Shooting") },
        {   2, N_("Continuous (2 fps)")  },
        {   3, N_("Continuous (3 fps)")  },
        {   4, N_("Continuous (4 fps)")  },
        {   5, N_("Continuous (5 fps)")  },
        {   6, N_("Continuous (6 fps)")  },
        {   7, N_("Continuous (7 fps)")  },
        {  10, N_("Continuous (10 fps)") },
        {  12, N_("Continuous (12 fps)") },
        {  15, N_("Continuous (15 fps)") },
        {  20, N_("Continuous (20 fps)") },
        {  30, N_("Continuous (30 fps)") },
        {  40, N_("Continuous (40 fps)") },
        {  60, N_("Continuous (60 fps)") },
        { 240, N_("Auto-N")              }
    }
Drive Mode, tag 0x3103.
casio2Enhancement
const TagDetails Exiv2::Internal::casio2Enhancement[] extern
Initial value:
= {
        { 0, N_("Off")         },
        { 1, N_("Scenery")     },
        { 3, N_("Green")       },
        { 5, N_("Unterwater")  },
        { 9, N_("Flesh Tones") }
    }
Enhancement, tag 0x3016.
casio2FocusMode
const TagDetails Exiv2::Internal::casio2FocusMode[] extern
Initial value:
= {
        { 0, N_("Normal") },
        { 1, N_("Macro") }
    }
Focus Mode, tag 0x000d.
casio2FocusMode2
const TagDetails Exiv2::Internal::casio2FocusMode2[] extern
Initial value:
= {
        { 0, N_("Manual")                 },
        { 1, N_("Focus Lock")             },
        { 2, N_("Macro")                  },
        { 3, N_("Single-Area Auto Focus") },
        { 5, N_("Infinity")               },
        { 6, N_("Multi-Area Auto Focus")  },
        { 8, N_("Super Macro")            }
    }
Focus Mode 2, tag 0x3003.
casio2ImageSize
const TagDetails Exiv2::Internal::casio2ImageSize[] extern
Initial value:
= {
        {  0, "640x480"   },
        {  4, "1600x1200" },
        {  5, "2048x1536" },
        { 20, "2288x1712" },
        { 21, "2592x1944" },
        { 22, "2304x1728" },
        { 36, "3008x2008" }
    }
Image Size, tag 0x0009.
casio2IsoSpeed
const TagDetails Exiv2::Internal::casio2IsoSpeed[] extern
Initial value:
= {
        { 3, "50"  },
        { 4, "64"  },
        { 6, "100" },
        { 9, "200" }
    }
ISO Speed, tag 0x0014.
casio2LightingMode
const TagDetails Exiv2::Internal::casio2LightingMode[] extern
Initial value:
= {
        { 0, N_("Off")                 },
        { 1, N_("High Dynamic Range")  },
        { 5, N_("Shadow Enhance Low")  },
        { 6, N_("Shadow Enhance High") }
    }
Lighting Mode, tag 0x302a.
casio2PortraitRefiner
const TagDetails Exiv2::Internal::casio2PortraitRefiner[] extern
Initial value:
= {
        { 0, N_("Off") },
        { 1, N_("+1")  },
        { 2, N_("+2")  }
    }
Portrait Refiner, tag 0x302b.
casio2Quality
const TagDetails Exiv2::Internal::casio2Quality[] extern
Initial value:
= {
        { 1, N_("Economy") },
        { 2, N_("Normal")  },
        { 3, N_("Fine")    }
    }
Quality, tag 0x3002.
casio2QualityMode
const TagDetails Exiv2::Internal::casio2QualityMode[] extern
Initial value:
= {
        { 0, N_("Economy") },
        { 1, N_("Normal")  },
        { 2, N_("Fine")    }
    }
Quality Mode, tag 0x0004.
casio2ReleaseMode
const TagDetails Exiv2::Internal::casio2ReleaseMode[] extern
Initial value:
= {
        {  1, N_("Normal")              },
        {  3, N_("AE Bracketing")       },
        { 11, N_("WB Bracketing")       },
        { 13, N_("Contrast Bracketing") },
        { 19, N_("High Speed Burst")    }
    }
Release Mode, tag 0x3001.
casio2Saturation
const TagDetails Exiv2::Internal::casio2Saturation[] extern
Initial value:
= {
        { 0, N_("Low")    },
        { 1, N_("Normal") },
        { 2, N_("High")   }
    }
Saturation, tag 0x001f.
casio2Sharpness
const TagDetails Exiv2::Internal::casio2Sharpness[] extern
Initial value:
= {
        { 0, N_("Soft")    },
        { 1, N_("Normal") },
        { 2, N_("Hard")   }
    }
Sharpness, tag 0x0021.
casio2SpecialEffectSetting
const TagDetails Exiv2::Internal::casio2SpecialEffectSetting[] extern
Initial value:
= {
        {  0, N_("Off")             },
        {  1, N_("Makeup")          },
        {  2, N_("Mist Removal")    },
        {  3, N_("Vivid Landscape") },
        { 16, N_("Art Shot")        }
    }
Special Effect Setting, tag 0x3031.
casio2VideoQuality
const TagDetails Exiv2::Internal::casio2VideoQuality[] extern
Initial value:
= {
        { 1, N_("Standard")        },
        { 3, N_("HD (720p)")       },
        { 4, N_("Full HD (1080p)") },
        { 5, N_("Low")             }
    }
Video Quality, tag 0x4003.
casio2WhiteBalance
const TagDetails Exiv2::Internal::casio2WhiteBalance[] extern
Initial value:
= {
        { 0, N_("Auto")        },
        { 1, N_("Daylight")    },
        { 2, N_("Shade")       },
        { 3, N_("Tungsten")    },
        { 4, N_("Fluorescent") },
        { 5, N_("Manual")      }
    }
White Balance, tag 0x0019.
casio2WhiteBalance2
const TagDetails Exiv2::Internal::casio2WhiteBalance2[] extern
Initial value:
= {
        {  0, N_("Manual")      },
        {  1, N_("Daylight")    },
        {  2, N_("Cloudy")      },
        {  3, N_("Shade")       },
        {  4, N_("Flash")       },
        {  6, N_("Fluorescent") },
        {  9, N_("Tungsten")    },
        { 10, N_("Tungsten")    },
        { 12, N_("Flash")       }
    }
White Balance2, tag 0x2012.
casioCCDSensitivity
const TagDetails Exiv2::Internal::casioCCDSensitivity[] extern
Initial value:
= {
        {  64, N_("Normal")                     },
        { 125, N_("+1.0")                       },
        { 250, N_("+2.0")                       },
        { 244, N_("+3.0")                       },
        {  80, N_("Normal (ISO 80 equivalent)") },
        { 100, N_("High")                       }
    }
CCD Sensitivity intensity, tag 0x0020.
casioColorFilter
const TagDetails Exiv2::Internal::casioColorFilter[] extern
Initial value:
= {
        { 1, N_("Off")           },
        { 2, N_("Black & White") },
        { 3, N_("Sepia")         },
        { 4, N_("Red")           },
        { 5, N_("Green")         },
        { 6, N_("Blue")          },
        { 7, N_("Yellow")        },
        { 8, N_("Pink")          },
        { 9, N_("Purple")        }
    }
Color filter, tag 0x0017.
casioContrast
const TagDetails Exiv2::Internal::casioContrast[] extern
Initial value:
= {
        {  0, N_("Normal") },
        {  1, N_("Low")   },
        {  2, N_("High")   },
        { 16, N_("Normal") },
        { 17, N_("+1")     },
        { 18, N_("-1")     }
    }
Contrast, tag 0x000c.
casioDigitalZoom
const TagDetails Exiv2::Internal::casioDigitalZoom[] extern
Initial value:
= {
        { 0x10000, N_("Off")   },
        { 0x10001, N_("2x")    },
        { 0x13333, N_("1.2x")  },
        { 0x13ae1, N_("1.23x") },
        { 0x19999, N_("1.6x")  },
        { 0x20000, N_("2x")    },
        { 0x33333, N_("3.2x")  },
        { 0x40000, N_("4x")    }
    }
Flash intensity, tag 0x0005.
casioEnhancement
const TagDetails Exiv2::Internal::casioEnhancement[] extern
Initial value:
= {
        { 1, N_("Off")         },
        { 2, N_("Red")         },
        { 3, N_("Green")       },
        { 4, N_("Blue")        },
        { 5, N_("Flesh Tones") }
    }
Enhancement, tag 0x0016.
casioFlashIntensity
const TagDetails Exiv2::Internal::casioFlashIntensity[] extern
Initial value:
= {
        { 11, N_("Weak")   },
        { 12, N_("Low")    },
        { 13, N_("Normal") },
        { 14, N_("High")   },
        { 15, N_("Strong") }
    }
Flash intensity, tag 0x0005.
casioFlashIntensity2
const TagDetails Exiv2::Internal::casioFlashIntensity2[] extern
Initial value:
= {
        { 1, N_("Normal") },
        { 2, N_("Weak")   },
        { 3, N_("Strong") }
    }
flash intensity 2, tag 0x0019
casioFlashMode
const TagDetails Exiv2::Internal::casioFlashMode[] extern
Initial value:
= {
        { 1, N_("Auto")              },
        { 2, N_("On")                },
        { 3, N_("Off")               },
        { 4, N_("Off")               },
        { 5, N_("Red-eye Reduction") }
    }
FlashMode, tag 0x0004.
casioFocusMode
const TagDetails Exiv2::Internal::casioFocusMode[] extern
Initial value:
= {
        { 2, N_("Macro")    },
        { 3, N_("Auto")     },
        { 4, N_("Manual")   },
        { 5, N_("Infinity") },
        { 7, N_("Sport AF") }
    }
Focus Mode, tag 0x0003.
casioQuality
const TagDetails Exiv2::Internal::casioQuality[] extern
Initial value:
= {
        { 1, N_("Economy") },
        { 2, N_("Normal")  },
        { 3, N_("Fine")    }
    }
Quality, tag 0x0002.
casioRecordingMode
const TagDetails Exiv2::Internal::casioRecordingMode[] extern
Initial value:
= {
        {  1, N_("Single Shutter") },
        {  2, N_("Panorama")       },
        {  3, N_("Night Scene")    },
        {  4, N_("Portrait")       },
        {  5, N_("Landscape")      },
        {  7, N_("Panorama")       },
        { 10, N_("Night Scene")    },
        { 15, N_("Portrait")       },
        { 16, N_("Landscape")      }
    }
RecordingMode, tag 0x0001.
casioSaturation
const TagDetails Exiv2::Internal::casioSaturation[] extern
Initial value:
= {
        {  0, N_("Normal") },
        {  1, N_("Low")   },
        {  2, N_("High")   },
        { 16, N_("Normal") },
        { 17, N_("+1")     },
        { 18, N_("-1")     }
    }
Saturation, tag 0x000d.
casioSharpness
const TagDetails Exiv2::Internal::casioSharpness[] extern
Initial value:
= {
        {  0, N_("Normal") },
        {  1, N_("Soft")   },
        {  2, N_("Hard")   },
        { 16, N_("Normal") },
        { 17, N_("+1")     },
        { 18, N_("-1")     }
    }
Sharpness, tag 0x000b.
casioWhiteBalance
const TagDetails Exiv2::Internal::casioWhiteBalance[] extern
Initial value:
= {
        {   1, N_("Auto")        },
        {   2, N_("Tungsten")    },
        {   3, N_("Daylight")    },
        {   4, N_("Fluorescent") },
        {   5, N_("Shade")       },
        { 129, N_("Manual")      }
    }
white balance, tag 0x0007
dngCfaLayout
const TagDetails Exiv2::Internal::dngCfaLayout[] extern
Initial value:
= {
        { 1, N_("Rectangular (or square) layout")                                                   },
        { 2, N_("Staggered layout A: even columns are offset down by 1/2 row")                      },
        { 3, N_("Staggered layout B: even columns are offset up by 1/2 row")                        },
        { 4, N_("Staggered layout C: even rows are offset right by 1/2 column")                     },
        { 5, N_("Staggered layout D: even rows are offset left by 1/2 column")                      },
        { 6, N_("Staggered layout E: even rows are offset up by 1/2, even columns left by 1/2")     },
        { 7, N_("Staggered layout F: even rows are offset up by 1/2, even columns right by 1/2")    },
        { 8, N_("Staggered layout G: even rows are offset down by 1/2, even columns left by 1/2")   },
        { 9, N_("Staggered layout H: even rows are offset down by 1/2, even columns right by 1/2")  }
    }
CFALayout, DNG tag 0xc617.
dngColorimetricReference
const TagDetails Exiv2::Internal::dngColorimetricReference[] extern
Initial value:
= {
        { 0, N_("XYZ values are scene-referred")  },
        { 1, N_("XYZ values are output-referred") }
    }
ColorimetricReference, DNG 1.2 tag 0xc6bf.
dngDefaultBlackRender
const TagDetails Exiv2::Internal::dngDefaultBlackRender[] extern
Initial value:
= {
        { 0, N_("Auto") },
        { 1, N_("None") }
    }
DefaultBlackRender, DNG 1.4 tag 0xc7a6.
dngDepthFormat
const TagDetails Exiv2::Internal::dngDepthFormat[] extern
Initial value:
= {
        { 0, N_("Unknown") },
        { 1, N_("Linear")  },
        { 2, N_("Inverse") }
    }
DepthFormat, DNG 1.5 tag 0xc7e9.
dngDepthMeasureType
const TagDetails Exiv2::Internal::dngDepthMeasureType[] extern
Initial value:
= {
        { 0, N_("Unknown")      },
        { 1, N_("Optical axis") },
        { 2, N_("Optical ray")  }
    }
DepthMeasureType, DNG 1.5 tag 0xc7ed.
dngDepthUnits
const TagDetails Exiv2::Internal::dngDepthUnits[] extern
Initial value:
= {
        { 0, N_("Unknown") },
        { 1, N_("meters")  }
    }
DepthUnits, DNG 1.5 tag 0xc7ec.
dngMakerNoteSafety
const TagDetails Exiv2::Internal::dngMakerNoteSafety[] extern
Initial value:
= {
        { 0, N_("Unsafe") },
        { 1, N_("Safe")   }
    }
MakerNoteSafety, DNG tag 0xc635.
dngPreviewColorSpace
const TagDetails Exiv2::Internal::dngPreviewColorSpace[] extern
Initial value:
= {
        { 0, N_("Unknown")        },
        { 1, N_("Gray Gamma 2.2") },
        { 2, N_("sRGB")           },
        { 2, N_("Adobe RGB")      },
        { 4, N_("ProPhoto RGB")   }
    }
PreviewColorSpace, DNG 1.2 tag 0xc71a.
dngProfileEmbedPolicy
const TagDetails Exiv2::Internal::dngProfileEmbedPolicy[] extern
Initial value:
= {
        { 0, N_("Allow copying")   },
        { 1, N_("Embed if used")   },
        { 2, N_("Embed never")     },
        { 3, N_("No restrictions") }
    }
ProfileEmbedPolicy, DNG 1.2 tag 0xc6fd.
dngProfileEncoding
const TagDetails Exiv2::Internal::dngProfileEncoding[] extern
Initial value:
= {
        { 0, N_("Linear") },
        { 1, N_("sRGB")   }
    }
ProfileEncoding, DNG 1.4 tags 0xc7a3, 0xc7a4.
exifColorSpace
const TagDetails Exiv2::Internal::exifColorSpace[] extern
Initial value:
= {
        {      1, N_("sRGB")         },
        {      2, N_("Adobe RGB")    },
        { 0xffff, N_("Uncalibrated") }
    }
ColorSpace, tag 0xa001.
Referenced by print0xa001().
exifCompositeImage
const TagDetails Exiv2::Internal::exifCompositeImage[] extern
Initial value:
= {
        { 0, N_("Unknown") },
        { 1, N_("NonComposite")   },
        { 2, N_("GeneralComposite")   },
        { 3, N_("CompositeCapturedWhenShooting")   }
    }
CompositeImage, tag 0xa460.
exifCustomRendered
const TagDetails Exiv2::Internal::exifCustomRendered[] extern
Initial value:
= {
        { 0, N_("Normal process") },
        { 1, N_("Custom process") }
    }
CustomRendered, tag 0xa401.
Referenced by print0xa401().
exifExposureMode
const TagDetails Exiv2::Internal::exifExposureMode[] extern
Initial value:
= {
        { 0, N_("Auto")         },
        { 1, N_("Manual")       },
        { 2, N_("Auto bracket") }
    }
ExposureMode, tag 0xa402.
Referenced by print0xa402().
exifExposureProgram
const TagDetails Exiv2::Internal::exifExposureProgram[] extern
Initial value:
= {
        { 0, N_("Not defined")       },
        { 1, N_("Manual")            },
        { 2, N_("Auto")              },
        { 3, N_("Aperture priority") },
        { 4, N_("Shutter priority")  },
        { 5, N_("Creative program")  },
        { 6, N_("Action program")    },
        { 7, N_("Portrait mode")     },
        { 8, N_("Landscape mode")    }
    }
ExposureProgram, tag 0x8822.
Referenced by print0x8822().
exifFileSource
const TagDetails Exiv2::Internal::exifFileSource[] extern
Initial value:
= {
        { 1, N_("Film scanner")            },
        { 2, N_("Reflexion print scanner") },
        { 3, N_("Digital still camera")    }
    }
FileSource, tag 0xa300.
Referenced by print0xa300().
exifFlash
const TagDetails Exiv2::Internal::exifFlash[] extern
Initial value:
= {
        { 0x00, N_("No flash")                                                      },
        { 0x01, N_("Fired")                                                         },
        { 0x05, N_("Fired, return light not detected")                              },
        { 0x07, N_("Fired, return light detected")                                  },
        { 0x08, N_("Yes, did not fire")                                             },
        { 0x09, N_("Yes, compulsory")                                               },
        { 0x0d, N_("Yes, compulsory, return light not detected")                    },
        { 0x0f, N_("Yes, compulsory, return light detected")                        },
        { 0x10, N_("No, compulsory")                                                },
        { 0x14, N_("No, did not fire, return light not detected")                   },
        { 0x18, N_("No, auto")                                                      },
        { 0x19, N_("Yes, auto")                                                     },
        { 0x1d, N_("Yes, auto, return light not detected")                          },
        { 0x1f, N_("Yes, auto, return light detected")                              },
        { 0x20, N_("No flash function")                                             },
        { 0x20, N_("No, no flash function")                                         },
        { 0x41, N_("Yes, red-eye reduction")                                        },
        { 0x45, N_("Yes, red-eye reduction, return light not detected")             },
        { 0x47, N_("Yes, red-eye reduction, return light detected")                 },
        { 0x49, N_("Yes, compulsory, red-eye reduction")                            },
        { 0x4d, N_("Yes, compulsory, red-eye reduction, return light not detected") },
        { 0x4f, N_("Yes, compulsory, red-eye reduction, return light detected")     },
        { 0x50, N_("No, red-eye reduction")                                         },
        { 0x58, N_("No, auto, red-eye reduction")                                   },
        { 0x59, N_("Yes, auto, red-eye reduction")                                  },
        { 0x5d, N_("Yes, auto, red-eye reduction, return light not detected")       },
        { 0x5f, N_("Yes, auto, red-eye reduction, return light detected")           }
    }
Flash, Exif tag 0x9209.
exifGainControl
const TagDetails Exiv2::Internal::exifGainControl[] extern
Initial value:
= {
        { 0, N_("None")           },
        { 1, N_("Low gain up")    },
        { 2, N_("High gain up")   },
        { 3, N_("Low gain down")  },
        { 4, N_("High gain down") }
    }
GainControl, tag 0xa407.
Referenced by print0xa407().
exifGPSAltitudeRef
const TagDetails Exiv2::Internal::exifGPSAltitudeRef[] extern
Initial value:
= {
        { 0, N_("Above sea level") },
        { 1, N_("Below sea level") }
    }
GPS altitude reference, tag 0x0005.
Referenced by print0x0005().
exifGPSDestDistanceRef
const TagDetails Exiv2::Internal::exifGPSDestDistanceRef[] extern
Initial value:
= {
        { 'K', N_("Kilometers") },
        { 'M', N_("Miles")      },
        { 'N', N_("Knots")      }
    }
GPS Destination distance ref, tag 0x0019.
Referenced by print0x0019().
exifGPSDifferential
const TagDetails Exiv2::Internal::exifGPSDifferential[] extern
Initial value:
= {
        { 0, N_("Without correction") },
        { 1, N_("Correction applied") }
    }
GPS Differential, tag 0x001e.
Referenced by print0x001e().
exifGPSDirRef
const TagDetails Exiv2::Internal::exifGPSDirRef[] extern
Initial value:
= {
        { 'T', N_("True direction")     },
        { 'M', N_("Magnetic direction") }
    }
GPS direction ref, tags 0x000e, 0x0010, 0x0017.
Referenced by printGPSDirRef().
exifGPSLatitudeRef
const TagDetails Exiv2::Internal::exifGPSLatitudeRef[] extern
Initial value:
= {
        { 78, N_("North") },
        { 83, N_("South") }
    }
GPS latitude reference, tag 0x0001; also GPSDestLatitudeRef, tag 0x0013.
exifGPSLongitudeRef
const TagDetails Exiv2::Internal::exifGPSLongitudeRef[] extern
Initial value:
= {
        { 69, N_("East") },
        { 87, N_("West") }
    }
GPS longitude reference, tag 0x0003; also GPSDestLongitudeRef, tag 0x0015.
exifGPSMeasureMode
const TagDetails Exiv2::Internal::exifGPSMeasureMode[] extern
Initial value:
= {
        { '2', N_("Two-dimensional measurement")   },
        { '3', N_("Three-dimensional measurement") }
    }
GPS measurement mode, tag 0x000a.
Referenced by print0x000a().
exifGPSSpeedRef
const TagDetails Exiv2::Internal::exifGPSSpeedRef[] extern
Initial value:
= {
        { 'K', N_("km/h")  },
        { 'M', N_("mph")   },
        { 'N', N_("knots") }
    }
GPS speed reference, tag 0x000c.
Referenced by print0x000c().
exifGPSStatus
const TagDetails Exiv2::Internal::exifGPSStatus[] extern
Initial value:
= {
        { 'A', N_("Measurement in progress")      },
        { 'V', N_("Measurement Interoperability") }
    }
GPS status, tag 0x0009.
Referenced by print0x0009().
exifIndexed
const TagDetails Exiv2::Internal::exifIndexed[] extern
Initial value:
= {
        { 0, N_("Not indexed") },
        { 1, N_("Indexed")     }
    }
Indexed, tag 0x015a.
exifInkSet
const TagDetails Exiv2::Internal::exifInkSet[] extern
Initial value:
= {
        { 1, N_("CMYK")     },
        { 2, N_("not CMYK") }
    }
InkSet, tag 0x014c.
exifJpegLosslessPredictor
const TagDetails Exiv2::Internal::exifJpegLosslessPredictor[] extern
Initial value:
= {
        { 1, N_("A")           },
        { 2, N_("B")           },
        { 3, N_("C")           },
        { 4, N_("A+B-C")       },
        { 5, N_("A+((B-C)/2)") },
        { 6, N_("B+((A-C)/2)") },
        { 7, N_("(A+B)/2")     }
    }
exifJpegLosslessPredictor, tag 0x0205
exifLightSource
const TagDetails Exiv2::Internal::exifLightSource[] extern
Initial value:
= {
        {   0, N_("Unknown")                                 },
        {   1, N_("Daylight")                                },
        {   2, N_("Fluorescent")                             },
        {   3, N_("Tungsten (incandescent light)")           },
        {   4, N_("Flash")                                   },
        {   9, N_("Fine weather")                            },
        {  10, N_("Cloudy weather")                          },
        {  11, N_("Shade")                                   },
        {  12, N_("Daylight fluorescent (D 5700 - 7100K)")   },
        {  13, N_("Day white fluorescent (N 4600 - 5400K)")  },
        {  14, N_("Cool white fluorescent (W 3900 - 4500K)") },
        {  15, N_("White fluorescent (WW 3200 - 3700K)")     },
        {  17, N_("Standard light A")                        },
        {  18, N_("Standard light B")                        },
        {  19, N_("Standard light C")                        },
        {  20, N_("D55")                                     },
        {  21, N_("D65")                                     },
        {  22, N_("D75")                                     },
        {  23, N_("D50")                                     },
        {  24, N_("ISO studio tungsten")                     },
        { 255, N_("Other light source")                      }
    }
LightSource, tag 0x9208.
Referenced by print0x9208().
exifMeteringMode
const TagDetails Exiv2::Internal::exifMeteringMode[] extern
Initial value:
= {
        { 0,   N_("Unknown")                 },
        { 1,   N_("Average")                 },
        { 2,   N_("Center weighted average") },
        { 3,   N_("Spot")                    },
        { 4,   N_("Multi-spot")              },
        { 5,   N_("Multi-segment")           },
        { 6,   N_("Partial")                 },
        { 255, N_("Other")                   },
        { 255, N_("Other")                   }
    }
MeteringMode, tag 0x9207.
Referenced by print0x9207().
exifNewSubfileType
const TagDetails Exiv2::Internal::exifNewSubfileType[] extern
Initial value:
= {
        {     0, N_("Primary image")                                               },
        {     1, N_("Thumbnail/Preview image")                                     },
        {     2, N_("Primary image, Multi page file")                              },
        {     3, N_("Thumbnail/Preview image, Multi page file")                    },
        {     4, N_("Primary image, Transparency mask")                            },
        {     5, N_("Thumbnail/Preview image, Transparency mask")                  },
        {     6, N_("Primary image, Multi page file, Transparency mask")           },
        {     7, N_("Thumbnail/Preview image, Multi page file, Transparency mask") },
        {     8, N_("Primary image, Depth map")                                    },
        {     9, N_("Thumbnail/Preview image, Depth map")                          },
        {    16, N_("Enhanced image")                                              },
        { 65537, N_("Thumbnail/Preview image, Alternative")                        },
        { 65540, N_("Primary image, Semantic mask")                                }
    }
NewSubfileType, TIFF tag 0x00fe - this is actually a bitmask.
exifNormalSoftHard
const TagDetails Exiv2::Internal::exifNormalSoftHard[] extern
Initial value:
= {
        { 0, N_("Normal") },
        { 1, N_("Soft")   },
        { 2, N_("Hard")   }
    }
Contrast, tag 0xa408 and Sharpness, tag 0xa40a.
Referenced by printNormalSoftHard().
exifOrientation
const TagDetails Exiv2::Internal::exifOrientation[] extern
Initial value:
= {
        { 1, N_("top, left")     },
        { 2, N_("top, right")    },
        { 3, N_("bottom, right") },
        { 4, N_("bottom, left")  },
        { 5, N_("left, top")     },
        { 6, N_("right, top")    },
        { 7, N_("right, bottom") },
        { 8, N_("left, bottom")  },
        { 8, N_("left, bottom")  }
    }
Orientation, tag 0x0112.
Referenced by print0x0112().
exifPhotometricInterpretation
const TagDetails Exiv2::Internal::exifPhotometricInterpretation[] extern
Initial value:
= {
        {     0, N_("White Is Zero")      },
        {     1, N_("Black Is Zero")      },
        {     2, N_("RGB")                },
        {     3, N_("RGB Palette")        },
        {     4, N_("Transparency Mask")  },
        {     5, N_("CMYK")               },
        {     6, N_("YCbCr")              },
        {     8, N_("CIELab")             },
        {     9, N_("ICCLab")             },
        {    10, N_("ITULab")             },
        { 32803, N_("Color Filter Array") },
        { 32844, N_("Pixar LogL")         },
        { 32845, N_("Pixar LogLuv")       },
        { 34892, N_("Linear Raw")         },
        { 51177, N_("Depth Map")          },
        { 52527, N_("Semantic Mask")      }
    }
PhotometricInterpretation, tag 0x0106.
exifPlanarConfiguration
const TagDetails Exiv2::Internal::exifPlanarConfiguration[] extern
Initial value:
= {
        { 1, N_("Chunky") },
        { 2, N_("Planar") }
    }
PlanarConfiguration, tag 0x011c.
exifPredictor
const TagDetails Exiv2::Internal::exifPredictor[] extern
Initial value:
= {
        {     1, N_("No prediction scheme used")              },
        {     2, N_("Horizontal differencing")                },
        {     3, N_("Floating point horizontal differencing") },
        { 34892, N_("Horizontal difference X2")               },
        { 34893, N_("Horizontal difference X4")               },
        { 34894, N_("Floating point X2")                      },
        { 34895, N_("Floating point X4")                      }
    }
Predictor, tag 0x013d.
exifSampleFormat
const TagDetails Exiv2::Internal::exifSampleFormat[] extern
Initial value:
= {
        { 1, N_("Unsigned integer data")                },
        { 2, N_("Two's complement signed integer data") },
        { 3, N_("IEEE floating point data")             },
        { 4, N_("Undefined data format")                },
        { 4, N_("Undefined data format")                }
    }
SampleFormat, tag 0x0153.
exifSaturation
const TagDetails Exiv2::Internal::exifSaturation[] extern
Initial value:
= {
        { 0, N_("Normal") },
        { 1, N_("Low")    },
        { 2, N_("High")   }
    }
Saturation, tag 0xa409.
Referenced by print0xa409().
exifSceneCaptureType
const TagDetails Exiv2::Internal::exifSceneCaptureType[] extern
Initial value:
= {
        { 0, N_("Standard")    },
        { 1, N_("Landscape")   },
        { 2, N_("Portrait")    },
        { 3, N_("Night scene") },
        { 3, N_("Night scene") }
    }
SceneCaptureType, tag 0xa406.
Referenced by print0xa406().
exifSceneType
const TagDetails Exiv2::Internal::exifSceneType[] extern
Initial value:
= {
        { 1, N_("Directly photographed") }
    }
SceneType, tag 0xa301.
Referenced by print0xa301().
exifSensingMethod
const TagDetails Exiv2::Internal::exifSensingMethod[] extern
Initial value:
= {
        { 1, N_("Not defined")             },
        { 2, N_("One-chip color area")     },
        { 3, N_("Two-chip color area")     },
        { 4, N_("Three-chip color area")   },
        { 5, N_("Color sequential area")   },
        { 7, N_("Trilinear sensor")        },
        { 8, N_("Color sequential linear") }
    }
SensingMethod, tag 0xa217.
Referenced by print0xa217().
exifSubfileType
const TagDetails Exiv2::Internal::exifSubfileType[] extern
Initial value:
= {
        {  1, N_("Full-resolution image data")                                  },
        {  2, N_("Reduced-resolution image data")                               },
        {  3, N_("A single page of a multi-page image")                         }
    }
SubfileType, TIFF tag 0x00ff.
exifSubjectDistanceRange
const TagDetails Exiv2::Internal::exifSubjectDistanceRange[] extern
Initial value:
= {
        { 0, N_("Unknown")      },
        { 1, N_("Macro")        },
        { 2, N_("Close view")   },
        { 3, N_("Distant view") },
        { 3, N_("Distant view") }
    }
SubjectDistanceRange, tag 0xa40c.
Referenced by print0xa40c().
exifThresholding
const TagDetails Exiv2::Internal::exifThresholding[] extern
Initial value:
= {
        { 1, N_("No dithering or halftoning")           },
        { 2, N_("Ordered dither or halftone technique") },
        { 3, N_("Randomized process")                   }
    }
Thresholding, tag 0x0107.
exifUnit
const TagDetails Exiv2::Internal::exifUnit[] extern
Initial value:
= {
        { 1, N_("none") },
        { 2, N_("inch") },
        { 3, N_("cm")   }
    }
Units for measuring X and Y resolution, tags 0x0128, 0xa210.
Referenced by printExifUnit().
exifWhiteBalance
const TagDetails Exiv2::Internal::exifWhiteBalance[] extern
Initial value:
= {
        { 0, N_("Auto")   },
        { 1, N_("Manual") }
    }
WhiteBalance, tag 0xa403.
Referenced by print0xa403().
exifYCbCrPositioning
const TagDetails Exiv2::Internal::exifYCbCrPositioning[] extern
Initial value:
= {
        { 1, N_("Centered") },
        { 2, N_("Co-sited") }
    }
YCbCrPositioning, tag 0x0213.
Referenced by print0x0213().
fujiColor
const TagDetails Exiv2::Internal::fujiColor[] extern
Initial value:
= {
        {   0, N_("Normal")                 },
        { 256, N_("High")                   },
        { 512, N_("Low")                    },
        { 768, N_("Monochrome")             },
        { 769, N_("Monochrome + R Filter")  },
        { 770, N_("Monochrome + Ye Filter") },
        { 771, N_("Monochrome + G Filter")  },
        { 784, N_("Sepia")                  },
        { 768, N_("Monochrome")             }
    }
Color, tag 0x1003.
fujiContinuous
const TagDetails Exiv2::Internal::fujiContinuous[] extern
Initial value:
= {
        { 0, N_("Off")              },
        { 1, N_("On")               },
        { 2, N_("No flash & flash") }
    }
Continuous, tag 0x1100.
fujiCropMode
const TagDetails Exiv2::Internal::fujiCropMode[] extern
Initial value:
= {
        { 0, N_("None")                          },
        { 1, N_("Full frame")                    },
        { 2, N_("Sports Finder Mode")            },
        { 4, N_("Electronic Shutter 1.25x Crop") },
    }
CropMode, tag 0x104d.
fujiDRangePriority
const TagDetails Exiv2::Internal::fujiDRangePriority[] extern
Initial value:
= {
        {     0, N_("Auto")  },
        {     1, N_("Fixed") }
    }
DRangePriority, tag 0x1443.
fujiDRangePriorityAuto
const TagDetails Exiv2::Internal::fujiDRangePriorityAuto[] extern
Initial value:
= {
        {     1, N_("Weak")  },
        {     2, N_("Strong") }
    }
DRangePriorityAuto, tag 0x1444.
fujiDRangePriorityFixed
const TagDetails Exiv2::Internal::fujiDRangePriorityFixed[] extern
Initial value:
= {
        {     1, N_("Weak")  },
        {     2, N_("Strong") }
    }
DRangePriorityFixed, tag 0x1445.
fujiDynamicRange
const TagDetails Exiv2::Internal::fujiDynamicRange[] extern
Initial value:
= {
        { 1, N_("Standard") },
        { 3, N_("Wide")     }
    }
DynamicRange, tag 0x1400.
fujiDynamicRangeSetting
const TagDetails Exiv2::Internal::fujiDynamicRangeSetting[] extern
Initial value:
= {
        {     0, N_("Auto (100-400%)")      },
        {     1, N_("Raw")                  },
        {   256, N_("Standard (100%)")      },
        {   512, N_("Wide mode 1 (230%)")   },
        {   513, N_("Wide mode 2 (400%)")   },
        { 32768, N_("Film simulation mode") }
    }
DynamicRange, tag 0x1402.
fujiFilmMode
const TagDetails Exiv2::Internal::fujiFilmMode[] extern
Initial value:
= {
        {    0, N_("F0/Standard (Provia)")                         },
        {  256, N_("F1/Studio Portrait")                           },
        {  272, N_("F1a/Studio Portrait Enhanced Saturation")      },
        {  288, N_("F1b/Studio Portrait Smooth Skin Tone (Astia)") },
        {  304, N_("F1c/Studio Portrait Increased Sharpness")      },
        {  512, N_("F2/Fujichrome (Velvia)")                       },
        {  768, N_("F3/Studio Portrait Ex")                        },
        { 1024, N_("F4/Velvia")                                    },
        { 1280, N_("Pro Neg. Std")                                 },
        { 1281, N_("Pro Neg. Hi")                                  },
        { 1536, N_("Classic Chrome")                               },
    }
FilmMode, tag 0x1401.
fujiFinePixColor
const TagDetails Exiv2::Internal::fujiFinePixColor[] extern
Initial value:
= {
        { 0,  N_("Standard")      },
        { 16, N_("Chrome")        },
        { 48, N_("Black & white") }
    }
FinePixColor, tag 0x1210.
fujiFlashMode
const TagDetails Exiv2::Internal::fujiFlashMode[] extern
Initial value:
= {
        {  0, N_("Auto")              },
        {  1, N_("On")                },
        {  2, N_("Off")               },
        {  3, N_("Red-eye reduction") },
        {  4, N_("External")          },
        { 16, N_("Commander")         },
        { 16, N_("Commander")         }
    }
FlashMode, tag 0x1010.
fujiFocusMode
const TagDetails Exiv2::Internal::fujiFocusMode[] extern
Initial value:
= {
        { 0, N_("Auto")   },
        { 1, N_("Manual") }
    }
FocusMode, tag 0x1021.
fujiOffOn
const TagDetails Exiv2::Internal::fujiOffOn[] extern
Initial value:
= {
        { 0, N_("Off") },
        { 1, N_("On")  }
    }
OffOn, multiple tags.
fujiPictureMode
const TagDetails Exiv2::Internal::fujiPictureMode[] extern
Initial value:
= {
        {   0, N_("Auto")                      },
        {   1, N_("Portrait")                  },
        {   2, N_("Landscape")                 },
        {   4, N_("Sports")                    },
        {   5, N_("Night scene")               },
        {   6, N_("Program AE")                },
        {   7, N_("Natural light")             },
        {   8, N_("Anti-blur")                 },
        {  10, N_("Sunset")                    },
        {  11, N_("Museum")                    },
        {  12, N_("Party")                     },
        {  13, N_("Flower")                    },
        {  14, N_("Text")                      },
        {  15, N_("Natural light & flash")     },
        {  16, N_("Beach")                     },
        {  17, N_("Snow")                      },
        {  18, N_("Fireworks")                 },
        {  19, N_("Underwater")                },
        { 256, N_("Aperture-priority AE")      },
        { 512, N_("Shutter speed priority AE") },
        { 768, N_("Manual")                    }
    }
PictureMode, tag 0x1031.
fujiSharpness
const TagDetails Exiv2::Internal::fujiSharpness[] extern
Initial value:
= {
        { 1, N_("Soft mode 1") },
        { 2, N_("Soft mode 2") },
        { 3, N_("Normal")      },
        { 4, N_("Hard mode 1") },
        { 5, N_("Hard mode 2") }
    }
Sharpness, tag 0x1001.
fujiSHTone
const TagDetails Exiv2::Internal::fujiSHTone[] extern
Initial value:
= {
        { -64, N_("+4") },
        { -48, N_("+3") },
        { -32, N_("+2") },
        { -16, N_("+1") },
        {   0 , N_("0") },
        {  16, N_("-1") },
        {  32, N_("-2") },
    }
ShadowTone, tag 0x1040 HighlightTone, tag 0x041.
fujiTone
const TagDetails Exiv2::Internal::fujiTone[] extern
Initial value:
= {
        {   0, N_("Normal") },
        { 256, N_("High")   },
        { 512, N_("Low")    }
    }
Tone, tag 0x1004.
fujiWhiteBalance
const TagDetails Exiv2::Internal::fujiWhiteBalance[] extern
Initial value:
= {
        {    0, N_("Auto")                     },
        {  256, N_("Daylight")                 },
        {  512, N_("Cloudy")                   },
        {  768, N_("Fluorescent (daylight)")   },
        {  769, N_("Fluorescent (warm white)") },
        {  770, N_("Fluorescent (cool white)") },
        { 1024, N_("Incandescent")             },
        { 3480, N_("Custom")                   },
        { 3480, N_("Custom")                   }
    }
WhiteBalance, tag 0x1002.
lensIdFct
const LensIdFct Exiv2::Internal::lensIdFct
List of lens ids which require special treatment with the medicine.
List of lens ids which require special treatment using resolveLensType.
List of lens ids which require special treatment from printMinoltaSonyLensID.
Referenced by Exiv2::Internal::CanonMakerNote::printCsLensType(), printLensType(), and printMinoltaSonyLensID().
minoCs5Cfg
const ArrayCfg Exiv2::Internal::minoCs5Cfg extern
Initial value:
= {
        minoltaCs5DId,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Minolta 5D Camera Settings binary array - configuration.
minoCs5Def
const ArrayDef Exiv2::Internal::minoCs5Def[] extern
Initial value:
= {
        { 146, ttSignedShort, 1 }
    }
Minolta 5D Camera Settings binary array - definition.
minoCs7Cfg
const ArrayCfg Exiv2::Internal::minoCs7Cfg extern
Initial value:
= {
        minoltaCs7DId,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Minolta 7D Camera Settings binary array - configuration.
minoCs7Def
const ArrayDef Exiv2::Internal::minoCs7Def[] extern
Initial value:
= {
        {  60, ttSignedShort, 1 },
        { 126, ttSignedShort, 1 }
    }
Minolta 7D Camera Settings binary array - definition.
minoCsnCfg
const ArrayCfg Exiv2::Internal::minoCsnCfg extern
Initial value:
= {
        minoltaCsNewId,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedLong, 1 }
    }
Minolta Camera Settings (new) binary array - configuration.
minoCsoCfg
const ArrayCfg Exiv2::Internal::minoCsoCfg extern
Initial value:
= {
        minoltaCsOldId,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedLong, 1 }
    }
Minolta Camera Settings (old) binary array - configuration.
minoltaAFMode5D
const TagDetails Exiv2::Internal::minoltaAFMode5D[] extern
Initial value:
= {
        { 0, "AF-A" },
        { 1, "AF-S" },
        { 2, "AF-D" },
        { 3, "DMF"  }
    }
Lookup table to translate Minolta Dynax 5D camera settings focus mode values to readable labels.
minoltaAFPoints7D
const TagDetails Exiv2::Internal::minoltaAFPoints7D[] extern
Initial value:
= {
        { 1,   N_("Center")       },
        { 2,   N_("Top")          },
        { 4,   N_("Top-right")    },
        { 8,   N_("Right")        },
        { 16,  N_("Bottom-right") },
        { 32,  N_("Bottom")       },
        { 64,  N_("Bottom-left")  },
        { 128, N_("Left")         },
        { 256, N_("Top-left")     }
    }
Lookup table to translate Minolta Dynax 7D camera settings AF points values to readable labels.
minoltaAFPointsStd
const TagDetails Exiv2::Internal::minoltaAFPointsStd[] extern
Initial value:
= {
        { 0, N_("Center")       },
        { 1, N_("Top")          },
        { 2, N_("Top-right")    },
        { 3, N_("Right")        },
        { 4, N_("Bottom-right") },
        { 5, N_("Bottom")       },
        { 6, N_("Bottom-left")  },
        { 7, N_("Left")         },
        { 8, N_("Top-left")     }
    }
Lookup table to translate Minolta Std camera settings AF points values to readable labels.
minoltaBracketStepStd
const TagDetails Exiv2::Internal::minoltaBracketStepStd[] extern
Initial value:
= {
        { 0, "1/3 EV" },
        { 1, "2/3 EV" },
        { 2, "1 EV"   }
    }
Lookup table to translate Minolta Std camera bracket step mode values to readable labels.
minoltaColorMode
const TagDetails Exiv2::Internal::minoltaColorMode[] extern
Initial value:
= {
        { 0,  N_("Natural Color")  },
        { 1,  N_("Black & White")  },
        { 2,  N_("Vivid Color")    },
        { 3,  N_("Solarization")   },
        { 4,  N_("AdobeRGB")       },
        { 5,  N_("Sepia")          },
        { 9,  N_("Natural")        },
        { 12, N_("Portrait")       },
        { 13, N_("Natural sRGB")   },
        { 14, N_("Natural+ sRGB")  },
        { 15, N_("Landscape")      },
        { 16, N_("Evening")        },
        { 17, N_("Night Scene")    },
        { 18, N_("Night Portrait") }
    }
Lookup table to translate Minolta color mode values to readable labels.
minoltaColorModeStd
const TagDetails Exiv2::Internal::minoltaColorModeStd[] extern
Initial value:
= {
        { 0, N_("Natural color")   },
        { 1, N_("Black and white") },
        { 2, N_("Vivid color")     },
        { 3, N_("Solarization")    },
        { 4, N_("Adobe RGB")       }
    }
Lookup table to translate Minolta Std camera settings color mode values to readable labels.
minoltaColorProfileStd
const TagDetails Exiv2::Internal::minoltaColorProfileStd[] extern
Initial value:
= {
        { 0, N_("Not embedded") },
        { 1, N_("Embedded")     }
    }
Lookup table to translate Minolta Std camera settings color profile values to readable labels.
minoltaColorSpace5D
const TagDetails Exiv2::Internal::minoltaColorSpace5D[] extern
Initial value:
= {
        { 0, N_("sRGB (Natural)")  },
        { 1, N_("sRGB (Natural+)") },
        { 2, N_("Monochrome")      },
        { 3, N_("Adobe RGB (ICC)") },
        { 4, N_("Adobe RGB")       }
    }
Lookup table to translate Minolta Dynax 5D camera settings color space values to readable labels.
minoltaColorSpace7D
const TagDetails Exiv2::Internal::minoltaColorSpace7D[] extern
Initial value:
= {
        { 0, N_("sRGB (Natural)")  },
        { 1, N_("sRGB (Natural+)") },
        { 4, N_("Adobe RGB")       }
    }
Lookup table to translate Minolta Dynax 7D camera settings color space values to readable labels.
minoltaDataImprintStd
const TagDetails Exiv2::Internal::minoltaDataImprintStd[] extern
Initial value:
= {
        { 0, N_("None")       },
        { 1, "YYYY/MM/DD"     },
        { 2, "MM/DD/HH:MM"    },
        { 3, N_("Text")       },
        { 4, N_("Text + ID#") }
    }
Lookup table to translate Minolta Std camera settings data Imprint values to readable labels.
minoltaDECPositionStd
const TagDetails Exiv2::Internal::minoltaDECPositionStd[] extern
Initial value:
= {
        { 0, N_("Exposure")   },
        { 1, N_("Contrast")   },
        { 2, N_("Saturation") },
        { 3, N_("Filter")     }
    }
Lookup table to translate Minolta Std camera settings DEC switch position values to readable labels.
minoltaDigitalZoomStd
const TagDetails Exiv2::Internal::minoltaDigitalZoomStd[] extern
Initial value:
= {
        { 0, N_("Off")                      },
        { 1, N_("Electronic magnification") },
        { 2, "2x"                           }
    }
Lookup table to translate Minolta Std camera settings digital zoom values to readable labels.
minoltaDriveModeStd
const TagDetails Exiv2::Internal::minoltaDriveModeStd[] extern
Initial value:
= {
        { 0, N_("Single Frame")   },
        { 1, N_("Continuous")     },
        { 2, N_("Self-timer")     },
        { 4, N_("Bracketing")     },
        { 5, N_("Interval")       },
        { 6, N_("UHS continuous") },
        { 7, N_("HS continuous")  }
    }
Lookup table to translate Minolta Std camera settings drive mode values to readable labels.
minoltaExposureMode5D
const TagDetails Exiv2::Internal::minoltaExposureMode5D[] extern
Initial value:
= {
        { 0,      N_("Program")             },
        { 1,      N_("Aperture priority")   },
        { 2,      N_("Shutter priority")    },
        { 3,      N_("Manual")              },
        { 4,      N_("Auto")                },
        { 5,      N_("Program Shift A")     },
        { 6,      N_("Program Shift S")     },
        { 0x1013, N_("Portrait")            },
        { 0x1023, N_("Sports")              },
        { 0x1033, N_("Sunset")              },
        { 0x1043, N_("Night View/Portrait") },
        { 0x1053, N_("Landscape")           },
        { 0x1083, N_("Macro")               }
    }
Lookup table to translate Minolta Dynax 5D camera settings exposure mode values to readable labels.
minoltaExposureMode7D
const TagDetails Exiv2::Internal::minoltaExposureMode7D[] extern
Initial value:
= {
        { 0, N_("Program")           },
        { 1, N_("Aperture priority") },
        { 2, N_("Shutter priority")  },
        { 3, N_("Manual")            },
        { 4, N_("Auto")              },
        { 5, N_("Program-shift A")   },
        { 6, N_("Program-shift S")   }
    }
Lookup table to translate Minolta Dynax 7D camera settings exposure mode values to readable labels.
minoltaExposureModeStd
const TagDetails Exiv2::Internal::minoltaExposureModeStd[] extern
Initial value:
= {
        { 0, N_("Program")           },
        { 1, N_("Aperture priority") },
        { 2, N_("Shutter priority")  },
        { 3, N_("Manual")            }
    }
Lookup table to translate Minolta Std camera settings exposure mode values to readable labels.
minoltaFlashFired
const TagDetails Exiv2::Internal::minoltaFlashFired[] extern
Initial value:
= {
        { 0, N_("Did not fire") },
        { 1, N_("Fired")        }
    }
Lookup table to translate Minolta Std camera settings flash fired values to readable labels.
minoltaFlashMeteringStd
const TagDetails Exiv2::Internal::minoltaFlashMeteringStd[] extern
Initial value:
= {
        { 0, N_("ADI (Advanced Distance Integration)") },
        { 1, N_("Pre-flash TTl")                       },
        { 2, N_("Manual flash control")                }
    }
Lookup table to translate Minolta Std camera settings flash metering values to readable labels.
minoltaFlashModeStd
const TagDetails Exiv2::Internal::minoltaFlashModeStd[] extern
Initial value:
= {
        { 0, N_("Fill flash")        },
        { 1, N_("Red-eye reduction") },
        { 2, N_("Rear flash sync")   },
        { 3, N_("Wireless")          },
        { 4, N_("Off")               }
    }
Lookup table to translate Minolta Std camera settings flash mode values to readable labels.
minoltaFocusArea5D
const TagDetails Exiv2::Internal::minoltaFocusArea5D[] extern
Initial value:
= {
        { 0, N_("Wide")      },
        { 1, N_("Selection") },
        { 2, N_("Spot")      }
    }
Lookup table to translate Minolta Dynax 5D camera settings focus area values to readable labels.
minoltaFocusAreaStd
const TagDetails Exiv2::Internal::minoltaFocusAreaStd[] extern
Initial value:
= {
        { 0, N_("Wide focus (normal)") },
        { 1, N_("Spot focus")          }
    }
Lookup table to translate Minolta Std camera settings focus area values to readable labels.
minoltaFocusMode7D
const TagDetails Exiv2::Internal::minoltaFocusMode7D[] extern
Initial value:
= {
        { 0, N_("Single-shot AF") },
        { 1, N_("Continuous AF")  },
        { 3, N_("Manual")         },
        { 4, N_("Automatic AF")   }
    }
Lookup table to translate Minolta Dynax 7D camera settings focus mode values to readable labels.
minoltaFocusModeStd
const TagDetails Exiv2::Internal::minoltaFocusModeStd[] extern
Initial value:
= {
        { 0, N_("Auto focus")   },
        { 1, N_("Manual focus") }
    }
Lookup table to translate Minolta Std camera settings focus mode values to readable labels.
minoltaFocusPosition5D
const TagDetails Exiv2::Internal::minoltaFocusPosition5D[] extern
Initial value:
= {
        { 0, N_("Wide")       },
        { 1, N_("Central")    },
        { 2, N_("Up")         },
        { 3, N_("Up right")   },
        { 4, N_("Right")      },
        { 5, N_("Down right") },
        { 6, N_("Down")       },
        { 7, N_("Down left")  },
        { 8, N_("Left")       },
        { 9, N_("Up left")    }
    }
Lookup table to translate Minolta Dynax 5D camera settings focus position values to readable labels.
minoltaFolderNameStd
const TagDetails Exiv2::Internal::minoltaFolderNameStd[] extern
Initial value:
= {
        { 0, N_("Standard form") },
        { 1, N_("Data form")     }
    }
Lookup table to translate Minolta Std camera settings folder name values to readable labels.
minoltaImageQuality
const TagDetails Exiv2::Internal::minoltaImageQuality[] extern
Initial value:
= {
        { 0, N_("Raw")        },
        { 1, N_("Super Fine") },
        { 2, N_("Fine")       },
        { 3, N_("Standard")   },
        { 4, N_("Economy")    },
        { 5, N_("Extra Fine") }
    }
Lookup table to translate Minolta image quality values to readable labels.
minoltaImageQuality5D
const TagDetails Exiv2::Internal::minoltaImageQuality5D[] extern
Initial value:
= {
        { 0,  N_("Raw")      },
        { 16, N_("Fine")     },
        { 32, N_("Normal")   },
        { 34, N_("Raw+Jpeg") },
        { 48, N_("Economy")  }
    }
Lookup table to translate Minolta Dynax 5D camera settings image quality values to readable labels.
minoltaImageQuality7D
const TagDetails Exiv2::Internal::minoltaImageQuality7D[] extern
Initial value:
= {
        { 0,  N_("Raw")      },
        { 16, N_("Fine")     },
        { 32, N_("Normal")   },
        { 34, N_("Raw+Jpeg") },
        { 48, N_("Economy")  }
    }
Lookup table to translate Minolta Dynax 7D camera settings image quality values to readable labels.
minoltaImageQualityStd
const TagDetails Exiv2::Internal::minoltaImageQualityStd[] extern
Initial value:
= {
        { 0, N_("Raw")        },
        { 1, N_("Super fine") },
        { 2, N_("Fine")       },
        { 3, N_("Standard")   },
        { 4, N_("Economy")    },
        { 5, N_("Extra fine") }
    }
Lookup table to translate Minolta Std camera settings image quality values to readable labels.
minoltaImageSize5D
const TagDetails Exiv2::Internal::minoltaImageSize5D[] extern
Initial value:
= {
        { 0, N_("Large")  },
        { 1, N_("Medium") },
        { 2, N_("Small")  }
    }
Lookup table to translate Minolta Dynax 5D camera settings image size values to readable labels.
minoltaImageSize7D
const TagDetails Exiv2::Internal::minoltaImageSize7D[] extern
Initial value:
= {
        { 0, N_("Large")  },
        { 1, N_("Medium") },
        { 2, N_("Small")  }
    }
Lookup table to translate Minolta Dynax 7D camera settings image size values to readable labels.
minoltaImageSizeStd
const TagDetails Exiv2::Internal::minoltaImageSizeStd[] extern
Initial value:
= {
        { 0, N_("Full size") },
        { 1, "1600x1200"     },
        { 2, "1280x960"      },
        { 3, "640x480"       },
        { 6, "2080x1560"     },
        { 7, "2560x1920"     },
        { 8, "3264x2176"     }
    }
Lookup table to translate Minolta Std camera settings image size values to readable labels.
minoltaImageStabilization
const TagDetails Exiv2::Internal::minoltaImageStabilization[] extern
Initial value:
= {
        { 1, N_("Off") },
        { 5, N_("On")  }
    }
Lookup table to translate Minolta image stabilization values.
minoltaIntervalModeStd
const TagDetails Exiv2::Internal::minoltaIntervalModeStd[] extern
Initial value:
= {
        { 0, N_("Still image")      },
        { 1, N_("Time-lapse movie") }
    }
Lookup table to translate Minolta Std camera settings interval mode values to readable labels.
minoltaISOSetting5D
const TagDetails Exiv2::Internal::minoltaISOSetting5D[] extern
Initial value:
= {
        { 0,  N_("Auto")                     },
        { 1,  "100"                          },
        { 3,  "200"                          },
        { 4,  "400"                          },
        { 5,  "800"                          },
        { 6,  "1600"                         },
        { 7,  "3200"                         },
        { 8,  N_("200 (Zone Matching High)") },
        { 10, N_("80 (Zone Matching Low)")   }
    }
Lookup table to translate Minolta Dynax 5D camera settings ISO settings values to readable labels.
minoltaISOSetting7D
const TagDetails Exiv2::Internal::minoltaISOSetting7D[] extern
Initial value:
= {
        { 0, N_("Auto") },
        { 1, "100"      },
        { 3, "200"      },
        { 4, "400"      },
        { 5, "800"      },
        { 6, "1600"     },
        { 7, "3200"     }
    }
Lookup table to translate Minolta Dynax 7D camera settings ISO settings values to readable labels.
minoltaISOSettingStd
const TagDetails Exiv2::Internal::minoltaISOSettingStd[] extern
Initial value:
= {
        { 0, "100"      },
        { 1, "200"      },
        { 2, "400"      },
        { 3, "800"      },
        { 4, N_("Auto") },
        { 5, "64"       }
    }
Lookup table to translate Minolta Std camera settings ISO settings values to readable labels.
minoltaMeteringMode5D
const TagDetails Exiv2::Internal::minoltaMeteringMode5D[] extern
Initial value:
= {
        { 0, N_("Multi-segment")   },
        { 1, N_("Center weighted") },
        { 2, N_("Spot")            }
    }
Lookup table to translate Minolta Dynax 5D camera settings metering mode values to readable labels.
minoltaMeteringModeStd
const TagDetails Exiv2::Internal::minoltaMeteringModeStd[] extern
Initial value:
= {
        { 0, N_("Multi-segment")           },
        { 1, N_("Center weighted average") },
        { 2, N_("Spot")                    }
    }
Lookup table to translate Minolta Std camera settings metering mode values to readable labels.
minoltaModelStd
const TagDetails Exiv2::Internal::minoltaModelStd[] extern
Initial value:
= {
        { 0, "DiMAGE 7 | X1 | X21 | X31" },
        { 1, "DiMAGE 5"                  },
        { 2, "DiMAGE S304"               },
        { 3, "DiMAGE S404"               },
        { 4, "DiMAGE 7i"                 },
        { 5, "DiMAGE 7Hi"                },
        { 6, "DiMAGE A1"                 },
        { 7, "DiMAGE A2 | S414"          },
        { 7, "DiMAGE A2 | S414"          }
    }
Lookup table to translate Minolta Std camera settings model values to readable labels.
minoltaPictureFinish5D
const TagDetails Exiv2::Internal::minoltaPictureFinish5D[] extern
Initial value:
= {
        { 0, N_("Natural")         },
        { 1, N_("Natural+")        },
        { 2, N_("Portrait")        },
        { 3, N_("Wind Scene")      },
        { 4, N_("Evening Scene")   },
        { 5, N_("Night Scene")     },
        { 6, N_("Night Portrait")  },
        { 7, N_("Monochrome")      },
        { 8, N_("Adobe RGB")       },
        { 9, N_("Adobe RGB (ICC)") }
    }
Lookup table to translate Minolta Dynax 5D camera settings picture finish values to readable labels.
minoltaRotation5D
const TagDetails Exiv2::Internal::minoltaRotation5D[] extern
Initial value:
= {
        { 72, N_("Horizontal (normal)") },
        { 76, N_("Rotate 90 CW")        },
        { 82, N_("Rotate 270 CW")       }
    }
Lookup table to translate Minolta Dynax 5D camera settings rotation values to readable labels.
minoltaRotation7D
const TagDetails Exiv2::Internal::minoltaRotation7D[] extern
Initial value:
= {
        { 72, N_("Horizontal (normal)") },
        { 76, N_("Rotate 90 CW")        },
        { 82, N_("Rotate 270 CW")       }
    }
Lookup table to translate Minolta Dynax 7D camera settings rotation values to readable labels.
minoltaSharpnessStd
const TagDetails Exiv2::Internal::minoltaSharpnessStd[] extern
Initial value:
= {
        { 0, N_("Hard")   },
        { 1, N_("Normal") },
        { 2, N_("Soft")   }
    }
Lookup table to translate Minolta Std camera settings sharpness values to readable labels.
minoltaSonyAFAreaMode
const TagDetails Exiv2::Internal::minoltaSonyAFAreaMode[] extern
Initial value:
= {
        { 0, N_("Wide")  },
        { 1, N_("Local") },
        { 2, N_("Spot")  }
    }
Lookup table to translate Sony camera settings focus mode values to readable labels.
Referenced by printMinoltaSonyAFAreaMode().
minoltaSonyBoolFunction
const TagDetails Exiv2::Internal::minoltaSonyBoolFunction[] extern
Initial value:
= {
        { 0, N_("Off") },
        { 1, N_("On")  }
    }
Lookup table to translate Minolta/Sony bool function values to readable labels.
Referenced by printMinoltaSonyBoolValue().
minoltaSonyBoolInverseFunction
const TagDetails Exiv2::Internal::minoltaSonyBoolInverseFunction[] extern
Initial value:
= {
        { 0, N_("On")  },
        { 1, N_("Off") }
    }
Lookup table to translate Minolta/Sony bool inverse function values to readable labels.
Referenced by printMinoltaSonyBoolInverseValue().
minoltaSonyColorMode
const TagDetails Exiv2::Internal::minoltaSonyColorMode[] extern
Initial value:
= {
        { 0,   N_("Standard")            },
        { 1,   N_("Vivid Color")         },
        { 2,   N_("Portrait")            },
        { 3,   N_("Landscape")           },
        { 4,   N_("Sunset")              },
        { 5,   N_("Night View/Portrait") },
        { 6,   N_("Black & White")       },
        { 7,   N_("AdobeRGB")            },
        { 12,  N_("Neutral")             },
        { 100, N_("Neutral")             },
        { 101, N_("Clear")               },
        { 102, N_("Deep")                },
        { 103, N_("Light")               },
        { 104, N_("Night View")          },
        { 105, N_("Autumn Leaves")       }
    }
Lookup table to translate Minolta A100 and all other Sony Alpha camera color mode values to readable labels.
Referenced by printMinoltaSonyColorMode().
minoltaSonyDynamicRangeOptimizerMode
const TagDetails Exiv2::Internal::minoltaSonyDynamicRangeOptimizerMode[] extern
Initial value:
= {
        { 0,    N_("Off")            },
        { 1,    N_("Standard")       },
        { 2,    N_("Advanced Auto")  },
        { 3,    N_("Advanced Level") },
        { 4097, N_("Auto")           }
    }
Lookup table to translate Sony camera settings dynamic range optimizer mode values to readable labels.
Referenced by printMinoltaSonyDynamicRangeOptimizerMode().
minoltaSonyImageQuality
const TagDetails Exiv2::Internal::minoltaSonyImageQuality[] extern
Initial value:
= {
        { 0, N_("Raw")                   },
        { 1, N_("Super Fine")            },
        { 2, N_("Fine")                  },
        { 3, N_("Standard")              },
        { 4, N_("Economy")               },
        { 5, N_("Extra Fine")            },
        { 6, N_("Raw + JPEG")            },
        { 7, N_("Compressed Raw")        },
        { 8, N_("Compressed Raw + JPEG") }
    }
Lookup table to translate Sony/Minolta image quality values to readable labels.
Referenced by printMinoltaSonyImageQuality().
minoltaSonyLocalAFAreaPoint
const TagDetails Exiv2::Internal::minoltaSonyLocalAFAreaPoint[] extern
Initial value:
= {
        { 1,  N_("Center")       },
        { 2,  N_("Top")          },
        { 3,  N_("Top-Right")    },
        { 4,  N_("Right")        },
        { 5,  N_("Bottom-Right") },
        { 6,  N_("Bottom")       },
        { 7,  N_("Bottom-Left")  },
        { 8,  N_("Left")         },
        { 9,  N_("Top-Left")     },
        { 10, N_("Far-Right")    },
        { 11, N_("Far-Left")     }
    }
Lookup table to translate Sony camera settings Local AF Area Point values to readable labels.
Referenced by printMinoltaSonyLocalAFAreaPoint().
minoltaSonyPrioritySetupShutterRelease
const TagDetails Exiv2::Internal::minoltaSonyPrioritySetupShutterRelease[] extern
Initial value:
= {
        { 0, N_("AF")      },
        { 1, N_("Release") }
    }
Lookup table to translate Sony camera settings priority setup shutter release values to readable labels.
Referenced by printMinoltaSonyPrioritySetupShutterRelease().
minoltaSonyQualityCs
const TagDetails Exiv2::Internal::minoltaSonyQualityCs[] extern
Initial value:
= {
        { 0,   N_("RAW")        },
        { 2,   N_("CRAW")       },
        { 16,  N_("Extra Fine") },
        { 32,  N_("Fine")       },
        { 34,  N_("RAW+JPEG")   },
        { 35,  N_("CRAW+JPEG")  },
        { 48,  N_("Standard")   }
    }
Lookup table to translate Sony camera settings quality values to readable labels.
Referenced by printMinoltaSonyQualityCs().
minoltaSonyRotation
const TagDetails Exiv2::Internal::minoltaSonyRotation[] extern
Initial value:
= {
        { 0, N_("Horizontal (normal)") },
        { 1, N_("Rotate 90 CW")        },
        { 2, N_("Rotate 270 CW")       }
    }
Lookup table to translate Sony camera settings rotation values to readable labels.
Referenced by printMinoltaSonyRotation().
minoltaSonySceneMode
const TagDetails Exiv2::Internal::minoltaSonySceneMode[] extern
Initial value:
= {
        { 0,  N_("Standard")            },
        { 1,  N_("Portrait")            },
        { 2,  N_("Text")                },
        { 3,  N_("Night Scene")         },
        { 4,  N_("Sunset")              },
        { 5,  N_("Sports")              },
        { 6,  N_("Landscape")           },
        { 7,  N_("Night Portrait")      },
        { 8,  N_("Macro")               },
        { 9,  N_("Super Macro")         },
        { 16, N_("Auto")                },
        { 17, N_("Night View/Portrait") }
    }
Lookup table to translate Minolta/Sony scene mode values to readable labels.
Referenced by printMinoltaSonySceneMode().
minoltaSonyTeleconverterModel
const TagDetails Exiv2::Internal::minoltaSonyTeleconverterModel[] extern
Initial value:
= {
        { 0x00, N_("None")                                },
        { 0x04, N_("Minolta/Sony AF 1.4x APO (D) (0x04)") },
        { 0x05, N_("Minolta/Sony AF 2x APO (D) (0x05)")   },
        { 0x48, N_("Minolta/Sony AF 2x APO (D)")          },
        { 0x50, N_("Minolta AF 2x APO II")                },
        { 0x60, N_("Minolta AF 2x APO")                   },
        { 0x88, N_("Minolta/Sony AF 1.4x APO (D)")        },
        { 0x90, N_("Minolta AF 1.4x APO II")              },
        { 0xa0, N_("Minolta AF 1.4x APO")                 }
    }
Lookup table to translate Sony/Minolta teleconverter model values to readable labels.
Referenced by printMinoltaSonyTeleconverterModel().
minoltaSonyWhiteBalanceStd
const TagDetails Exiv2::Internal::minoltaSonyWhiteBalanceStd[] extern
Initial value:
= {
        { 0x00,  N_("Auto")                           },
        { 0x01,  N_("Color Temperature/Color Filter") },
        { 0x10,  N_("Daylight")                       },
        { 0x20,  N_("Cloudy")                         },
        { 0x30,  N_("Shade")                          },
        { 0x40,  N_("Tungsten")                       },
        { 0x50,  N_("Flash")                          },
        { 0x60,  N_("Fluorescent")                    },
        { 0x70,  N_("Custom")                         }
    }
Lookup table to translate Sony/Minolta Std camera settings white balance values to readable labels.
Referenced by printMinoltaSonyWhiteBalanceStd().
minoltaSonyZoneMatching
const TagDetails Exiv2::Internal::minoltaSonyZoneMatching[] extern
Initial value:
= {
        { 0, N_("ISO Setting Used") },
        { 1, N_("High Key") },
        { 2, N_("Low Key")  }
    }
Lookup table to translate Sony/Minolta zone matching values to readable labels.
Referenced by printMinoltaSonyZoneMatching().
minoltaSubjectProgramStd
const TagDetails Exiv2::Internal::minoltaSubjectProgramStd[] extern
Initial value:
= {
        { 0, N_("None")           },
        { 1, N_("Portrait")       },
        { 2, N_("Text")           },
        { 3, N_("Night portrait") },
        { 4, N_("Sunset")         },
        { 5, N_("Sports action")  }
    }
Lookup table to translate Minolta Std camera settings subject program values to readable labels.
minoltaWhiteBalance5D
const TagDetails Exiv2::Internal::minoltaWhiteBalance5D[] extern
Initial value:
= {
        { 0,   N_("Auto")        },
        { 1,   N_("Daylight")    },
        { 2,   N_("Cloudy")      },
        { 3,   N_("Shade")       },
        { 4,   N_("Tungsten")    },
        { 5,   N_("Fluorescent") },
        { 6,   N_("Flash")       },
        { 256, N_("Kelvin")      },
        { 512, N_("Manual")      }
    }
Lookup table to translate Minolta Dynax 5D camera settings white balance values to readable labels.
minoltaWhiteBalance7D
const TagDetails Exiv2::Internal::minoltaWhiteBalance7D[] extern
Initial value:
= {
        { 0,   N_("Auto")        },
        { 1,   N_("Daylight")    },
        { 2,   N_("Shade")       },
        { 3,   N_("Cloudy")      },
        { 4,   N_("Tungsten")    },
        { 5,   N_("Fluorescent") },
        { 256, N_("Kelvin")      },
        { 512, N_("Manual")      },
        { 512, N_("Manual")      }
    }
Lookup table to translate Minolta Dynax 7D camera settings white balance values to readable labels.
minoltaWhiteBalanceStd
const TagDetails Exiv2::Internal::minoltaWhiteBalanceStd[] extern
Initial value:
= {
        { 0,  N_("Auto")          },
        { 1,  N_("Daylight")      },
        { 2,  N_("Cloudy")        },
        { 3,  N_("Tungsten")      },
        { 5,  N_("Custom")        },
        { 7,  N_("Fluorescent")   },
        { 8,  N_("Fluorescent 2") },
        { 11, N_("Custom 2")      },
        { 12, N_("Custom 3")      }
    }
Lookup table to translate Minolta Std camera settings white balance values to readable labels.
minoltaWideFocusZoneStd
const TagDetails Exiv2::Internal::minoltaWideFocusZoneStd[] extern
Initial value:
= {
        { 0, N_("No zone")                              },
        { 1, N_("Center zone (horizontal orientation)") },
        { 1, N_("Center zone (vertical orientation)")   },
        { 1, N_("Left zone")                            },
        { 4, N_("Right zone")                           }
    }
Lookup table to translate Minolta Std camera settings wide focus zone values to readable labels.
nikon2ColorMode
const TagDetails Exiv2::Internal::nikon2ColorMode[] extern
Initial value:
= {
        { 1, N_("Color")      },
        { 2, N_("Monochrome") }
    }
ColorMode, tag 0x0004.
nikon2ImageAdjustment
const TagDetails Exiv2::Internal::nikon2ImageAdjustment[] extern
Initial value:
= {
        { 0, N_("Normal")    },
        { 1, N_("Bright+")   },
        { 2, N_("Bright-")   },
        { 3, N_("Contrast+") },
        { 4, N_("Contrast-") }
    }
ImageAdjustment, tag 0x0005.
nikon2IsoSpeed
const TagDetails Exiv2::Internal::nikon2IsoSpeed[] extern
Initial value:
= {
        { 0, "80"  },
        { 2, "160" },
        { 4, "320" },
        { 5, "100" }
    }
ISOSpeed, tag 0x0006.
nikon2Quality
const TagDetails Exiv2::Internal::nikon2Quality[] extern
Initial value:
= {
        { 1, N_("VGA Basic")   },
        { 2, N_("VGA Normal")  },
        { 3, N_("VGA Fine")    },
        { 4, N_("SXGA Basic")  },
        { 5, N_("SXGA Normal") },
        { 6, N_("SXGA Fine")   }
    }
Quality, tag 0x0003.
nikon2WhiteBalance
const TagDetails Exiv2::Internal::nikon2WhiteBalance[] extern
Initial value:
= {
        { 0, N_("Auto")         },
        { 1, N_("Preset")       },
        { 2, N_("Daylight")     },
        { 3, N_("Incandescent") },
        { 4, N_("Fluorescent")  },
        { 5, N_("Cloudy")       },
        { 6, N_("Speedlight")   }
    }
WhiteBalance, tag 0x0007.
nikonActiveDLighning
const TagDetails Exiv2::Internal::nikonActiveDLighning[] extern
Initial value:
= {
        {     0, N_("Off")        },
        {     1, N_("Low")        },
        {     3, N_("Normal")     },
        {     5, N_("High")       },
        {     7, N_("Extra High") },
        { 65535, N_("Auto")       }
    }
Off, Low, Normal, High, multiple tags.
nikonAdjust
const TagDetails Exiv2::Internal::nikonAdjust[] extern
Initial value:
= {
        {  0, N_("Default Settings") },
        {  1, N_("Quick Adjust")     },
        {  2, N_("Full Control")     }
    }
Adjust.
nikonAf21Cfg
const ArrayCfg Exiv2::Internal::nikonAf21Cfg extern
Initial value:
= {
        nikonAf21Id,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Auto Focus 21 binary array - configuration.
nikonAf21Def
const ArrayDef Exiv2::Internal::nikonAf21Def[] extern
Initial value:
= {
        {  0, ttUndefined,     4 },
        {  4, ttUnsignedByte,  1 },
        {  5, ttUnsignedByte,  1 },
        {  6, ttUnsignedByte,  1 },
        {  7, ttUnsignedByte,  1 },
        {  8, ttUnsignedByte,  7 },
        { 16, ttUnsignedShort, 1 },
        { 18, ttUnsignedShort, 1 },
        { 20, ttUnsignedShort, 1 },
        { 22, ttUnsignedShort, 1 },
        { 24, ttUnsignedShort, 1 },
        { 26, ttUnsignedShort, 1 },
        { 28, ttUnsignedShort, 1 },
    }
Nikon Auto Focus 21 binary array - definition.
nikonAf22Cfg
const ArrayCfg Exiv2::Internal::nikonAf22Cfg extern
Initial value:
= {
        nikonAf22Id,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Auto Focus 22 binary array - configuration.
nikonAf22Def
const ArrayDef Exiv2::Internal::nikonAf22Def[] extern
Initial value:
= {
        {  0, ttUndefined,     4 },
        {  4, ttUnsignedByte,  1 },
        {  5, ttUnsignedByte,  1 },
        {  6, ttUnsignedByte,  1 },
        {  7, ttUnsignedByte,  1 },
        {  8, ttUnsignedByte,  7 },
        { 70, ttUnsignedShort, 1 },
        { 72, ttUnsignedShort, 1 },
        { 74, ttUnsignedShort, 1 },
        { 76, ttUnsignedShort, 1 },
        { 78, ttUnsignedShort, 1 },
        { 80, ttUnsignedShort, 1 },
    }
Nikon Auto Focus 22 binary array - definition.
nikonAf2Set
const ArraySet Exiv2::Internal::nikonAf2Set[] extern
Initial value:
= {
        { nikonAf21Cfg, nikonAf21Def, EXV_COUNTOF(nikonAf21Def) },
        { nikonAf22Cfg, nikonAf22Def, EXV_COUNTOF(nikonAf22Def) },
    }
Nikon AF2 configuration and definitions.
nikonAfAreaMode
const TagDetails Exiv2::Internal::nikonAfAreaMode[] extern
Initial value:
= {
        { 0, N_("Single Area")                   },
        { 1, N_("Dynamic Area")                  },
        { 2, N_("Dynamic Area, Closest Subject") },
        { 3, N_("Group Dynamic")                 },
        { 4, N_("Single Area (wide)")            },
        { 5, N_("Dynamic Area (wide)")           }
    }
AfAreaMode.
nikonAfCfg
const ArrayCfg Exiv2::Internal::nikonAfCfg extern
Initial value:
= {
        nikonAfId,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Auto Focus binary array - configuration.
nikonAfDef
const ArrayDef Exiv2::Internal::nikonAfDef[] extern
Initial value:
= {
        { 0, ttUnsignedByte,  1 },
        { 1, ttUnsignedByte,  1 },
        { 2, ttUnsignedShort, 1 }
    }
Nikon Auto Focus binary array - definition.
nikonAfPoint
const TagDetails Exiv2::Internal::nikonAfPoint[] extern
Initial value:
= {
        { 0, N_("Center")      },
        { 1, N_("Top")         },
        { 2, N_("Bottom")      },
        { 3, N_("Mid-left")    },
        { 4, N_("Mid-right")   },
        { 5, N_("Upper-left")  },
        { 6, N_("Upper-right") },
        { 7, N_("Lower-left")  },
        { 8, N_("Lower-right") },
        { 9, N_("Far Left")    },
        { 10, N_("Far Right")  }
    }
AfPoint.
nikonAfPointsInFocus
const TagDetailsBitmask Exiv2::Internal::nikonAfPointsInFocus[] extern
Initial value:
= {
        { 0x0001, N_("Center")        },
        { 0x0002, N_("Top")           },
        { 0x0004, N_("Bottom")        },
        { 0x0008, N_("Mid-left")      },
        { 0x0010, N_("Mid-right")     },
        { 0x0020, N_("Upper-left")    },
        { 0x0040, N_("Upper-right")   },
        { 0x0080, N_("Lower-left")    },
        { 0x0100, N_("Lower-right")   },
        { 0x0200, N_("Far Left")      },
        { 0x0400, N_("Far Right")     }
    }
AfPointsInFocus.
Referenced by Exiv2::Internal::Nikon3MakerNote::printAfPointsInFocus().
nikonAFTCfg
const ArrayCfg Exiv2::Internal::nikonAFTCfg extern
Initial value:
= {
        nikonAFTId,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon AF Fine Tune binary array - configuration.
nikonAFTDef
const ArrayDef Exiv2::Internal::nikonAFTDef[] extern
Initial value:
= {
        {  0, ttUnsignedByte,  1 },
        {  1, ttUnsignedByte,  1 },
        {  2, ttUnsignedByte,  1 }
    }
Nikon AF Fine Tune binary array - definition.
nikonAutoBracketRelease
const TagDetails Exiv2::Internal::nikonAutoBracketRelease[] extern
Initial value:
= {
        { 0, N_("None")           },
        { 1, N_("Auto release")   },
        { 2, N_("Manual release") }
    }
AutoBracketRelease, tag 0x008a.
nikonCb1Cfg
const ArrayCfg Exiv2::Internal::nikonCb1Cfg extern
Initial value:
= {
        nikonCb1Id,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        false,
        true,
        { 0, ttUnsignedShort, 1 }
    }
Nikon Color Balance binary array - configuration 1.
nikonCb1Def
const ArrayDef Exiv2::Internal::nikonCb1Def[] extern
Initial value:
= {
        {  0, ttUndefined,        4 },
        { 72, ttUnsignedShort,    4 }
    }
Nikon Color Balance binary array - definition 1 (D100)
nikonCb2aCfg
const ArrayCfg Exiv2::Internal::nikonCb2aCfg extern
Initial value:
= {
        nikonCb2aId,
        invalidByteOrder,
        ttUndefined,
        nikonCrypt,
        false,
        false,
        true,
        { 0, ttUnsignedShort, 1 }
    }
Nikon Color Balance binary array - configuration 2a.
nikonCb2aDef
const ArrayDef Exiv2::Internal::nikonCb2aDef[] extern
Initial value:
= {
        {  0, ttUndefined,        4 },
        { 18, ttUnsignedShort,    4 }
    }
Nikon Color Balance binary array - definition 2a (D50)
nikonCb2bCfg
const ArrayCfg Exiv2::Internal::nikonCb2bCfg extern
Initial value:
= {
        nikonCb2bId,
        invalidByteOrder,
        ttUndefined,
        nikonCrypt,
        false,
        false,
        true,
        { 0, ttUnsignedShort, 1 }
    }
Nikon Color Balance binary array - configuration 2b.
nikonCb2bDef
const ArrayDef Exiv2::Internal::nikonCb2bDef[] extern
Initial value:
= {
        {  0, ttUndefined,        4 },
        {  4, ttUnsignedShort,  140 },
        {284, ttUnsignedShort,    3 },
        {290, ttUnsignedShort,    4 }
    }
Nikon Color Balance binary array - definition 2b (D2X=0204,D2Hs=0206,D200=0207,D40=0208)
nikonCb2Cfg
const ArrayCfg Exiv2::Internal::nikonCb2Cfg extern
Initial value:
= {
        nikonCb2Id,
        invalidByteOrder,
        ttUndefined,
        nikonCrypt,
        false,
        false,
        true,
        { 0, ttUnsignedShort, 1 }
    }
Nikon Color Balance binary array - configuration 2.
nikonCb2Def
const ArrayDef Exiv2::Internal::nikonCb2Def[] extern
Initial value:
= {
        {  0, ttUndefined,        4 },
        { 10, ttUnsignedShort,    4 }
    }
Nikon Color Balance binary array - definition 2 (D2H)
nikonCb3Cfg
const ArrayCfg Exiv2::Internal::nikonCb3Cfg extern
Initial value:
= {
        nikonCb3Id,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        false,
        true,
        { 0, ttUnsignedShort, 1 }
    }
Nikon Color Balance binary array - configuration 3.
nikonCb3Def
const ArrayDef Exiv2::Internal::nikonCb3Def[] extern
Initial value:
= {
        {  0, ttUndefined,        4 },
        { 20, ttUnsignedShort,    4 }
    }
Nikon Color Balance binary array - definition 3 (D70)
nikonCb4Cfg
const ArrayCfg Exiv2::Internal::nikonCb4Cfg extern
Initial value:
= {
        nikonCb4Id,
        invalidByteOrder,
        ttUndefined,
        nikonCrypt,
        false,
        false,
        true,
        { 0, ttUnsignedShort, 1 }
    }
Nikon Color Balance binary array - configuration 4.
nikonCb4Def
const ArrayDef Exiv2::Internal::nikonCb4Def[] extern
Initial value:
= {
        {  0, ttUndefined,        4 },
        {  4, ttUnsignedShort,  140 },
        {284, ttUnsignedShort,    5 },
        {294, ttUnsignedShort,    4 }
    }
Nikon Color Balance binary array - definition 4 (D3)
nikonCbSet
const ArraySet Exiv2::Internal::nikonCbSet[] extern
Initial value:
= {
        { nikonCb1Cfg,  nikonCb1Def,  EXV_COUNTOF(nikonCb1Def)  },
        { nikonCb2Cfg,  nikonCb2Def,  EXV_COUNTOF(nikonCb2Def)  },
        { nikonCb2aCfg, nikonCb2aDef, EXV_COUNTOF(nikonCb2aDef) },
        { nikonCb2bCfg, nikonCb2bDef, EXV_COUNTOF(nikonCb2bDef) },
        { nikonCb3Cfg,  nikonCb3Def,  EXV_COUNTOF(nikonCb3Def)  },
        { nikonCb4Cfg,  nikonCb4Def,  EXV_COUNTOF(nikonCb4Def)  }
    }
Nikon Color Balance configurations and definitions.
nikonColorSpace
const TagDetails Exiv2::Internal::nikonColorSpace[] extern
Initial value:
= {
        { 1, N_("sRGB")      },
        { 2, N_("Adobe RGB") }
    }
ColorSpace, tag 0x001e.
nikonDateDisplayFormat
const TagDetails Exiv2::Internal::nikonDateDisplayFormat[] extern
Initial value:
= {
        { 0, N_("Y/M/D") },
        { 1, N_("M/D/Y") },
        { 2, N_("D/M/Y") }
    }
DateDisplayFormat, tag index 3.
nikonExternalFlashFlags
const TagDetails Exiv2::Internal::nikonExternalFlashFlags[] extern
Initial value:
= {
        { 0, N_("Fired")              },
        { 2, N_("Bounce Flash")       },
        { 4, N_("Wide Flash Adapter") }
    }
ExternalFlashFlags.
nikonFiCfg
const ArrayCfg Exiv2::Internal::nikonFiCfg extern
Initial value:
= {
        nikonFiId,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon File Info binary array - configuration.
nikonFiDef
const ArrayDef Exiv2::Internal::nikonFiDef[] extern
Initial value:
= {
        { 0, ttUndefined,     4 },
        { 6, ttUnsignedShort, 1 },
        { 8, ttUnsignedShort, 1 }
    }
Nikon File Info binary array - definition.
nikonFilterEffect
const TagDetails Exiv2::Internal::nikonFilterEffect[] extern
Initial value:
= {
        { 0x80, N_("Off")    },
        { 0x81, N_("Yellow") },
        { 0x82, N_("Orange") },
        { 0x83, N_("Red")    },
        { 0x84, N_("Green")  },
        { 0xff, N_("n/a")    }
    }
FilterEffect.
nikonFl1Cfg
const ArrayCfg Exiv2::Internal::nikonFl1Cfg extern
Initial value:
= {
        nikonFl1Id,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Flash Info binary array - configuration 1.
nikonFl1Def
const ArrayDef Exiv2::Internal::nikonFl1Def[] extern
Initial value:
= {
        {  0, ttUndefined,     4 },
        {  4, ttUnsignedByte,  1 },
        {  6, ttUnsignedShort, 1 },
        {  8, ttUnsignedByte,  1 },
        { 11, ttUnsignedByte,  1 },
        { 12, ttUnsignedByte,  1 },
        { 13, ttUnsignedByte,  1 },
        { 14, ttUnsignedByte,  1 },
        { 15, ttUnsignedByte,  1 },
        { 16, ttUnsignedByte,  1 }
    }
Nikon Flash Info binary array - definition 1.
nikonFl2Cfg
const ArrayCfg Exiv2::Internal::nikonFl2Cfg extern
Initial value:
= {
        nikonFl2Id,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Flash Info binary array - configuration 2.
nikonFl2Def
const ArrayDef Exiv2::Internal::nikonFl2Def[] extern
Initial value:
= {
        {  0, ttUndefined,     4 },
        {  4, ttUnsignedByte,  1 },
        {  6, ttUnsignedShort, 1 },
        {  8, ttUnsignedByte,  1 },
        { 12, ttUnsignedByte,  1 },
        { 13, ttUnsignedByte,  1 },
        { 14, ttUnsignedByte,  1 },
        { 15, ttUnsignedByte,  1 },
    }
Nikon Flash Info binary array - definition 2.
nikonFl3Cfg
const ArrayCfg Exiv2::Internal::nikonFl3Cfg extern
Initial value:
= {
        nikonFl3Id,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Flash Info binary array - configuration 3.
nikonFl3Def
const ArrayDef Exiv2::Internal::nikonFl3Def[] extern
Initial value:
= {
        {  0, ttUndefined,     4 },
        {  4, ttUnsignedByte,  1 },
        {  6, ttUnsignedShort, 1 },
        {  8, ttUnsignedByte,  1 },
        { 12, ttUnsignedByte,  1 },
        { 13, ttUnsignedByte,  1 },
        { 14, ttUnsignedByte,  1 },
        { 15, ttUnsignedByte,  1 },
        { 16, ttUnsignedByte,  1 },
    }
Nikon Flash Info binary array - definition.
nikonFlashColorFilter
const TagDetails Exiv2::Internal::nikonFlashColorFilter[] extern
Initial value:
= {
        {  0, N_("None")   },
        {  1, N_("FL-GL1") },
        {  2, N_("FL-GL2") },
        {  9, N_("TN-A1")  },
        { 10, N_("TN-A2")  },
        { 65, N_("Red")    },
        { 66, N_("Blue")   },
        { 67, N_("Yellow") },
        { 68, N_("Amber")  }
    }
FlashColorFilter.
nikonFlashComp
const TagDetails Exiv2::Internal::nikonFlashComp[] extern
Initial value:
= {
        { 0x06, "+1.0 EV" },
        { 0x04, "+0.7 EV" },
        { 0x03, "+0.5 EV" },
        { 0x02, "+0.3 EV" },
        { 0x00,  "0.0 EV" },
        { 0xfe, "-0.3 EV" },
        { 0xfd, "-0.5 EV" },
        { 0xfc, "-0.7 EV" },
        { 0xfa, "-1.0 EV" },
        { 0xf8, "-1.3 EV" },
        { 0xf7, "-1.5 EV" },
        { 0xf6, "-1.7 EV" },
        { 0xf4, "-2.0 EV" },
        { 0xf2, "-2.3 EV" },
        { 0xf1, "-2.5 EV" },
        { 0xf0, "-2.7 EV" },
        { 0xee, "-3.0 EV" }
    }
FlashComp, tag 0x0012.
nikonFlashControlMode
const TagDetails Exiv2::Internal::nikonFlashControlMode[] extern
Initial value:
= {
        { 0, N_("Off")                    },
        { 1, N_("iTTL-BL")                },
        { 2, N_("iTTL")                   },
        { 3, N_("Auto Aperture")          },
        { 4, N_("Automatic")              },
        { 5, N_("GN (distance priority)") },
        { 6, N_("Manual")                 },
        { 7, N_("Repeating Flash")        },
        { 7, N_("Repeating Flash")        }
    }
FlashControlMode.
nikonFlashFirmware
const TagDetails Exiv2::Internal::nikonFlashFirmware[] extern
Initial value:
= {
        { 0x0000, N_("n/a")                            },
        { 0x0101, N_("1.01 (SB-800 or Metz 58 AF-1)")  },
        { 0x0103, "1.03 (SB-800)"                  },
        { 0x0201, "2.01 (SB-800)"                  },
        { 0x0204, "2.04 (SB-600)"                  },
        { 0x0205, "2.05 (SB-600)"                  },
        { 0x0301, "3.01 (SU-800 Remote Commander)" },
        { 0x0401, "4.01 (SB-400)"                  },
        { 0x0402, "4.02 (SB-400)"                  },
        { 0x0404, "4.04 (SB-400)"                  },
        { 0x0501, "5.01 (SB-900)"                  },
        { 0x0502, "5.02 (SB-900)"                  },
        { 0x0601, "6.01 (SB-700)"                  },
        { 0x0701, "7.01 (SB-910)"                  }
    }
FlashFirmware.
nikonFlashMode
const TagDetails Exiv2::Internal::nikonFlashMode[] extern
Initial value:
= {
        { 0, N_("Did not fire")         },
        { 1, N_("Fire, manual")         },
        { 7, N_("Fire, external")       },
        { 8, N_("Fire, commander mode") },
        { 9, N_("Fire, TTL mode")       }
    }
FlashMode, tag 0x0087.
nikonFlashSource
const TagDetails Exiv2::Internal::nikonFlashSource[] extern
Initial value:
= {
        { 0, N_("None")     },
        { 1, N_("External") },
        { 2, N_("Internal") }
    }
FlashSource.
nikonFlSet
const ArraySet Exiv2::Internal::nikonFlSet[] extern
Initial value:
= {
        { nikonFl1Cfg, nikonFl1Def, EXV_COUNTOF(nikonFl1Def) },
        { nikonFl2Cfg, nikonFl2Def, EXV_COUNTOF(nikonFl2Def) },
        { nikonFl3Cfg, nikonFl3Def, EXV_COUNTOF(nikonFl3Def) }
    }
Nikon Lens Data configurations and definitions.
nikonFocusarea
const char* const Exiv2::Internal::nikonFocusarea[] extern
Initial value:
= {
        N_("Single area"),
        N_("Dynamic area"),
        N_("Dynamic area, closest subject"),
        N_("Group dynamic"),
        N_("Single area (wide)"),
    }
Focus area for Nikon cameras.
Referenced by Exiv2::Internal::Nikon1MakerNote::print0x0088().
nikonFocuspoints
const char* const Exiv2::Internal::nikonFocuspoints[] extern
Initial value:
= {
        N_("Center"),
        N_("Top"),
        N_("Bottom"),
        N_("Left"),
        N_("Right"),
        N_("Upper-left"),
        N_("Upper-right"),
        N_("Lower-left"),
        N_("Lower-right"),
        N_("Left-most"),
    }
Focus points for Nikon cameras, used for Nikon 1 and Nikon 3 makernotes.
Referenced by Exiv2::Internal::Nikon1MakerNote::print0x0088(), and Exiv2::Internal::Nikon3MakerNote::print0x0088().
nikonHighISONoiseReduction
const TagDetails Exiv2::Internal::nikonHighISONoiseReduction[] extern
Initial value:
= {
        { 0, N_("Off")     },
        { 1, N_("Minimal") },
        { 2, N_("Low")     },
        { 4, N_("Normal")  },
        { 6, N_("High")    }
    }
HighISONoiseReduction, tag 0x00b1.
nikonIiCfg
const ArrayCfg Exiv2::Internal::nikonIiCfg extern
Initial value:
= {
        nikonIiId,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon ISO info binary array - configuration.
nikonIiDef
const ArrayDef Exiv2::Internal::nikonIiDef[] extern
Initial value:
= {
        {  0, ttUnsignedByte,  1 },
        {  4, ttUnsignedShort, 1 },
        {  6, ttUnsignedByte,  1 },
        { 10, ttUnsignedShort, 1 },
        { 13, ttUnsignedByte,  1 }
    }
Nikon ISO info binary array - definition.
nikonIsoExpansion
const TagDetails Exiv2::Internal::nikonIsoExpansion[] extern
Initial value:
= {
        { 0x000, N_("Off")    },
        { 0x101, N_("Hi 0.3") },
        { 0x102, N_("Hi 0.5") },
        { 0x103, N_("Hi 0.7") },
        { 0x104, N_("Hi 1.0") },
        { 0x105, N_("Hi 1.3") },
        { 0x106, N_("Hi 1.5") },
        { 0x107, N_("Hi 1.7") },
        { 0x108, N_("Hi 2.0") },
        { 0x109, N_("Hi 2.3") },
        { 0x10a, N_("Hi 2.5") },
        { 0x10b, N_("Hi 2.7") },
        { 0x10c, N_("Hi 3.0") },
        { 0x10d, N_("Hi 3.3") },
        { 0x10e, N_("Hi 3.5") },
        { 0x10f, N_("Hi 3.7") },
        { 0x110, N_("Hi 4.0") },
        { 0x111, N_("Hi 4.3") },
        { 0x112, N_("Hi 4.5") },
        { 0x113, N_("Hi 4.7") },
        { 0x114, N_("Hi 5.0") },
        { 0x201, N_("Lo 0.3") },
        { 0x202, N_("Lo 0.5") },
        { 0x203, N_("Lo 0.7") },
        { 0x204, N_("Lo 1.0") }
    }
ISOExpansion, tag index 4 and 10.
nikonLd1Cfg
const ArrayCfg Exiv2::Internal::nikonLd1Cfg extern
Initial value:
= {
        nikonLd1Id,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        false,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Lens Data binary array - configuration 1.
nikonLd2Cfg
const ArrayCfg Exiv2::Internal::nikonLd2Cfg extern
Initial value:
= {
        nikonLd2Id,
        invalidByteOrder,
        ttUndefined,
        nikonCrypt,
        false,
        true,
        false,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Lens Data binary array - configuration 2.
nikonLd3Cfg
const ArrayCfg Exiv2::Internal::nikonLd3Cfg extern
Initial value:
= {
        nikonLd3Id,
        invalidByteOrder,
        ttUndefined,
        nikonCrypt,
        false,
        true,
        false,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Lens Data binary array - configuration 3.
nikonLd4Cfg
const ArrayCfg Exiv2::Internal::nikonLd4Cfg extern
Initial value:
= {
        nikonLd4Id,
        invalidByteOrder,
        ttUndefined,
        nikonCrypt,
        false,
        true,
        false,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Lens Data binary array - configuration 3.
nikonLd4Def
const ArrayDef Exiv2::Internal::nikonLd4Def[] extern
Initial value:
= {
        { 0, ttUndefined, 4 },
        { 48, ttUnsignedShort, 1 },
        { 54, ttUnsignedShort, 1 },
        { 56, ttUnsignedShort, 1 },
        { 60, ttUnsignedShort, 1 }
    }
Nikon Lens Data binary array - definition.
nikonLdDef
const ArrayDef Exiv2::Internal::nikonLdDef[] extern
Initial value:
= {
        { 0, ttUndefined, 4 }
    }
Nikon Lens Data binary array - definition.
nikonLdSet
const ArraySet Exiv2::Internal::nikonLdSet[] extern
Initial value:
= {
        { nikonLd1Cfg, nikonLdDef, EXV_COUNTOF(nikonLdDef) },
        { nikonLd2Cfg, nikonLdDef, EXV_COUNTOF(nikonLdDef) },
        { nikonLd3Cfg, nikonLdDef, EXV_COUNTOF(nikonLdDef) },
        { nikonLd4Cfg, nikonLd4Def, EXV_COUNTOF(nikonLd4Def) }
    }
Nikon Lens Data configurations and definitions.
nikonMeCfg
const ArrayCfg Exiv2::Internal::nikonMeCfg extern
Initial value:
= {
        nikonMeId,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Multi Exposure binary array - configuration.
nikonMeDef
const ArrayDef Exiv2::Internal::nikonMeDef[] extern
Initial value:
= {
        {  0, ttUndefined,     4 },
        {  4, ttUnsignedLong,  1 },
        {  8, ttUnsignedLong,  1 },
        { 12, ttUnsignedLong,  1 }
    }
Nikon Multi Exposure binary array - definition.
nikonMultiExposureMode
const TagDetails Exiv2::Internal::nikonMultiExposureMode[] extern
Initial value:
= {
        { 0, N_("Off")               },
        { 1, N_("Multiple Exposure") },
        { 2, N_("Image Overlay")     }
    }
MultiExposureMode.
nikonNefCompression
const TagDetails Exiv2::Internal::nikonNefCompression[] extern
Initial value:
= {
        {  1, N_("Lossy (type 1)") },
        {  2, N_("Uncompressed")   },
        {  3, N_("Lossless")       },
        {  4, N_("Lossy (type 2)") }
    }
NEFCompression, tag 0x0093.
nikonOffOn
const TagDetails Exiv2::Internal::nikonOffOn[] extern
Initial value:
= {
        {  0, N_("Off") },
        {  1, N_("On")  }
    }
OffOn, multiple tags.
nikonOffOn2
const TagDetails Exiv2::Internal::nikonOffOn2[] extern
Initial value:
= {
        { 0, N_("Off")    },
        { 1, N_("On (1)") },
        { 2, N_("On (2)") },
        { 3, N_("On (3)") }
    }
VibrationReduction.
nikonOffOn3
const TagDetails Exiv2::Internal::nikonOffOn3[] extern
Initial value:
= {
        { 0x0, N_("n/a") },
        { 0xc, N_("Off") },
        { 0xf, N_("On")  }
    }
VibrationReduction2.
nikonOlnh
const TagDetails Exiv2::Internal::nikonOlnh[] extern
Initial value:
= {
        {  0, N_("Off")    },
        {  1, N_("Low")    },
        {  3, N_("Normal") },
        {  5, N_("High")   }
    }
Off, Low, Normal, High, multiple tags.
nikonOnOff
const TagDetails Exiv2::Internal::nikonOnOff[] extern
Initial value:
= {
        {  1, N_("On")  },
        {  2, N_("Off") }
    }
OnOff.
nikonPcCfg
const ArrayCfg Exiv2::Internal::nikonPcCfg extern
Initial value:
= {
        nikonPcId,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Picture Control binary array - configuration.
nikonPcDef
const ArrayDef Exiv2::Internal::nikonPcDef[] extern
Initial value:
= {
        {  0, ttUndefined,     4 },
        {  4, ttAsciiString,  20 },
        { 24, ttAsciiString,  20 },
        { 48, ttUnsignedByte,  1 },
        { 49, ttUnsignedByte,  1 },
        { 50, ttUnsignedByte,  1 },
        { 51, ttUnsignedByte,  1 },
        { 52, ttUnsignedByte,  1 },
        { 53, ttUnsignedByte,  1 },
        { 54, ttUnsignedByte,  1 },
        { 55, ttUnsignedByte,  1 },
        { 56, ttUnsignedByte,  1 },
        { 57, ttUnsignedByte,  1 }
    }
Nikon Picture Control binary array - definition.
nikonPhaseDetectAF
const TagDetails Exiv2::Internal::nikonPhaseDetectAF[] extern
Initial value:
= {
        { 0, N_("Off")                },
        { 1, N_("On (51-point)")      },
        { 2, N_("On (11-point)")      },
        { 3, N_("On (39-point)")      },
        { 4, N_("On (73-point)")      },
        { 5, N_("On (73-point, new)") },
        { 6, N_("On (105-point)")     },
        { 7, N_("On (153-point)")     },
    }
PhaseDetectAF.
nikonRetouchHistory
const TagDetails Exiv2::Internal::nikonRetouchHistory[] extern
Initial value:
= {
        {  0, N_("None")          },
        {  3, N_("B & W")         },
        {  4, N_("Sepia")         },
        {  5, N_("Trim")          },
        {  6, N_("Small picture") },
        {  7, N_("D-Lighting")    },
        {  8, N_("Red eye")       },
        {  9, N_("Cyanotype")     },
        { 10, N_("Sky light")     },
        { 11, N_("Warm tone")     },
        { 12, N_("Color custom")  },
        { 13, N_("Image overlay") }
    }
RetouchHistory, tag 0x009e.
Referenced by Exiv2::Internal::Nikon3MakerNote::print0x009e().
nikonShootingMode
const TagDetailsBitmask Exiv2::Internal::nikonShootingMode[] extern
Initial value:
= {
        { 0x0001, N_("Continuous")               },
        { 0x0002, N_("Delay")                    },
        { 0x0004, N_("PC Control")               },
        { 0x0008, N_("Self-timer")               },
        { 0x0010, N_("Exposure Bracketing")      },
        { 0x0020, N_("Auto ISO")                 },
        { 0x0040, N_("White-Balance Bracketing") },
        { 0x0080, N_("IR Control")               },
        { 0x0100, N_("D-Lighting Bracketing")    }
    }
ShootingMode, tag 0x0089.
Referenced by Exiv2::Internal::Nikon3MakerNote::print0x0089().
nikonShootingModeD70
const TagDetailsBitmask Exiv2::Internal::nikonShootingModeD70[] extern
Initial value:
= {
        { 0x0001, N_("Continuous")               },
        { 0x0002, N_("Delay")                    },
        { 0x0004, N_("PC control")               },
        { 0x0010, N_("Exposure bracketing")      },
        { 0x0020, N_("Unused LE-NR slowdown") },
        { 0x0040, N_("White balance bracketing") },
        { 0x0080, N_("IR control")               }
    }
ShootingMode D70, tag 0x0089.
Referenced by Exiv2::Internal::Nikon3MakerNote::print0x0089().
nikonShutterModes
const TagDetails Exiv2::Internal::nikonShutterModes[] extern
Initial value:
= {
        { 0, "Mechanical" },
        { 16, "Electronic" },
        { 48, "Electronic Front Curtain" },
        { 64, "Electronic (Movie)" },
        { 80, "Auto (Mechanical)" },
        { 81, "Auto (Electronic Front Curtain)" }
    }
Shutter Modes (credits to exiftool)
nikonSi1Cfg
const ArrayCfg Exiv2::Internal::nikonSi1Cfg extern
Initial value:
= {
        nikonSi1Id,
        bigEndian,
        ttUndefined,
        nikonCrypt,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Shot Info binary array - configuration 1 (D80)
nikonSi1Def
const ArrayDef Exiv2::Internal::nikonSi1Def[] extern
Initial value:
= {
        {    0, ttUndefined,    4 },
        {  586, ttUnsignedLong, 1 },
        { 1155, ttUnsignedByte, 1 }
    }
Nikon Shot Info binary array - definition 1 (D80)
nikonSi2Cfg
const ArrayCfg Exiv2::Internal::nikonSi2Cfg extern
Initial value:
= {
        nikonSi2Id,
        bigEndian,
        ttUndefined,
        nikonCrypt,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Shot Info binary array - configuration 2 (D40)
nikonSi2Def
const ArrayDef Exiv2::Internal::nikonSi2Def[] extern
Initial value:
= {
        {    0, ttUndefined,    4 },
        {  582, ttUnsignedLong, 1 },
        {  738, ttUnsignedByte, 1 },
        { 1112, ttUnsignedByte, 1 }
    }
Nikon Shot Info binary array - definition 2 (D40)
nikonSi3Cfg
const ArrayCfg Exiv2::Internal::nikonSi3Cfg extern
Initial value:
= {
        nikonSi3Id,
        bigEndian,
        ttUndefined,
        nikonCrypt,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Shot Info binary array - configuration 3 (D300a)
nikonSi3Def
const ArrayDef Exiv2::Internal::nikonSi3Def[] extern
Initial value:
= {
        {    0, ttUndefined,     4 },
        {  604, ttUnsignedByte,  1 },
        {  633, ttUnsignedLong,  1 },
        {  721, ttUnsignedShort, 1 },
        {  814, ttUndefined,  4478 }
    }
Nikon Shot Info binary array - definition 3 (D300a)
nikonSi4Cfg
const ArrayCfg Exiv2::Internal::nikonSi4Cfg extern
Initial value:
= {
        nikonSi4Id,
        bigEndian,
        ttUndefined,
        nikonCrypt,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Shot Info binary array - configuration 4 (D300b)
nikonSi4Def
const ArrayDef Exiv2::Internal::nikonSi4Def[] extern
Initial value:
= {
        {    0, ttUndefined,     4 },
        {  644, ttUnsignedLong,  1 },
        {  732, ttUnsignedShort, 1 },
        {  826, ttUndefined,  4478 }
    }
Nikon Shot Info binary array - definition 4 (D300b)
nikonSi5Cfg
const ArrayCfg Exiv2::Internal::nikonSi5Cfg extern
Initial value:
= {
        nikonSi5Id,
        bigEndian,
        ttUndefined,
        nikonCrypt,
        false,
        false,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Shot Info binary array - configuration 5 (ver 02.xx)
nikonSi5Def
const ArrayDef Exiv2::Internal::nikonSi5Def[] extern
Initial value:
= {
        {    0, ttUndefined,     4 },
        {  106, ttUnsignedLong,  1 },
        {  110, ttUnsignedLong,  1 },
        {  117, ttUnsignedByte,  1 },
        {  130, ttUnsignedByte,  1 },
        {  343, ttUndefined,     2 },
        {  430, ttUnsignedByte,  1 },
        {  598, ttUnsignedByte,  1 },
        {  630, ttUnsignedLong,  1 }
    }
Nikon Shot Info binary array - definition 5 (ver 01.xx and ver 02.xx)
nikonSi6Cfg
const ArrayCfg Exiv2::Internal::nikonSi6Cfg extern
Initial value:
= {
        nikonSi6Id,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Shot Info binary array - configuration 6 (ver 01.xx)
nikonSiSet
const ArraySet Exiv2::Internal::nikonSiSet[] extern
Initial value:
= {
        { nikonSi1Cfg, nikonSi1Def, EXV_COUNTOF(nikonSi1Def) },
        { nikonSi2Cfg, nikonSi2Def, EXV_COUNTOF(nikonSi2Def) },
        { nikonSi3Cfg, nikonSi3Def, EXV_COUNTOF(nikonSi3Def) },
        { nikonSi4Cfg, nikonSi4Def, EXV_COUNTOF(nikonSi4Def) },
        { nikonSi5Cfg, nikonSi5Def, EXV_COUNTOF(nikonSi5Def) },
        { nikonSi6Cfg, nikonSi5Def, EXV_COUNTOF(nikonSi5Def) }
    }
Nikon Lens Data configurations and definitions.
nikonToningEffect
const TagDetails Exiv2::Internal::nikonToningEffect[] extern
Initial value:
= {
        { 0x80, N_("B&W")         },
        { 0x81, N_("Sepia")       },
        { 0x82, N_("Cyanotype")   },
        { 0x83, N_("Red")         },
        { 0x84, N_("Yellow")      },
        { 0x85, N_("Green")       },
        { 0x86, N_("Blue-green")  },
        { 0x87, N_("Blue")        },
        { 0x88, N_("Purple-blue") },
        { 0x89, N_("Red-purple")  },
        { 0xff, N_("n/a")         }
    }
ToningEffect.
nikonVrCfg
const ArrayCfg Exiv2::Internal::nikonVrCfg extern
Initial value:
= {
        nikonVrId,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon Vibration Reduction binary array - configuration.
nikonVrDef
const ArrayDef Exiv2::Internal::nikonVrDef[] extern
Initial value:
= {
        { 0, ttUndefined,     4 },
        { 7, ttUnsignedByte,  1 }
    }
Nikon Vibration Reduction binary array - definition.
nikonWtCfg
const ArrayCfg Exiv2::Internal::nikonWtCfg extern
Initial value:
= {
        nikonWtId,
        invalidByteOrder,
        ttUndefined,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedByte,  1 }
    }
Nikon World Time binary array - configuration.
nikonWtDef
const ArrayDef Exiv2::Internal::nikonWtDef[] extern
Initial value:
= {
        { 0, ttSignedShort,   1 },
        { 2, ttUnsignedByte,  1 },
        { 3, ttUnsignedByte,  1 }
    }
Nikon World Time binary array - definition.
nikonYesNo
const TagDetails Exiv2::Internal::nikonYesNo[] extern
Initial value:
= {
        { 0, N_("No")    },
        { 1, N_("Yes")   }
    }
YesNo, used for DaylightSavings, tag index 2.
olympusAFSearch
const TagDetails Exiv2::Internal::olympusAFSearch[] extern
Initial value:
= {
        { 0, N_("Not Ready") },
        { 1, N_("Ready")     }
    }
AFSearch, tag 0x0303.
olympusCCDScanMode
const TagDetails Exiv2::Internal::olympusCCDScanMode[] extern
Initial value:
= {
        {  0, N_("Interlaced")  },
        {  1, N_("Progressive") }
    }
CCDScanMode, tag 0x1039.
olympusColorSpace
const TagDetails Exiv2::Internal::olympusColorSpace[] extern
Initial value:
= {
        { 0, N_("sRGB")          },
        { 1, N_("Adobe RGB")     },
        { 2, N_("Pro Photo RGB") }
    }
ColorSpace, tag 0x0507.
olympusContrast
const TagDetails Exiv2::Internal::olympusContrast[] extern
Initial value:
= {
        { 0, N_("High")   },
        { 1, N_("Normal") },
        { 2, N_("Low")    }
    }
Contrast, tag 0x1029.
olympusCsFocusMode
const TagDetails Exiv2::Internal::olympusCsFocusMode[] extern
Initial value:
= {
        { 0, N_("Single AF")              },
        { 1, N_("Sequential shooting AF") },
        { 2, N_("Continuous AF")          },
        { 3, N_("Multi AF")               },
        { 10, N_("MF")                    }
    }
FocusMode, tag 0x0301.
olympusCsQuality
const TagDetails Exiv2::Internal::olympusCsQuality[] extern
Initial value:
= {
        { 1, N_("SQ")  },
        { 2, N_("HQ")  },
        { 3, N_("SHQ") },
        { 4, N_("RAW") }
    }
OlympusCs Quality, tag 0x0603.
olympusEqFlashModel
const TagDetails Exiv2::Internal::olympusEqFlashModel[] extern
Initial value:
= {
        { 0, N_("None") },
        { 1, "FL-20"    },
        { 2, "FL-50"    },
        { 3, "RF-11"    },
        { 4, "TF-22"    },
        { 5, "FL-36"    },
        { 6, "FL-50R"   },
        { 7, "FL-36R"   },
        { 9, "FL-14"    },
        {11, "FL-600R"  },
        {11, "FL-600R"  }
    }
OlympusEq FlashModel, tag 0x1001.
olympusEqFlashType
const TagDetails Exiv2::Internal::olympusEqFlashType[] extern
Initial value:
= {
        { 0, N_("None")            },
        { 2, N_("Simple E-System") },
        { 3, N_("E-System")        }
    }
OlympusEq FlashType, tag 0x1000.
olympusExposureMode
const TagDetails Exiv2::Internal::olympusExposureMode[] extern
Initial value:
= {
        { 1, N_("Manual")                    },
        { 2, N_("Program")                   },
        { 3, N_("Aperture-priority AE")      },
        { 4, N_("Shutter speed priority AE") },
        { 5, N_("Program-shift")             }
    }
ExposureMode, tag 0x0200.
olympusFiExternalFlashBounce
const TagDetails Exiv2::Internal::olympusFiExternalFlashBounce[] extern
Initial value:
= {
        { 0, N_("Bounce or Off") },
        { 1, N_("Direct") }
    }
OlympusFi ExternalFlashBounce, tag 0x1204.
olympusFlashControlMode
const TagDetails Exiv2::Internal::olympusFlashControlMode[] extern
Initial value:
= {
        { 0, N_("Off")     },
        { 3, N_("TTL")     },
        { 4, N_("Auto")    },
        { 5, N_("Manual")  }
    }
FlashControlMode, tag 0x0404.
olympusFlashDevice
const TagDetails Exiv2::Internal::olympusFlashDevice[] extern
Initial value:
= {
        {  0, N_("None")                },
        {  1, N_("Internal")            },
        {  4, N_("External")            },
        {  5, N_("Internal + External") }
    }
FlashDevice, tag 0x1005.
olympusFlashMode
const TagDetailsBitmask Exiv2::Internal::olympusFlashMode[] extern
Initial value:
= {
        { 0x0000, N_("Off")         },
        { 0x0001, N_("On")          },
        { 0x0002, N_("Fill-in")     },
        { 0x0004, N_("Red-eye")     },
        { 0x0008, N_("Slow-sync")   },
        { 0x0010, N_("Forced On")   },
        { 0x0020, N_("2nd Curtain") }
    }
FlashMode, tag 0x0400.
olympusFlashRemoteControl
const TagDetails Exiv2::Internal::olympusFlashRemoteControl[] extern
Initial value:
= {
        {  0x0, N_("Off")              },
        {  0x1, N_("Channel 1, Low")   },
        {  0x2, N_("Channel 2, Low")   },
        {  0x3, N_("Channel 3, Low")   },
        {  0x4, N_("Channel 4, Low")   },
        {  0x9, N_("Channel 1, Mid")   },
        {  0xa, N_("Channel 2, Mid")   },
        {  0xb, N_("Channel 3, Mid")   },
        {  0xc, N_("Channel 4, Mid")   },
        { 0x11, N_("Channel 1, High")  },
        { 0x12, N_("Channel 2, High")  },
        { 0x13, N_("Channel 3, High")  },
        { 0x14, N_("Channel 4, High")  }
    }
FlashRemoteControl, tag 0x0403.
olympusFocusMode
const TagDetails Exiv2::Internal::olympusFocusMode[] extern
Initial value:
= {
        {  0, N_("Auto")   },
        {  1, N_("Manual") }
    }
FocusMode, tag 0x100b.
olympusFocusProcess
const TagDetails Exiv2::Internal::olympusFocusProcess[] extern
Initial value:
= {
        { 0, N_("AF Not Used") },
        { 1, N_("AF Used")     }
    }
FocusProcess, tag 0x0302.
olympusFocusRange
const TagDetails Exiv2::Internal::olympusFocusRange[] extern
Initial value:
= {
        {  0, N_("Normal")   },
        {  1, N_("Macro") }
    }
FocusRange, tag 0x100a.
olympusImageStabilization
const TagDetails Exiv2::Internal::olympusImageStabilization[] extern
Initial value:
= {
        { 0, N_("Off")        },
        { 1, N_("On, Mode 1") },
        { 2, N_("On, Mode 2") },
        { 3, N_("On, Mode 3") }
    }
Olympus ImageStabilization, tag 0x0604.
olympusIpAspectRatio
const TagDetails Exiv2::Internal::olympusIpAspectRatio[] extern
Initial value:
= {
        { 1, "4:3"  },
        { 2, "3:2"  },
        { 3, "16:9" },
        { 4, "6:6"  },
        { 5, "5:4"  },
        { 6, "7:6"  },
        { 7, "6:5"  },
        { 8, "7:5"  },
        { 9, "3:4"  }
    }
OlympusIp olympusIpAspectRatio, tag 0x101c.
olympusIpMultipleExposureMode
const TagDetails Exiv2::Internal::olympusIpMultipleExposureMode[] extern
Initial value:
= {
        { 0, N_("Off")             },
        { 2, N_("On (2 frames)")   },
        { 3, N_("On (3 frames)")   }
    }
OlympusIp MultipleExposureMode, tag 0x101c.
olympusMacro
const TagDetails Exiv2::Internal::olympusMacro[] extern
Initial value:
= {
        {  0, N_("Off")         },
        {  1, N_("On")          },
        {  2, N_("Super macro") }
    }
Macro, tag 0x0202.
olympusMacroMode
const TagDetails Exiv2::Internal::olympusMacroMode[] extern
Initial value:
= {
        { 0, N_("Off")         },
        { 1, N_("On")          },
        { 2, N_("Super Macro") }
    }
MacroMode, tag 0x0300.
olympusMeteringMode
const TagDetails Exiv2::Internal::olympusMeteringMode[] extern
Initial value:
= {
        {    2, N_("Center-weighted average") },
        {    3, N_("Spot")                    },
        {    5, N_("ESP")                     },
        {  261, N_("Pattern+AF")              },
        {  515, N_("Spot+Highlight control")  },
        { 1027, N_("Spot+Shadow control")     }
    }
MeteringMode, tag 0x0202.
olympusModifiedSaturation
const TagDetails Exiv2::Internal::olympusModifiedSaturation[] extern
Initial value:
= {
        { 0, N_("Off")                 },
        { 1, N_("CM1 (Red Enhance)")   },
        { 2, N_("CM2 (Green Enhance)") },
        { 3, N_("CM3 (Blue Enhance)")  },
        { 4, N_("CM4 (Skin Tones)")    }
    }
ModifiedSaturation, tag 0x0504.
olympusNoiseReduction
const TagDetailsBitmask Exiv2::Internal::olympusNoiseReduction[] extern
Initial value:
= {
        { 0x0001, N_("Noise Reduction")          },
        { 0x0002, N_("Noise Filter")             },
        { 0x0004, N_("Noise Filter (ISO Boost)") },
        { 0x0008, N_("Auto")                     }
    }
NoiseReduction, tag 0x050a.
olympusNoYes
const TagDetails Exiv2::Internal::olympusNoYes[] extern
Initial value:
= {
        {  0, N_("No") },
        {  1, N_("Yes")  }
    }
NoYes, multiple tags.
olympusOffOn
const TagDetails Exiv2::Internal::olympusOffOn[] extern
Initial value:
= {
        {  0, N_("Off") },
        {  1, N_("On")  }
    }
OffOn, multiple tags.
olympusOneTouchWb
const TagDetails Exiv2::Internal::olympusOneTouchWb[] extern
Initial value:
= {
        {  0, N_("Off")         },
        {  1, N_("On")          },
        {  2, N_("On (preset)") }
    }
OneTouchWB, tag 0x0302.
olympusPictureMode
const TagDetails Exiv2::Internal::olympusPictureMode[] extern
Initial value:
= {
        {   1, N_("Vivid")                },
        {   2, N_("Natural")              },
        {   3, N_("Muted")                },
        {   4, N_("Portrait")             },
        {   5, N_("i-Enhance")            },
        {   6, N_("e-Portrait")           },
        {   7, N_("Color Creator")        },
        {   9, N_("Color Profile 1")      },
        {  10, N_("Color Profile 2")      },
        {  11, N_("Color Profile 3")      },
        {  12, N_("Monochrome Profile 1") },
        {  13, N_("Monochrome Profile 2") },
        {  14, N_("Monochrome Profile 3") },
        { 256, N_("Monotone")             },
        { 512, N_("Sepia")                }
    }
PictureMode, tag 0x0520.
olympusPictureModeBWFilter
const TagDetails Exiv2::Internal::olympusPictureModeBWFilter[] extern
Initial value:
= {
        { 0, N_("n/a")     },
        { 1, N_("Neutral") },
        { 2, N_("Yellow")  },
        { 3, N_("Orange")  },
        { 4, N_("Red")     },
        { 5, N_("Green")   }
    }
PictureModeBWFilter, tag 0x0525.
olympusPictureModeTone
const TagDetails Exiv2::Internal::olympusPictureModeTone[] extern
Initial value:
= {
        { 0, N_("n/a")     },
        { 1, N_("Neutral") },
        { 2, N_("Sepia")   },
        { 3, N_("Blue")    },
        { 4, N_("Purple")  },
        { 5, N_("Green")   }
    }
PictureModeTone, tag 0x0526.
olympusQuality
const TagDetails Exiv2::Internal::olympusQuality[] extern
Initial value:
= {
        { 1, N_("Standard Quality (SQ)")    },
        { 2, N_("High Quality (HQ)")        },
        { 3, N_("Super High Quality (SHQ)") },
        { 6, N_("Raw")                      }
    }
Quality, tag 0x0201.
olympusRd2ColorSpace
const TagDetails Exiv2::Internal::olympusRd2ColorSpace[] extern
Initial value:
= {
        { 0, N_("sRGB")          },
        { 1, N_("Adobe RGB")     },
        { 2, N_("Pro Photo RGB") }
    }
OlympusRd2 ColorSpace, tag 0x0109.
olympusRd2Engine
const TagDetails Exiv2::Internal::olympusRd2Engine[] extern
Initial value:
= {
        { 0, N_("High Speed")    },
        { 1, N_("High Function") }
    }
OlympusRd2 Engine, tag 0x010b.
olympusRd2PictureMode
const TagDetails Exiv2::Internal::olympusRd2PictureMode[] extern
Initial value:
= {
        {   1, N_("Vivid")    },
        {   2, N_("Natural")  },
        {   3, N_("Muted")    },
        { 256, N_("Monotone") },
        { 512, N_("Sepia")    }
    }
OlympusRd2 PictureMode, tag 0x010c.
olympusRd2PM_BWFilter
const TagDetails Exiv2::Internal::olympusRd2PM_BWFilter[] extern
Initial value:
= {
        { 1, N_("Neutral") },
        { 2, N_("Yellow")  },
        { 3, N_("Orange")  },
        { 4, N_("Red")     },
        { 5, N_("Green")   }
    }
OlympusRd2 PM_BWFilter, tag 0x0110.
olympusRd2PMPictureTone
const TagDetails Exiv2::Internal::olympusRd2PMPictureTone[] extern
Initial value:
= {
        { 1, N_("Neutral") },
        { 2, N_("Sepia")   },
        { 3, N_("Blue")    },
        { 4, N_("Purple")  },
        { 5, N_("Green")   }
    }
OlympusRd2 PMPictureTone, tag 0x0111.
olympusRd2WhiteBalance
const TagDetails Exiv2::Internal::olympusRd2WhiteBalance[] extern
Initial value:
= {
        { 1, N_("Color Temperature") },
        { 2, N_("Gray Point")        }
    }
OlympusRd2 WhiteBalance, tag 0x0101.
olympusRdColorSpace
const TagDetails Exiv2::Internal::olympusRdColorSpace[] extern
Initial value:
= {
        { 0, N_("sRGB")          },
        { 1, N_("Adobe RGB")     },
        { 2, N_("Pro Photo RGB") }
    }
OlympusRd ColorSpace, tag 0x0108.
olympusRdEditStatus
const TagDetails Exiv2::Internal::olympusRdEditStatus[] extern
Initial value:
= {
        { 0, N_("Original")           },
        { 1, N_("Edited (Landscape)") },
        { 6, N_("Edited (Portrait)")  },
        { 8, N_("Edited (Portrait)")  }
    }
OlympusRd EditStatus, tag 0x010b.
olympusRdEngine
const TagDetails Exiv2::Internal::olympusRdEngine[] extern
Initial value:
= {
        { 0, N_("High Speed")             },
        { 1, N_("High Function")          },
        { 2, N_("Advanced High Speed")    },
        { 3, N_("Advanced High Function") }
    }
OlympusRd Engine, tag 0x0109.
olympusRdSettings
const TagDetailsBitmask Exiv2::Internal::olympusRdSettings[] extern
Initial value:
= {
        { 0x0001, N_("WB Color Temp")   },
        { 0x0004, N_("WB Gray Point")   },
        { 0x0008, N_("Saturation")      },
        { 0x0010, N_("Contrast")        },
        { 0x0020, N_("Sharpness")       },
        { 0x0040, N_("Color Space")     },
        { 0x0080, N_("High Function")   },
        { 0x0100, N_("Noise Reduction") }
    }
OlympusRd Settings, tag 0x010c.
olympusRiLightSource
const TagDetails Exiv2::Internal::olympusRiLightSource[] extern
Initial value:
= {
        {   0, N_("Unknown")                                 },
        {  16, N_("Shade")                                   },
        {  17, N_("Cloudy")                                  },
        {  18, N_("Fine Weather")                            },
        {  20, N_("Tungsten (incandescent)")                 },
        {  22, N_("Evening Sunlight")                        },
        {  33, N_("Daylight Fluorescent (D 5700 - 7100K)")   },
        {  34, N_("Day White Fluorescent (N 4600 - 5400K)")  },
        {  35, N_("Cool White Fluorescent (W 3900 - 4500K)") },
        {  36, N_("White Fluorescent (WW 3200 - 3700K)")     },
        { 256, N_("One Touch White Balance")                 },
        { 512, N_("Custom 1-4")                              }
    }
OlympusRi LightSource, tag 0x1000.
olympusSharpness
const TagDetails Exiv2::Internal::olympusSharpness[] extern
Initial value:
= {
        { 0, N_("Normal") },
        { 1, N_("Hard")   },
        { 2, N_("Soft")   }
    }
Sharpness, tag 0x100f.
olympusWhiteBalance
const TagDetails Exiv2::Internal::olympusWhiteBalance[] extern
Initial value:
= {
        {   0, N_("Auto")                              },
        {   1, N_("Auto (Keep Warm Color Off")         },
        {  16, N_("7500K (Fine Weather with Shade)")   },
        {  17, N_("6000K (Cloudy)")                    },
        {  18, N_("5300K (Fine Weather)")              },
        {  20, N_("3000K (Tungsten light)")            },
        {  21, N_("3600K (Tungsten light-like)")       },
        {  22, N_("Auto Setup")                        },
        {  23, N_("5500K (Flash)")                     },
        {  33, N_("6600K (Daylight fluorescent)")      },
        {  34, N_("4500K (Neutral white fluorescent)") },
        {  35, N_("4000K (Cool white fluorescent)")    },
        {  36, N_("White Fluorescent")                 },
        {  48, N_("3600K (Tungsten light-like)")       },
        {  67, N_("Underwater")                        },
        { 256, N_("One Touch WB 1")                    },
        { 257, N_("One Touch WB 2")                    },
        { 258, N_("One Touch WB 3")                    },
        { 259, N_("One Touch WB 4")                    },
        { 512, N_("Custom WB 1")                       },
        { 513, N_("Custom WB 2")                       },
        { 514, N_("Custom WB 3")                       },
        { 515, N_("Custom WB 4")                       }
    }
WhiteBalance, tag 0x0500.
panasonicAFAssistLamp
const TagDetails Exiv2::Internal::panasonicAFAssistLamp[] extern
Initial value:
= {
        { 1, N_("Fired")                     },
        { 2, N_("Enabled but Not Used")      },
        { 3, N_("Disabled but Required")     },
        { 4, N_("Disabled and Not Required") }
    }
AFAssistLamp, tag 0x0031.
panasonicAudio
const TagDetails Exiv2::Internal::panasonicAudio[] extern
Initial value:
= {
        { 1, N_("Yes")    },
        { 2, N_("No")     },
        { 3, N_("Stereo") }
    }
Audio, tag 0x0020.
panasonicBracketSettings
const TagDetails Exiv2::Internal::panasonicBracketSettings[] extern
Initial value:
= {
        { 0, N_("No Bracket")               },
        { 1, N_("3 images, Sequence 0/-/+") },
        { 2, N_("3 images, Sequence -/0/+") },
        { 3, N_("5 images, Sequence 0/-/+") },
        { 4, N_("5 images, Sequence -/0/+") },
        { 5, N_("7 images, Sequence 0/-/+") },
        { 6, N_("7 images, Sequence -/0/+") }
    }
Bracket Settings, tag 0x0045.
panasonicBurstMode
const TagDetails Exiv2::Internal::panasonicBurstMode[] extern
Initial value:
= {
        { 0, N_("Off")              },
        { 1, N_("Low/High quality") },
        { 2, N_("Infinite")         }
    }
BustMode, tag 0x002a.
panasonicCameraOrientation
const TagDetails Exiv2::Internal::panasonicCameraOrientation[] extern
Initial value:
= {
        { 0, N_("Normal")         },
        { 1, N_("Rotate CW")      },
        { 2, N_("Rotate 180")     },
        { 3, N_("Rotate CCW")     },
        { 4, N_("Tilt upwards")   },
        { 5, N_("Tilt downwards") }
    }
Camera orientation, tag 0x008f.
panasonicClearRetouch
const TagDetails Exiv2::Internal::panasonicClearRetouch[] extern
Initial value:
= {
        { 0, N_("Off") },
        { 1, N_("On") }
    }
Clear Retouch, tag 0x007c.
panasonicColorEffect
const TagDetails Exiv2::Internal::panasonicColorEffect[] extern
Initial value:
= {
        { 1, N_("Off")             },
        { 2, N_("Warm")            },
        { 3, N_("Cool")            },
        { 4, N_("Black and white") },
        { 5, N_("Sepia")           },
        { 6, N_("Happy")           }
    }
ColorEffect, tag 0x0028.
panasonicColorMode
const TagDetails Exiv2::Internal::panasonicColorMode[] extern
Initial value:
= {
        { 0, N_("Normal")  },
        { 1, N_("Natural") },
        { 2, N_("Vivid")   }
    }
ColorMode, tag 0x0032.
panasonicContrast
const TagDetails Exiv2::Internal::panasonicContrast[] extern
Initial value:
= {
        {   0, N_("Normal")      },
        {   1, N_("Low")         },
        {   2, N_("High")        },
        {   6, N_("Medium low")  },
        {   7, N_("Medium high") },
        { 256, N_("Low")         },
        { 272, N_("Standard")    },
        { 288, N_("High")        },
        { 288, N_("High")        }
    }
Contrast, tag 0x002c.
panasonicConversionLens
const TagDetails Exiv2::Internal::panasonicConversionLens[] extern
Initial value:
= {
        { 1, N_("Off")       },
        { 2, N_("Wide")      },
        { 3, N_("Telephoto") },
        { 4, N_("Macro")     },
        { 4, N_("Macro")     }
    }
ConversionLens, tag 0x0035.
panasonicFilmMode
const TagDetails Exiv2::Internal::panasonicFilmMode[] extern
Initial value:
= {
        {  1, N_("Standard (color)") },
        {  2, N_("Dynamic (color)")  },
        {  3, N_("Nature (color)")   },
        {  4, N_("Smooth (color)")   },
        {  5, N_("Standard (B&W)")   },
        {  6, N_("Dynamic (B&W)")    },
        {  7, N_("Smooth (B&W)")     },
        { 10, N_("Nostalgic")        },
        { 11, N_("Vibrant")          }
    }
FilmMode, tag 0x0042.
panasonicFlashCurtain
const TagDetails Exiv2::Internal::panasonicFlashCurtain[] extern
Initial value:
= {
        { 0, N_("n/a") },
        { 1, N_("1st") },
        { 2, N_("2nd") }
    }
Flash curtain, tag 0x0048.
panasonicFlashFired
const TagDetails Exiv2::Internal::panasonicFlashFired[] extern
Initial value:
= {
        { 1, N_("No")  },
        { 2, N_("Yes") }
    }
Flash Fired, tag 0x8007.
panasonicFlashWarning
const TagDetails Exiv2::Internal::panasonicFlashWarning[] extern
Initial value:
= {
        { 0, N_("No")                               },
        { 1, N_("Yes (flash required but disabled") }
    }
Flash warning, tag 0x0062.
panasonicFocusMode
const TagDetails Exiv2::Internal::panasonicFocusMode[] extern
Initial value:
= {
        {  1, N_("Auto")               },
        {  2, N_("Manual")             },
        {  4, N_("Auto, focus button") },
        {  5, N_("Auto, continuous")   },
        {  6, N_("AF-S")               },
        {  7, N_("AF-C")               },
        {  8, N_("AF-F")               }
    }
FocusMode, tag 0x0007.
panasonicHDR
const TagDetails Exiv2::Internal::panasonicHDR[] extern
Initial value:
= {
        {     0, N_("Off")         },
        {   100, N_("1 EV")        },
        {   200, N_("2 EV")        },
        {   300, N_("3 EV")        },
        { 32868, N_("1 EV (Auto)") },
        { 32968, N_("2 EV (Auto)") },
        { 33068, N_("3 EV (Auto)") }
    }
HDR, tag 0x009e.
panasonicImageStabilizer
const TagDetails Exiv2::Internal::panasonicImageStabilizer[] extern
Initial value:
= {
        {  2, N_("On, Mode 1") },
        {  3, N_("Off")        },
        {  4, N_("On, Mode 2") },
        {  5, N_("Panning")    },
        {  6, N_("On, Mode 3") },
    }
ImageStabilizer, tag 0x001a.
panasonicIntelligentDRange
const TagDetails Exiv2::Internal::panasonicIntelligentDRange[] extern
Initial value:
= {
        { 0, N_("Off")      },
        { 1, N_("Low")      },
        { 2, N_("Standard") },
        { 3, N_("High")     }
    }
Intelligent D-Range, tag 0x0079.
panasonicIntelligentExposure
const TagDetails Exiv2::Internal::panasonicIntelligentExposure[] extern
Initial value:
= {
        { 0, N_("Off")      },
        { 1, N_("Low")      },
        { 2, N_("Standard") },
        { 3, N_("High")     }
    }
Intelligent exposure, tag 0x005d.
panasonicIntelligentResolution
const TagDetails Exiv2::Internal::panasonicIntelligentResolution[] extern
Initial value:
= {
        { 0, N_("Off")      },
        { 1, N_("Low")      },
        { 2, N_("Standard") },
        { 3, N_("High")     },
        { 4, N_("Extended") }
    }
Intelligent resolution, tag 0x0070.
panasonicLongShutterNoiseReduction
const TagDetails Exiv2::Internal::panasonicLongShutterNoiseReduction[] extern
Initial value:
= {
        { 1, N_("Off") },
        { 2, N_("On") }
    }
Long Shutter Noise Reduction, tag 0x0049.
panasonicMacro
const TagDetails Exiv2::Internal::panasonicMacro[] extern
Initial value:
= {
        {   1, N_("On")         },
        {   2, N_("Off")        },
        { 257, N_("Tele-macro") },
        { 513, N_("Macro-zoom") }
    }
Macro, tag 0x001c.
panasonicNoiseReduction
const TagDetails Exiv2::Internal::panasonicNoiseReduction[] extern
Initial value:
= {
        { 0, N_("Standard") },
        { 1, N_("Low (-1)")     },
        { 2, N_("High (+1)")    },
        { 3, N_("Lowest (-2)")  },
        { 4, N_("Highest (+2)") }
    }
NoiseReduction, tag 0x002d.
panasonicOpticalZoomMode
const TagDetails Exiv2::Internal::panasonicOpticalZoomMode[] extern
Initial value:
= {
        { 1, N_("Standard")  },
        { 2, N_("EX optics") }
    }
OpticalZoomMode, tag 0x0034.
panasonicPhotoStyle
const TagDetails Exiv2::Internal::panasonicPhotoStyle[] extern
Initial value:
= {
        { 0, N_("NoAuto")             },
        { 1, N_("Standard or Custom") },
        { 2, N_("Vivid")              },
        { 3, N_("Natural")            },
        { 4, N_("Monochrome")         },
        { 5, N_("Scenery")            },
        { 6, N_("Portrait")           }
    }
Photo Style, tag 0x0089.
panasonicQuality
const TagDetails Exiv2::Internal::panasonicQuality[] extern
Initial value:
= {
        {  1, N_("TIFF")           },
        {  2, N_("High")           },
        {  3, N_("Normal")         },
        {  6, N_("Very High")      },
        {  7, N_("Raw")            },
        {  9, N_("Motion Picture") },
        { 11, N_("Full HD Movie")  },
        { 12, N_("4k Movie")       }
    }
Quality, tag 0x0001.
panasonicRotation
const TagDetails Exiv2::Internal::panasonicRotation[] extern
Initial value:
= {
        { 1, N_("Horizontal (normal)") },
        { 3, N_("Rotate 180")          },
        { 6, N_("Rotate 90 CW")        },
        { 8, N_("Rotate 270 CW")       }
    }
Rotation, tag 0x0030.
panasonicSelfTimer
const TagDetails Exiv2::Internal::panasonicSelfTimer[] extern
Initial value:
= {
        { 1, N_("Off")                },
        { 2, "10 s"               },
        { 3, "2 s"                },
        { 4, "10 s / 3 pictures"  }
    }
SelfTimer, tag 0x002e.
panasonicShadingCompensation
const TagDetails Exiv2::Internal::panasonicShadingCompensation[] extern
Initial value:
= {
        { 0, N_("Off") },
        { 1, N_("On") }
    }
Shading compensation, tag 0x008a.
panasonicShutterType
const TagDetails Exiv2::Internal::panasonicShutterType[] extern
Initial value:
= {
        { 0, N_("Mechanical") },
        { 1, N_("Electronic") },
        { 2, N_("Hybrid")     }
    }
Shutter Type, tag 0x009f.
panasonicSweepPanoramaDirection
const TagDetails Exiv2::Internal::panasonicSweepPanoramaDirection[] extern
Initial value:
= {
        { 0, N_("Off")           },
        { 1, N_("Left to Right") },
        { 2, N_("Right to Left") },
        { 3, N_("Top to Bottom") },
        { 4, N_("Bottom to Top") }
    }
Sweep panorama direction, tag 0x0093.
panasonicTextStamp
const TagDetails Exiv2::Internal::panasonicTextStamp[] extern
Initial value:
= {
        { 1, N_("Off") },
        { 2, N_("On")  }
    }
TextStamp, tag 0x003b, 0x003e, 000x8008 and 0x8009.
panasonicTimerRecording
const TagDetails Exiv2::Internal::panasonicTimerRecording[] extern
Initial value:
= {
        { 0, N_("Off")                   },
        { 1, N_("Time Lapse")            },
        { 2, N_("Stop-Motion Animation") }
    }
Timer recording, tag 0x0096.
panasonicTouchAE
const TagDetails Exiv2::Internal::panasonicTouchAE[] extern
Initial value:
= {
        { 0, N_("Off") },
        { 1, N_("On")  }
    }
Touch AE, tag 0x00ab.
panasonicWhiteBalance
const TagDetails Exiv2::Internal::panasonicWhiteBalance[] extern
Initial value:
= {
        {  1, N_("Auto")            },
        {  2, N_("Daylight")        },
        {  3, N_("Cloudy")          },
        {  4, N_("Halogen")         },
        {  5, N_("Manual")          },
        {  8, N_("Flash")           },
        { 10, N_("Black and white") },
        { 11, N_("Manual")          },
        { 12, N_("Shade")           },
        { 13, N_("Kelvin")          }
    }
WhiteBalance, tag 0x0003.
panasonicWorldTimeLocation
const TagDetails Exiv2::Internal::panasonicWorldTimeLocation[] extern
Initial value:
= {
        { 1, N_("Home")        },
        { 2, N_("Destination") }
    }
WorldTimeLocation, tag 0x003a.
pentaxAFPoint
const TagDetails Exiv2::Internal::pentaxAFPoint[] extern
Initial value:
= {
        {    0xffff, N_("Auto") },
        {    0xfffe, N_("Fixed Center") },
        {    0xfffd, N_("Automatic Tracking AF") },
        {    0xfffc, N_("Face Recognition AF") },
        {    0xfffb, N_("AF Select") },
        {    0, N_("None") },
        {    1, N_("Upper-left") },
        {    2, N_("Top") },
        {    3, N_("Upper-right") },
        {    4, N_("Left") },
        {    5, N_("Mid-left") },
        {    6, N_("Center") },
        {    7, N_("Mid-right") },
        {    8, N_("Right") },
        {    9, N_("Lower-left") },
        {    10, N_("Bottom") },
        {    11, N_("Lower-right") },
    }
AFPoint, tag 0x000e.
pentaxAFPointFocus
const TagDetails Exiv2::Internal::pentaxAFPointFocus[] extern
Initial value:
= {
        {    0xffff, N_("None") },
        {    0, N_("Fixed Center or multiple") },
        {    1, N_("Top-left") },
        {    2, N_("Top-center") },
        {    3, N_("Top-right") },
        {    4, N_("Left") },
        {    5, N_("Center") },
        {    6, N_("Right") },
        {    7, N_("Bottom-left") },
        {    8, N_("Bottom-center") },
        {    9, N_("Bottom-right") },
    }
AFPointInFocus, tag 0x000f.
pentaxColorSpace
const TagDetails Exiv2::Internal::pentaxColorSpace[] extern
Initial value:
= {
        {    0, N_("sRGB") },
        {    1, N_("Adobe RGB") },
    }
ColorSpace, tag 0x0037.
pentaxContrast
const TagDetails Exiv2::Internal::pentaxContrast[] extern
Initial value:
= {
        {    0, N_("Low") },
        {    1, N_("Normal") },
        {    2, N_("High") },
        {    3, N_("Med Low") },
        {    4, N_("Med High") },
        {    5, N_("Very Low") },
        {    6, N_("Very High") },
        {    7, N_("-4") },
        {    8, N_("+4") },
    }
Contrast, tag 0x0020.
pentaxDriveMode
const TagDetails Exiv2::Internal::pentaxDriveMode[] extern
Initial value:
= {
        { 0x00000000, N_("Single-frame") },
        { 0x01000000, N_("Continuous") },
        { 0x02000000, N_("Continuous (Hi)") },
        { 0x03000000, N_("Burst") },
        { 0xff000000, N_("Video") },
        { 0x00100000, N_("Single-frame") },
        { 0x00010000, N_("Self-timer (12 sec)") },
        { 0x00020000, N_("Self-timer (2 sec)") },
        { 0x000f0000, N_("Video") },
        { 0x00100000, N_("Mirror Lock-up") },
        { 0x00000100, N_("Remote Control (3 sec)") },
        { 0x00000200, N_("Remote Control") },
        { 0x00000400, N_("Remote Continuous Shooting") },
        { 0x00000001, N_("Multiple Exposure") },
        { 0x00000010, N_("HDR") },
        { 0x00000020, N_("HDR Strong 1") },
        { 0x00000030, N_("HDR Strong 2") },
        { 0x00000040, N_("HDR Strong 3") },
        { 0x000000e0, N_("HDR Auto") },
        { 0x000000ff, N_("Video") },
    }
DriveMode, combi-tag 0x0034 (4 bytes)
pentaxDynamicRangeExpansion
const TagDetails Exiv2::Internal::pentaxDynamicRangeExpansion[] extern
Initial value:
= {
        {   0, N_("Off") },
        {   0x1000000, N_("On") },
    }
DynamicRangeExpansion, tag 0x0069.
pentaxFlash
const TagDetails Exiv2::Internal::pentaxFlash[] extern
Initial value:
= {
        {    0x000, N_("Auto, Did not fire") },
        {    0x001, N_("Off, Did not fire") },
        {    0x002, N_("Off, Did not fire") },
        {    0x003, N_("Auto, Did not fire, Red-eye reduction") },
        {    0x005, N_("On. Did not fire. Wireless (Master)") },
        {    0x100, N_("Auto, Fired") },
        {    0x102, N_("On, Fired") },
        {    0x103, N_("Auto, Fired, Red-eye reduction") },
        {    0x104, N_("On, Red-eye reduction") },
        {    0x105, N_("On, Wireless (Master)") },
        {    0x106, N_("On, Wireless (Control)") },
        {    0x108, N_("On, Soft") },
        {    0x109, N_("On, Slow-sync") },
        {    0x10a, N_("On, Slow-sync, Red-eye reduction") },
        {    0x10b, N_("On, Trailing-curtain Sync") },
    }
Flash, tag 0x000c.
pentaxFocus
const TagDetails Exiv2::Internal::pentaxFocus[] extern
Initial value:
= {
        {    0, N_("Normal") },
        {    1, N_("Macro") },
        {    2, N_("Infinity") },
        {    3, N_("Manual") },
        {    4, N_("Super Macro") },
        {    5, N_("Pan Focus") },
        {    16, N_("AF-S") },
        {    17, N_("AF-C") },
        {    18, N_("AF-A") },
        {    32, N_("Contrast-detect") },
        {    33, N_("Tracking Contrast-detect") },
        {    288, N_("Face Detect") },
    }
Focus, tag 0x000d.
pentaxHighISONoiseReduction
const TagDetails Exiv2::Internal::pentaxHighISONoiseReduction[] extern
Initial value:
= {
        {   0, N_("Off") },
        {   1, N_("Weakest") },
        {   2, N_("Weak") },
        {   3, N_("Strong") },
        {   4, N_("Custom") },
    }
HighISONoiseReduction, tag 0x0071.
pentaxImageProcessing
const TagDetails Exiv2::Internal::pentaxImageProcessing[] extern
Initial value:
= {
        { 0x00000000, N_("Unprocessed") },
        { 0x00000004, N_("Digital Filter") },
        { 0x01000000, N_("Resized") },
        { 0x02000000, N_("Cropped") },
        { 0x04000000, N_("Color Filter") },
        { 0x06000000, N_("Digital Filter 6") },
        { 0x10000000, N_("Frame Synthesis?") }
    }
ImageProcessing, combi-tag 0x0032 (4 bytes)
pentaxImageTone
const TagDetails Exiv2::Internal::pentaxImageTone[] extern
Initial value:
= {
        {    0, N_("Natural") },
        {    1, N_("Bright") },
        {    2, N_("Portrait") },
        {    3, N_("Landscape") },
        {    4, N_("Vibrant") },
        {    5, N_("Monochrome") },
        {    6, N_("Muted") },
        {    7, N_("Reversal film") },
        {    8, N_("Bleach bypass") },
        {    9, N_("Radiant") },
    }
ImageTone, tag 0x004f.
pentaxLocation
const TagDetails Exiv2::Internal::pentaxLocation[] extern
Initial value:
= {
        {    0, N_("Home town") },
        {    1, N_("Destination") },
    }
Location, tag 0x0022.
pentaxMeteringMode
const TagDetails Exiv2::Internal::pentaxMeteringMode[] extern
Initial value:
= {
        {    0, N_("Multi Segment") },
        {    1, N_("Center Weighted") },
        {    2, N_("Spot") },
    }
MeteringMode, tag 0x0017.
pentaxOffOn
const TagDetails Exiv2::Internal::pentaxOffOn[] extern
Initial value:
= {
        {    0, N_("Off") },
        {    1, N_("On") },
    }
Generic for Off/On switches.
pentaxQuality
const TagDetails Exiv2::Internal::pentaxQuality[] extern
Initial value:
= {
        {   0, N_("Good") },
        {   1, N_("Better") },
        {   2, N_("Best") },
        {   3, N_("TIFF") },
        {   4, N_("RAW") },
        {   5, N_("Premium") },
        {   65535, N_("n/a") },
    }
Quality, tag 0x0008.
pentaxSaturation
const TagDetails Exiv2::Internal::pentaxSaturation[] extern
Initial value:
= {
        {     0, N_("Low")       },
        {     1, N_("Normal")    },
        {     2, N_("High")      },
        {     3, N_("Med Low")   },
        {     4, N_("Med High")  },
        {     5, N_("Very Low")  },
        {     6, N_("Very High") },
        {     7, N_("-4") },
        {     8, N_("+4") },
        { 65535, N_("None")      },
        { 65535, N_("None")      }
    }
Saturation, tag 0x001f.
pentaxSharpness
const TagDetails Exiv2::Internal::pentaxSharpness[] extern
Initial value:
= {
        {    0, N_("Soft") },
        {    1, N_("Normal") },
        {    2, N_("Hard") },
        {    3, N_("Med Soft") },
        {    4, N_("Med Hard") },
        {    5, N_("Very Soft") },
        {    6, N_("Very Hard") },
        {    7, N_("-4") },
        {    8, N_("+4") },
    }
Sharpness, tag 0x0021.
pentaxShootingMode
const TagDetails Exiv2::Internal::pentaxShootingMode[] extern
Initial value:
= {
        {   0, N_("Auto")                      },
        {   1, N_("Night-Scene")               },
        {   2, N_("Manual")                    },
    }
ShootingMode, tag 0x0001.
pentaxWhiteBalance
const TagDetails Exiv2::Internal::pentaxWhiteBalance[] extern
Initial value:
= {
        {    0, N_("Auto") },
        {    1, N_("Daylight") },
        {    2, N_("Shade") },
        {    3, N_("Fluorescent") },
        {    4, N_("Tungsten") },
        {    5, N_("Manual") },
        {    6, N_("DaylightFluorescent") },
        {    7, N_("DaywhiteFluorescent") },
        {    8, N_("WhiteFluorescent") },
        {    9, N_("Flash") },
        {    10, N_("Cloudy") },
        {    15, N_("Color Temperature Enhancement") },
        {    17, N_("Kelvin") },
        {    65534, N_("Unknown") },
        {    65535, N_("User Selected") },
    }
WhiteBalance, tag 0x0019.
pentaxWhiteBalanceMode
const TagDetails Exiv2::Internal::pentaxWhiteBalanceMode[] extern
Initial value:
= {
        {    1, N_("Auto (Daylight)") },
        {    2, N_("Auto (Shade)") },
        {    3, N_("Auto (Flash)") },
        {    4, N_("Auto (Tungsten)") },
        {    6, N_("Auto (DaylightFluorescent)") },
        {    7, N_("Auto (DaywhiteFluorescent)") },
        {    8, N_("Auto (WhiteFluorescent)") },
        {    10, N_("Auto (Cloudy)") },
        {    0xffff, N_("User-Selected") },
        {    0xfffe, N_("Preset (Fireworks?)") },
    }
WhiteBalance, tag 0x001a.
pentaxYesNo
const TagDetails Exiv2::Internal::pentaxYesNo[] extern
Initial value:
= {
        {    0, N_("No") },
        {    1, N_("Yes") },
    }
Generic for Yes/No switches.
print0xb025
const TagDetails Exiv2::Internal::print0xb025[] extern
Initial value:
= {
        { 0,  N_("Off")           },
        { 1,  N_("Standard")      },
        { 2,  N_("Advanced Auto") },
        { 3,  N_("Auto")          },
        { 8,  N_("Advanced Lv1")  },
        { 9,  N_("Advanced Lv2")  },
        { 10, N_("Advanced Lv3")  },
        { 11, N_("Advanced Lv4")  },
        { 12, N_("Advanced Lv5")  },
        { 16, "1"                 },
        { 17, "2"                 },
        { 18, "3"                 },
        { 19, "4"                 },
        { 20, "5"                 }
    }
Lookup table to translate Sony dynamic range optimizer values to readable labels.
print0xb04f
const TagDetails Exiv2::Internal::print0xb04f[] extern
Initial value:
= {
        { 0, N_("Off")      },
        { 1, N_("Standard") },
        { 2, N_("Plus")     }
    }
Lookup table to translate Sony dynamic range optimizer values to readable labels.
samsung2ColorSpace
const TagDetails Exiv2::Internal::samsung2ColorSpace[] extern
Initial value:
= {
        { 0, N_("sRGB")      },
        { 1, N_("Adobe RGB") }
    }
ColorSpace, tag 0xa011.
samsung2LensType
const TagDetails Exiv2::Internal::samsung2LensType[] extern
Initial value:
= {
        {  0, N_("Built-in")                                      },
        {  1, "Samsung NX 30mm F2 Pancake"                    },
        {  2, "Samsung NX 18-55mm F3.5-5.6 OIS"               },
        {  3, "Samsung NX 50-200mm F4-5.6 ED OIS"             },
        {  4, "Samsung NX 20-50mm F3.5-5.6 ED"                },
        {  5, "Samsung NX 20mm F2.8 Pancake"                  },
        {  6, "Samsung NX 18-200mm F3.5-6.3 ED OIS"           },
        {  7, "Samsung NX 60mm F2.8 Macro ED OIS SSA"         },
        {  8, "Samsung NX 16mm F2.4 Pancake"                  },
        {  9, "Samsung NX 85mm F1.4 ED SSA"                   },
        { 10, "Samsung NX 45mm F1.8"                          },
        { 11, "Samsung NX 45mm F1.8 2D/3D"                    },
        { 12, "Samsung NX 12-24mm F4-5.6 ED"                  },
        { 13, "Samsung NX 16-50mm F2-2.8 S ED OIS"            },
        { 14, "Samsung NX 10mm F3.5 Fisheye"                  },
        { 15, "Samsung NX 16-50mm F3.5-5.6 Power Zoom ED OIS" },
        { 20, "Samsung NX 50-150mm F2.8 S ED OIS"             },
        { 21, "Samsung NX 300mm F2.8 ED OIS"                  }
    }
LensType, tag 0xa003.
samsung2SmartRange
const TagDetails Exiv2::Internal::samsung2SmartRange[] extern
Initial value:
= {
        { 0, N_("Off") },
        { 1, N_("On")  }
    }
SmartRange, tag 0xa012.
samsungPwCfg
const ArrayCfg Exiv2::Internal::samsungPwCfg extern
Initial value:
= {
        samsungPwId,
        invalidByteOrder,
        ttUnsignedShort,
        notEncrypted,
        false,
        true,
        true,
        { 0, ttUnsignedShort, 1 }
    }
Samsung PictureWizard binary array - configuration.
samsungPwDef
const ArrayDef Exiv2::Internal::samsungPwDef[] extern
Initial value:
= {
        {  0, ttUnsignedShort, 1 },
        {  2, ttUnsignedShort, 1 },
        {  4, ttUnsignedShort, 1 },
        {  6, ttUnsignedShort, 1 },
        {  8, ttUnsignedShort, 1 }
    }
Samsung PictureWizard binary array - definition.
samsungPwMode
const TagDetails Exiv2::Internal::samsungPwMode[] extern
Initial value:
= {
        {  0, N_("Standard")  },
        {  1, N_("Vivid")     },
        {  2, N_("Portrait")  },
        {  3, N_("Landscape") },
        {  4, N_("Forest")    },
        {  5, N_("Retro")     },
        {  6, N_("Cool")      },
        {  7, N_("Calm")      },
        {  8, N_("Classic")   },
        {  9, N_("Custom1")   },
        { 10, N_("Custom2")   },
        { 11, N_("Custom3")   }
    }
PictureWizard Mode.
slowShutter
const TagDetails Exiv2::Internal::slowShutter[] extern
Initial value:
= {
        { 65535, "n/a"         },
        { 0,     "Off"         },
        { 1,     "Night Scene" },
        { 2,     "On"          },
        { 3,     "None"        },
    }
sony1Cs2Cfg
const ArrayCfg Exiv2::Internal::sony1Cs2Cfg extern
Initial value:
= {
        sony1Cs2Id,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Sony1 Camera Settings 2 binary array - configuration.
sony1CsCfg
const ArrayCfg Exiv2::Internal::sony1CsCfg extern
Initial value:
= {
        sony1CsId,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Sony1 Camera Settings binary array - configuration.
sony1CsSet
const ArraySet Exiv2::Internal::sony1CsSet[] extern
Initial value:
= {
        { sony1CsCfg,  sonyCsDef,  EXV_COUNTOF(sonyCsDef)  },
        { sony1Cs2Cfg, sonyCs2Def, EXV_COUNTOF(sonyCs2Def) }
    }
Sony1 Camera Settings configurations and definitions.
sony1MCs7Cfg
const ArrayCfg Exiv2::Internal::sony1MCs7Cfg extern
Initial value:
= {
        sony1MltCs7DId,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Sony Minolta 7D Camera Settings binary array - configuration.
sony1MCsA100Cfg
const ArrayCfg Exiv2::Internal::sony1MCsA100Cfg extern
Initial value:
= {
        sony1MltCsA100Id,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Sony Minolta A100 Camera Settings binary array - configuration.
sony1MCsA100Def
const ArrayDef Exiv2::Internal::sony1MCsA100Def[] extern
Initial value:
= {
        { 112, ttSignedShort, 1 },
        { 116, ttSignedShort, 1 },
        { 190, ttSignedShort, 1 }
    }
Sony Minolta A100 Camera Settings binary array - definition.
sony1MCsnCfg
const ArrayCfg Exiv2::Internal::sony1MCsnCfg extern
Initial value:
= {
        sony1MltCsNewId,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedLong, 1 }
    }
Sony Minolta Camera Settings (new) binary array - configuration.
sony1MCsoCfg
const ArrayCfg Exiv2::Internal::sony1MCsoCfg extern
Initial value:
= {
        sony1MltCsOldId,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedLong, 1 }
    }
Sony Minolta Camera Settings (old) binary array - configuration.
sony2010eCfg
const ArrayCfg Exiv2::Internal::sony2010eCfg extern
Initial value:
= {
        sony2010eId,
        invalidByteOrder,
        ttUnsignedByte,
        sonyTagDecipher,
        false,
        false,
        false,
        { 0, ttUnsignedByte, 1 }
    }
sony2010eSet
const ArraySet Exiv2::Internal::sony2010eSet[] extern
Initial value:
= {
        { sony2010eCfg,  sony2010eDef,  EXV_COUNTOF(sony2010eDef)  }
    }
Sony1 Camera Settings configurations and definitions.
sony2Cs2Cfg
const ArrayCfg Exiv2::Internal::sony2Cs2Cfg extern
Initial value:
= {
        sony2Cs2Id,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Sony2 Camera Settings 2 binary array - configuration.
sony2CsCfg
const ArrayCfg Exiv2::Internal::sony2CsCfg extern
Initial value:
= {
        sony2CsId,
        bigEndian,
        ttUndefined,
        notEncrypted,
        false,
        false,
        false,
        { 0, ttUnsignedShort, 1 }
    }
Sony2 Camera Settings binary array - configuration.
sony2CsSet
const ArraySet Exiv2::Internal::sony2CsSet[] extern
Initial value:
= {
        { sony2CsCfg,  sonyCsDef,  EXV_COUNTOF(sonyCsDef)  },
        { sony2Cs2Cfg, sonyCs2Def, EXV_COUNTOF(sonyCs2Def) }
    }
Sony2 Camera Settings configurations and definitions.
sony2FpCfg
const ArrayCfg Exiv2::Internal::sony2FpCfg extern
Initial value:
= {
        sony2FpId,
        bigEndian,
        ttUnsignedByte,
        sonyTagDecipher,
        false,
        false,
        false,
        { 0, ttUnsignedByte, 1 }
    }
sony2FpDef
const ArrayDef Exiv2::Internal::sony2FpDef[] extern
Initial value:
= {
        {  0x4, ttSignedByte  , 1 },
        { 0x16, ttUnsignedByte, 1 },
        { 0x17, ttUnsignedByte, 1 },
        { 0x2d, ttUnsignedByte, 1 }
    }
sonyAELButtonA100
const TagDetails Exiv2::Internal::sonyAELButtonA100[] extern
Initial value:
= {
        { 0, N_("Hold")        },
        { 1, N_("Toggle")      },
        { 2, N_("Spot Hold")   },
        { 3, N_("Spot Toggle") }
    }
Lookup table to translate Sony A100 camera settings AEL button values to readable labels.
sonyAFAreaIlluminationA100
const TagDetails Exiv2::Internal::sonyAFAreaIlluminationA100[] extern
Initial value:
= {
        { 0, N_("0.3 seconds") },
        { 1, N_("0.6 seconds") },
        { 2, N_("Off")         }
    }
Lookup table to translate Sony A100 camera settings sony AF area illumination values to readable labels.
sonyAFIlluminator
const TagDetails Exiv2::Internal::sonyAFIlluminator[] extern
Initial value:
= {
        { 0,     N_("Off") },
        { 1,     N_("Auto")  },
        { 65535, N_("n/a") }
    }
Lookup table to translate Sony AF illuminator values to readable labels.
sonyAFIlluminatorCS
const TagDetails Exiv2::Internal::sonyAFIlluminatorCS[] extern
Initial value:
= {
        { 0, N_("Auto") },
        { 1, N_("Off")  }
    }
Lookup table to translate Sony AF illuminator values to readable labels.
sonyAFMode
const TagDetails Exiv2::Internal::sonyAFMode[] extern
Initial value:
= {
        { 0,     N_("Default")          },
        { 1,     N_("Multi AF")         },
        { 2,     N_("Center AF")        },
        { 3,     N_("Spot AF")          },
        { 4,     N_("Flexible Spot AF") },
        { 6,     N_("Touch AF")         },
        { 14,    N_("Manual Focus")     },
        { 15,    N_("Face Detected")    },
        { 65535, N_("n/a")              }
    }
Lookup table to translate Sony AF mode values to readable labels.
sonyAntiBlur
const TagDetails Exiv2::Internal::sonyAntiBlur[] extern
Initial value:
= {
        { 0,     N_("Off")             },
        { 1,     N_("On (Continuous)") },
        { 2,     N_("On (Shooting)")   },
        { 65535, N_("n/a")             }
    }
Lookup table to translate Sony anti-blur values to readable labels.
sonyAspectRatio
const TagDetails Exiv2::Internal::sonyAspectRatio[] extern
Initial value:
= {
        { 1, "3:2"   },
        { 2, "16:9"  }
    }
Lookup table to translate Sony aspect ratio values to readable labels.
sonyAutoBracketOrderA100
const TagDetails Exiv2::Internal::sonyAutoBracketOrderA100[] extern
Initial value:
= {
        { 0, "0-+" },
        { 1, "-0+" }
    }
Lookup table to translate Sony A100 camera settings auto bracket order values to readable labels.
sonyBatteryLevelA100
const TagDetails Exiv2::Internal::sonyBatteryLevelA100[] extern
Initial value:
= {
        { 3, N_("Very Low")                   },
        { 4, N_("Low")                        },
        { 5, N_("Half Full")                  },
        { 6, N_("Sufficient Power Remaining") }
    }
Lookup table to translate Sony A100 camera settings battery level switch values to readable labels.
sonyColorSpaceA100
const TagDetails Exiv2::Internal::sonyColorSpaceA100[] extern
Initial value:
= {
        { 0, N_("sRGB")      },
        { 5, N_("Adobe RGB") }
    }
Lookup table to translate Sony A100 camera settings color space values to readable labels.
sonyColorTemperatureSettingA100
const TagDetails Exiv2::Internal::sonyColorTemperatureSettingA100[] extern
Initial value:
= {
        { 0, N_("Temperature")  },
        { 2, N_("Color Filter") }
    }
Lookup table to translate Sony A100 camera settings color temperature setting values to readable labels.
sonyContinuousBracketingA100
const TagDetails Exiv2::Internal::sonyContinuousBracketingA100[] extern
Initial value:
= {
        { 0x303, N_("Low")  },
        { 0x703, N_("High") }
    }
Lookup table to translate Sony A100 camera settings continuous bracketing values to readable labels.
sonyControlDialSetA100
const TagDetails Exiv2::Internal::sonyControlDialSetA100[] extern
Initial value:
= {
        { 0, N_("Shutter Speed") },
        { 1, N_("Aperture")      }
    }
Lookup table to translate Sony A100 camera settings control dial set values to readable labels.
sonyCreativeStyle
const TagDetails Exiv2::Internal::sonyCreativeStyle[] extern
Initial value:
= {
        { 1,    N_("Standard")            },
        { 2,    N_("Vivid")               },
        { 3,    N_("Portrait")            },
        { 4,    N_("Landscape")           },
        { 5,    N_("Sunset")              },
        { 6,    N_("Night View/Portrait") },
        { 8,    N_("Black & White")       },
        { 9,    N_("Adobe RGB")           },
        { 11,   N_("Neutral")             },
        { 12,   N_("Clear")               },
        { 13,   N_("Deep")                },
        { 14,   N_("Light")               },
        { 15,   N_("Autumn")              },
        { 16,   N_("Sepia")               }
    }
Lookup table to translate Sony camera settings creative style values to readable labels.
sonyCs2Def
const ArrayDef Exiv2::Internal::sonyCs2Def[] extern
Initial value:
= {
        {  44, ttUnsignedShort, 1 }
    }
Sony[12] Camera Settings 2 binary array - definition.
sonyCsDef
const ArrayDef Exiv2::Internal::sonyCsDef[] extern
Initial value:
= {
        {  12, ttSignedShort,   1 }
    }
Sony[12] Camera Settings binary array - definition.
sonyCSFocusMode
const TagDetails Exiv2::Internal::sonyCSFocusMode[] extern
Initial value:
= {
        { 0, N_("Manual") },
        { 1, "AF-S"       },
        { 2, "AF-C"       },
        { 3, "AF-A"       }
    }
Lookup table to translate Sony camera settings focus mode values to readable labels.
sonyCustomWBErrorA100
const TagDetails Exiv2::Internal::sonyCustomWBErrorA100[] extern
Initial value:
= {
        { 0, N_("Ok")    },
        { 2, N_("Error") }
    }
Lookup table to translate Sony A100 camera settings custom WB error values to readable labels.
sonyCustomWBSettingA100
const TagDetails Exiv2::Internal::sonyCustomWBSettingA100[] extern
Initial value:
= {
        { 0, N_("Setup")  },
        { 2, N_("Recall") }
    }
Lookup table to translate Sony A100 camera settings custom WB setting values to readable labels.
sonyDriveMode2A100
const TagDetails Exiv2::Internal::sonyDriveMode2A100[] extern
Initial value:
= {
        { 0,    N_("Self-timer 10 sec")             },
        { 1,    N_("Continuous")                    },
        { 4,    N_("Self-timer 2 sec")              },
        { 5,    N_("Single Frame")                  },
        { 8,    N_("White Balance Bracketing Low")  },
        { 9,    N_("White Balance Bracketing High") },
        { 770,  N_("Single-frame Bracketing Low")   },
        { 771,  N_("Continuous Bracketing Low")     },
        { 1794, N_("Single-frame Bracketing High")  },
        { 1795, N_("Continuous Bracketing High")    }
    }
Lookup table to translate Sony A100 camera settings drive mode 2 values to readable labels.
sonyDriveModeA100
const TagDetails Exiv2::Internal::sonyDriveModeA100[] extern
Initial value:
= {
        { 0, N_("Single Frame")             },
        { 1, N_("Continuous")               },
        { 2, N_("Self-timer")               },
        { 3, N_("Continuous Bracketing")    },
        { 4, N_("Single-Frame Bracketing")  },
        { 5, N_("White Balance Bracketing") }
    }
Lookup table to translate Sony A100 camera settings drive mode values to readable labels.
sonyDriveModeStd
const TagDetails Exiv2::Internal::sonyDriveModeStd[] extern
Initial value:
= {
        { 0x01, N_("Single Frame")                      },
        { 0x02, N_("Continuous High")                   },
        { 0x04, N_("Self-timer 10 sec")                 },
        { 0x05, N_("Self-timer 2 sec, Mirror Lock-up")  },
        { 0x06, N_("Single-frame Bracketing")           },
        { 0x07, N_("Continuous Bracketing")             },
        { 0x0a, N_("Remote Commander")                  },
        { 0x0b, N_("Mirror Lock-up")                    },
        { 0x12, N_("Continuous Low")                    },
        { 0x18, N_("White Balance Bracketing Low")      },
        { 0x19, N_("D-Range Optimizer Bracketing Low")  },
        { 0x28, N_("White Balance Bracketing High")     },
        { 0x29, N_("D-Range Optimizer Bracketing High") },
        { 0x29, N_("D-Range Optimizer Bracketing High") }
    }
Lookup table to translate Sony camera settings drive mode values to readable labels.
sonyExposureCompensationModeA100
const TagDetails Exiv2::Internal::sonyExposureCompensationModeA100[] extern
Initial value:
= {
        { 0, N_("Ambient and Flash") },
        { 1, N_("Ambient Only")      }
    }
Lookup table to translate Sony A100 camera settings exposure compensation mode values to readable labels.
sonyExposureIndicatorA100
const TagDetails Exiv2::Internal::sonyExposureIndicatorA100[] extern
Initial value:
= {
        { 0,   N_("Not Indicated")   },
        { 1,   N_("Under Scale")     },
        { 119, N_("Bottom of Scale") },
        { 120, "-2.0"                },
        { 121, "-1.7"                },
        { 122, "-1.5"                },
        { 123, "-1.3"                },
        { 124, "-1.0"                },
        { 125, "-0.7"                },
        { 126, "-0.5"                },
        { 127, "-0.3"                },
        { 128, "-0.0"                },
        { 129, "+0.3"                },
        { 130, "+0.5"                },
        { 131, "+0.7"                },
        { 132, "+1.0"                },
        { 133, "+1.3"                },
        { 134, "+1.5"                },
        { 135, "+1.7"                },
        { 136, "+2.0"                },
        { 253, N_("Top of Scale")    },
        { 254, N_("Over Scale")      }
    }
Lookup table to translate Sony A100 camera settings exposure indicator values to readable labels.
sonyExposureLevelIncrements
const TagDetails Exiv2::Internal::sonyExposureLevelIncrements[] extern
Initial value:
= {
        { 33, "1/3 EV" },
        { 50, "1/2 EV" }
    }
Lookup table to translate Sony exposure level increments values to readable labels.
sonyExposureProgram
const TagDetails Exiv2::Internal::sonyExposureProgram[] extern
Initial value:
= {
        { 0,    N_("Auto")                      },
        { 1,    N_("Manual")                    },
        { 2,    N_("Program AE")                },
        { 3,    N_("Aperture-priority AE")      },
        { 4,    N_("Shutter speed priority AE") },
        { 8,    N_("Program Shift A")           },
        { 9,    N_("Program Shift S")           },
        { 16,   N_("Portrait")                  },
        { 17,   N_("Sports")                    },
        { 18,   N_("Sunset")                    },
        { 19,   N_("Night Portrait")            },
        { 20,   N_("Landscape")                 },
        { 21,   N_("Macro")                     },
        { 35,   N_("Auto No Flash")             }
    }
Lookup table to translate Sony camera settings exposure program values to readable labels.
sonyFlashDefaultA100
const TagDetails Exiv2::Internal::sonyFlashDefaultA100[] extern
Initial value:
= {
        { 0, N_("Auto")       },
        { 1, N_("Fill Flash") }
    }
Lookup table to translate Sony A100 camera settings flash default setup values to readable labels.
sonyFlashLevel
const TagDetails Exiv2::Internal::sonyFlashLevel[] extern
Initial value:
= {
        { -32768, N_("Low")    },
        { -1,     N_("n/a")    },
        { 0,      N_("Normal") },
        { 32767,  N_("High")   }
    }
Lookup table to translate Sony flash level values to readable labels.
sonyFlashMode
const TagDetails Exiv2::Internal::sonyFlashMode[] extern
Initial value:
= {
        { 0, N_("ADI") },
        { 1, N_("TTL") },
    }
Lookup table to translate Sony camera settings flash mode values to readable labels.
sonyFlashModeA100
const TagDetails Exiv2::Internal::sonyFlashModeA100[] extern
Initial value:
= {
        { 0, N_("Auto")            },
        { 2, N_("Rear flash sync") },
        { 3, N_("Wireless")        },
        { 4, N_("Fill flash")      }
    }
Lookup table to translate Sony A100 camera settings flash mode values to readable labels.
sonyFlashTypeA100
const TagDetails Exiv2::Internal::sonyFlashTypeA100[] extern
Initial value:
= {
        { 0, N_("Off")      },
        { 1, N_("Built-in") },
        { 2, N_("External") }
    }
Lookup table to translate Sony A100 camera settings flash type switch values to readable labels.
sonyFocusHoldButtonA100
const TagDetails Exiv2::Internal::sonyFocusHoldButtonA100[] extern
Initial value:
= {
        { 0, N_("Focus Hold")  },
        { 1, N_("DOF Preview") }
    }
Lookup table to translate Sony A100 camera settings focus hold button values to readable labels.
sonyFocusMode
const TagDetails Exiv2::Internal::sonyFocusMode[] extern
Initial value:
= {
        { 1,     "AF-S"             },
        { 2,     "AF-C"             },
        { 4,     N_("Permanent-AF") },
        { 65535, N_("n/a")          }
    }
Lookup table to translate Sony AF mode values to readable labels.
sonyFocusModeA100
const TagDetails Exiv2::Internal::sonyFocusModeA100[] extern
Initial value:
= {
        { 0, "AF-S"   },
        { 1, "AF-C"   },
        { 4, "AF-A"   },
        { 5, "Manual" },
        { 6, "DMF"    }
    }
Lookup table to translate Sony A100 camera settings focus mode values to readable labels.
sonyFocusModeSwitchA100
const TagDetails Exiv2::Internal::sonyFocusModeSwitchA100[] extern
Initial value:
= {
        { 0, N_("AM") },
        { 1, N_("MF") }
    }
Lookup table to translate Sony A100 camera settings focus mode switch values to readable labels.
sonyHDRMode
const TagDetails Exiv2::Internal::sonyHDRMode[] extern
Initial value:
= {
        { 0x00000, N_("Off")   },
        { 0x10001, N_("Auto")  },
        { 0x10010, "1"         },
        { 0x10012, "2"         },
        { 0x10014, "3"         },
        { 0x10016, "4"         },
        { 0x10018, "5"         }
    }
Lookup table to translate Sony Auto HDR values to readable labels.
sonyImageSize
const TagDetails Exiv2::Internal::sonyImageSize[] extern
Initial value:
= {
        { 1, N_("Large")  },
        { 2, N_("Medium") },
        { 3, N_("Small")  }
    }
Lookup table to translate Sony camera settings image size values to readable labels.
sonyImageSizeA100
const TagDetails Exiv2::Internal::sonyImageSizeA100[] extern
Initial value:
= {
        { 0, N_("Standard") },
        { 1, N_("Medium")   },
        { 2, N_("Small")    }
    }
Lookup table to translate Sony A100 camera settings image size values to readable labels.
sonyImageStyle
const TagDetails Exiv2::Internal::sonyImageStyle[] extern
Initial value:
= {
        { 1,    N_("Standard")            },
        { 2,    N_("Vivid")               },
        { 3,    N_("Portrait")            },
        { 4,    N_("Landscape")           },
        { 5,    N_("Sunset")              },
        { 7,    N_("Night View/Portrait") },
        { 8,    N_("B&W")                 },
        { 9,    N_("Adobe RGB")           },
        { 11,   N_("Neutral")             },
        { 129,  N_("StyleBox1")           },
        { 130,  N_("StyleBox2")           },
        { 131,  N_("StyleBox3")           },
        { 132,  N_("StyleBox4")           },
        { 133,  N_("StyleBox5")           },
        { 134,  N_("StyleBox6")           }
    }
Lookup table to translate Sony camera settings image style values to readable labels.
sonyInstantPlaybackSetupA100
const TagDetails Exiv2::Internal::sonyInstantPlaybackSetupA100[] extern
Initial value:
= {
        { 0, N_("Image and Information") },
        { 1, N_("Image Only")            },
        { 3, N_("Image and Histogram")   }
    }
Lookup table to translate Sony A100 camera settings instant playback setup values to readable labels.
sonyIntelligentAuto
const TagDetails Exiv2::Internal::sonyIntelligentAuto[] extern
Initial value:
= {
        { 0, N_("Off")      },
        { 1, N_("On")       },
        { 2, N_("Advanced") }
    }
Lookup table to translate Sony Intelligent Auto values to readable labels.
sonyJPEGQuality
const TagDetails Exiv2::Internal::sonyJPEGQuality[] extern
Initial value:
= {
        { 0,     N_("Normal")       },
        { 1,     N_("Fine")         },
        { 2,     N_("Extra Fine")   },
        { 65535, N_("n/a")          }
    }
Lookup table to translate Sony JPEG Quality values to readable labels.
sonyLongExposureNoiseReduction
const TagDetails Exiv2::Internal::sonyLongExposureNoiseReduction[] extern
Initial value:
= {
        { 0,     N_("Off") },
        { 1,     N_("On")  },
        { 65535, N_("n/a") }
    }
Lookup table to translate Sony long exposure noise reduction values to readable labels.
sonyMacroMode
const TagDetails Exiv2::Internal::sonyMacroMode[] extern
Initial value:
= {
        { 0,     N_("Off")         },
        { 1,     N_("On")          },
        { 2,     N_("Close Focus") },
        { 65535, N_("n/a")         }
    }
Lookup table to translate Sony macro mode values to readable labels.
sonyMeteringMode
const TagDetails Exiv2::Internal::sonyMeteringMode[] extern
Initial value:
= {
        { 1, N_("Multi-segment")           },
        { 2, N_("Center weighted average") },
        { 4, N_("Spot")                    }
    }
Lookup table to translate Sony camera settings metering mode values to readable labels.
sonyMeteringModeA100
const TagDetails Exiv2::Internal::sonyMeteringModeA100[] extern
Initial value:
= {
        { 0, N_("Multi-segment")           },
        { 1, N_("Center weighted average") },
        { 2, N_("Spot")                    }
    }
Lookup table to translate Sony A100 camera settings metering mode values to readable labels.
sonyMeteringOffScaleIndicatorA100
const TagDetails Exiv2::Internal::sonyMeteringOffScaleIndicatorA100[] extern
Initial value:
= {
        { 0,   N_("Within Range")     },
        { 1,   N_("Under/Over Range") },
        { 255, N_("Out of Range")     }
    }
Lookup table to translate Sony A100 camera settings metering off scale indicator values to readable labels.
sonyMonitorDisplayOffA100
const TagDetails Exiv2::Internal::sonyMonitorDisplayOffA100[] extern
Initial value:
= {
        { 0, N_("Automatic") },
        { 1, N_("Manual")    }
    }
Lookup table to translate Sony A100 camera settings monitor display off values to readable labels.
sonyPlayDisplayA100
const TagDetails Exiv2::Internal::sonyPlayDisplayA100[] extern
Initial value:
= {
        { 0, N_("Auto-rotate")   },
        { 1, N_("Manual Rotate") }
    }
Lookup table to translate Sony A100 camera settings play display values to readable labels.
sonyPresetWhiteBalanceA100
const TagDetails Exiv2::Internal::sonyPresetWhiteBalanceA100[] extern
Initial value:
= {
        { 1, N_("Daylight")    },
        { 2, N_("Cloudy")      },
        { 3, N_("Shade")       },
        { 4, N_("Tungsten")    },
        { 5, N_("Fluorescent") },
        { 6, N_("Flash")       }
    }
Lookup table to translate Sony A100 camera settings preset white balance values to readable labels.
sonyRecordDisplayA100
const TagDetails Exiv2::Internal::sonyRecordDisplayA100[] extern
Initial value:
= {
        { 0, N_("Auto-rotate") },
        { 1, N_("Horizontal")  }
    }
Lookup table to translate Sony A100 camera settings record display values to readable labels.
sonyReleaseMode
const TagDetails Exiv2::Internal::sonyReleaseMode[] extern
Initial value:
= {
        { 0,     N_("Normal")                   },
        { 2,     N_("Burst")                    },
        { 5,     N_("Exposure Bracketing")      },
        { 6,     N_("White Balance Bracketing") },
        { 65535, N_("n/a")                      }
    }
Lookup table to translate Sony release mode values to readable labels.
sonySelfTimerTimeA100
const TagDetails Exiv2::Internal::sonySelfTimerTimeA100[] extern
Initial value:
= {
        { 0, "10s" },
        { 4, "2s"  }
    }
Lookup table to translate Sony A100 camera settings self timer time values to readable labels.
sonySequenceNumber
const TagDetails Exiv2::Internal::sonySequenceNumber[] extern
Initial value:
= {
        { 0,     N_("Single")                    },
        { 65535, N_("n/a")                       }
    }
Lookup table to translate Sony sequence number values to readable labels.
sonySingleFrameBracketingA100
const TagDetails Exiv2::Internal::sonySingleFrameBracketingA100[] extern
Initial value:
= {
        { 0x302, N_("Low")  },
        { 0x702, N_("High") }
    }
Lookup table to translate Sony A100 camera settings single frame bracketing values to readable labels.
sonyWhiteBalance
const TagDetails Exiv2::Internal::sonyWhiteBalance[] extern
Initial value:
= {
        { 0,  N_("Auto")                       },
        { 4,  N_("Manual")                     },
        { 5,  N_("Daylight")                   },
        { 6,  N_("Cloudy")                     },
        { 7,  N_("White Fluorescent")          },
        { 8,  N_("Cool White Fluorescent")     },
        { 9,  N_("Day White Fluorescent")      },
        { 10, N_("Incandescent2")              },
        { 11, N_("Warm White Fluorescent")     },
        { 14, N_("Incandescent")               },
        { 15, N_("Flash")                      },
        { 17, N_("Underwater 1 (Blue Water)")  },
        { 18, N_("Underwater 2 (Green Water)") }
    }
Lookup table to translate Sony WB values to readable labels.
sonyWhiteBalanceBracketingA100
const TagDetails Exiv2::Internal::sonyWhiteBalanceBracketingA100[] extern
Initial value:
= {
        { 0x8, N_("Low")  },
        { 0x9, N_("High") }
    }
Lookup table to translate Sony A100 camera settings white balance bracketing values to readable labels.
sonyWhiteBalanceSettingA100
const TagDetails Exiv2::Internal::sonyWhiteBalanceSettingA100[] extern
Initial value:
= {
        { 0x0000, N_("Auto")                           },
        { 0x0001, N_("Preset")                         },
        { 0x0002, N_("Custom")                         },
        { 0x0003, N_("Color Temperature/Color Filter") },
        { 0x8001, N_("Preset")                         },
        { 0x8002, N_("Custom")                         },
        { 0x8003, N_("Color Temperature/Color Filter") }
    }
Lookup table to translate Sony A100 camera settings white balance setting values to readable labels.
sonyZoneMatchingModeA100
const TagDetails Exiv2::Internal::sonyZoneMatchingModeA100[] extern
Initial value:
= {
        { 0,    N_("Off")      },
        { 1,    N_("Standard") },
        { 2,    N_("Advanced") }
    }
Lookup table to translate Sony A100 camera settings zone matching mode values to readable labels.
tiffFocalPlaneResolutionUnit
const TagDetails Exiv2::Internal::tiffFocalPlaneResolutionUnit[] extern
Initial value:
= {
        { 1, N_("inch")       },
        { 2, N_("meter")      },
        { 3, N_("centimeter") },
        { 4, N_("millimeter") },
        { 5, N_("micrometer") }
    }
FocalPlaneResolutionUnit, TIFF/EP tag 0x9210.
tiffSensingMethod
const TagDetails Exiv2::Internal::tiffSensingMethod[] extern
Initial value:
= {
        { 0, N_("Undefined")               },
        { 1, N_("Monochrome area")         },
        { 2, N_("One-chip color area")     },
        { 3, N_("Two-chip color area")     },
        { 4, N_("Three-chip color area")   },
        { 5, N_("Color sequential area")   },
        { 6, N_("Monochrome linear")       },
        { 7, N_("Trilinear sensor")        },
        { 8, N_("Color sequential linear") }
    }
SensingMethod, TIFF/EP tag 0x9217.